### ISSUE TITLE
Error in converting LLaMA3.1 nemo checkpoint into HF

### ISSUE THREAD

**Issue by aimarz** [NVIDIA/NeMo#10328]
The same as #10013 but in the other direction, that is, from `.nemo` to HF. It happens even in the 24.07 container.

**Describe the bug**

I'm trying to convert LLama3.1-8b nemo checkpoint into huggingface checkpoint using convert_llama_nemo_to_hf.py script. It's giving ``ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}``

Find the complete trace below :

``` [rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py", line 257, in <module>
[rank0]:     replace_hf_weights_and_tokenizer(
[rank0]:   File "/opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py", line 231, in replace_hf_weights_and_tokenizer
[rank0]:     model = AutoModelForCausalLM.from_pretrained(input_hf_path, local_files_only=True, torch_dtype=dtype,)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 523, in from_pretrained
[rank0]:     config, kwargs = AutoConfig.from_pretrained(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 952, in from_pretrained
[rank0]:     return config_class.from_dict(config_dict, **unused_kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 761, in from_dict
[rank0]:     config = cls(**config_dict)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
[rank0]:     self._rope_scaling_validation()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 181, in 
_rope_scaling_validation
[rank0]:     raise ValueError(
[rank0]: ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got 
{'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

**Steps/Code to reproduce bug**

`python <path_to_NeMo>/scripts/checkpoint_converters/convert_llama_hf_to_nemo.py --<arguments>`

**Expected behavior**

Successful conversion of llama3.1-8b nemo checkpoints into hf checkpoint.

**Environment overview**

I'm using nvcr.io/nvidia/nemo:24.07 container (have tried 24.05.llama3.1 as well).

**Comment by aimarz** [comment]
Sorry, I have not tried with the newest dev container. I will lock this issue for now and give it a try.

**Comment by aimarz** [comment]
Yeah it works in the newest container.
