### ISSUE TITLE
Problems Installing

### ISSUE THREAD

**Issue by prashantserai** [NVIDIA/NeMo#1157]
**Describe the bug**
Packaging module doesn't exist

**Steps/Code to reproduce bug**

```
bash-4.1$ envname=myenvname
bash-4.1$ conda create -n $envname python=3.6
bash-4.1$ source activate $envname
(myenvname) bash-4.1$ pip install nemo_toolkit[all]
(myenvname) bash-4.1$ pip install nemo_toolkit[all]
Collecting nemo_toolkit[all]
  Using cached nemo_toolkit-0.11.0-py3-none-any.whl (622 kB)
Collecting scikit-learn
  Downloading scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 3.3 MB/s
Collecting wget
  Using cached wget-3.2.zip (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /homes/3/serai/.conda/envs/asr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1z_m8zcj/wget/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1z_m8zcj/wget/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-28zn03nc
         cwd: /tmp/pip-install-1z_m8zcj/wget/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/homes/3/serai/.conda/envs/asr/lib/python3.6/site-packages/setuptools/__init__.py", line 14, in <module>
        from setuptools.dist import Distribution, Feature
      File "/homes/3/serai/.conda/envs/asr/lib/python3.6/site-packages/setuptools/dist.py", line 21, in <module>
        from setuptools.extern import packaging
      File "/homes/3/serai/.conda/envs/asr/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 61, in load_module
        "distribution.".format(**locals())
    ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**Expected behavior**

nemo toolkit installs successfully and the examples are runnable.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal local servers
 - Method of NeMo install: pip install nemo_toolkit[all]

**Environment details** Python version 3.6, Pip version 20.0, OS: RHEL 6, Pytorch not installed

**Comment by okuchaiev** [comment]
Can you please try ```pip install nemo_toolkit[all]==1.0.0a1``` ?
And/or installing from source (call ./reinstall.sh)?

We don't test NeMo on RHEL, we test on Ubuntu.

The easiest approach on RHEL would be to use NVIDIA Pytorch docker container 20.08

**Comment by okuchaiev** [comment]
closing for now - please re-open if problem persists
