### ISSUE TITLE
Kaldi unittest fails

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/NeMo#116]
======================================================================
ERROR: test_kaldi_dataloader (tests.test_asr.TestASRPytorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/okuchaiev/repos/NeMo/tests/test_asr.py", line 165, in test_kaldi_dataloader
    batch_size=batch_size
  File "/home/okuchaiev/repos/NeMo/collections/nemo_asr/nemo_asr/data_layer.py", line 464, in __init__
    self._dataset = KaldiFeatureDataset(**dataset_params)
  File "/home/okuchaiev/repos/NeMo/collections/nemo_asr/nemo_asr/parts/dataset.py", line 224, in __init__
    for utt_id, feats in kaldi_io.read_mat_scp(feats_path)
  File "/home/okuchaiev/repos/NeMo/collections/nemo_asr/nemo_asr/parts/dataset.py", line 222, in <dictcomp>
    id2feats = {
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/kaldi_io-0.9.1-py3.7.egg/kaldi_io/kaldi_io.py", line 343, in read_mat_scp
    fd = open_or_fd(file_or_fd)
  File "/home/okuchaiev/anaconda3/envs/py37/lib/python3.7/site-packages/kaldi_io-0.9.1-py3.7.egg/kaldi_io/kaldi_io.py", line 63, in open_or_fd
    fd = open(file, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'tests/data/asr/kaldi_an4/feats.scp'

**Comment by redoctopus** [comment]
Reassigning based on conversation in-person

**Comment by okuchaiev** [comment]
done
