### ISSUE TITLE
AttributeError: Can't pickle local object 'FilterbankFeatures.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1194]
Hi guys, 
I am trying to train an ASR with nemo. I preprocessed data as shown on the tutorial. but when I tried to train the model, I have the following error : AttributeError: Can't pickle local object 'FilterbankFeatures.__init__.<locals>.<lambda>'.
Can someone help me ?
Thanks in advance.

**Comment by okuchaiev** [comment]
can you please provide more details? (As in bug template).

But this error can occur if you are using non-ddp backend when training on multi-GPU

**Comment by amejri** [comment]
This is what I have when I tried to execute the script: 

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    train(train_manifest_file, valid_manifest_file, checkpoint_path='/home/lsam/weeks/week_14_21_september/checkpoint'+'/check.th')
  File "main.py", line 26, in train
    trainer.fit(first_asr_model)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in fit
    self.accelerator_backend.train(model, nprocs=self.num_processes)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_spawn_backend.py", line 43, in train
    mp.spawn(self.ddp_train, nprocs=nprocs, args=(self.mp_queue, model,))
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/lsam/anaconda3/envs/nemo_env/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'FilterbankFeatures.__init__.<locals>.<lambda>'

**Comment by amejri** [comment]
You are right. The code works fine with a single GPU. How do I put it on multi-GPU ?

**Comment by niloofarmaani1** [comment]
Hi I have fine tuned the nemo model, and I am trying to save the model using torch.save(quartznet,'fine_tuned')
but I end up with the same error, do you have any idea about it?

**Comment by amejri** [comment]
Hello, to save the model, I have just used this command : quartznet.save_to(path)

**Comment by hoangtuanvu** [comment]
Hi @amejri, how do you fix error when training on multi-gpus?

**Comment by SummerZ723** [comment]
I also met this problem. 
Through check out the docs of pytorch lightning, I found that this error could be solved by adding a parameter " **accelerator='ddp'** " to trainer. 
Therefore, the code works fine with multi-GPU since the doc explains that "**('ddp') is DistributedDataParallel (each gpu on each node trains, and syncs grads)**"
[https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html](url)

**Comment by hzitoun** [comment]
> I also met this problem.
> Through check out the docs of pytorch lightning, I found that this error could be solved by adding a parameter " **accelerator='ddp'** " to trainer.
> Therefore, the code works fine with multi-GPU since the doc explains that "**('ddp') is DistributedDataParallel (each gpu on each node trains, and syncs grads)**"
> [https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html](url)

That is it!! thanks

**Comment by rajeevbaalwan** [comment]
> I also met this problem. Through check out the docs of pytorch lightning, I found that this error could be solved by adding a parameter " **accelerator='ddp'** " to trainer. Therefore, the code works fine with multi-GPU since the doc explains that "**('ddp') is DistributedDataParallel (each gpu on each node trains, and syncs grads)**" [https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html](url)

As per pytorch lightning docs there is no option for 'ddp'. 
https://pytorch-lightning.readthedocs.io/en/latest/accelerators/gpu_basic.html
Also I have tried by providing accelerator="gpu" and devices=4 but getting same error.

**Comment by titu1994** [comment]
Ptl added another argument called trainer.strategy="ddp". All of these flags are set in our configs please refer to them
