### ISSUE TITLE
AttributeError: 'list' object has no attribute 'add_image' in 'swriter.add_image()', when training Tacotron2 whith wandb logging

### ISSUE THREAD

**Issue by khalilRhouma** [NVIDIA/NeMo#1356]
Nemo version: 1.0.0b1
PTL version: 0.9.0

**when running Tacotron2 with wandb logging I got this error** 
`Traceback (most recent call last):
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/hydra/_internal/utils.py", line 203, in run_and_report
    return func()
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    overrides=args.overrides,
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 109, in run
    job_subdir_key=None,
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "aaj/tts/tacotron2_v1.py", line 32, in main
    trainer.fit(tocatron2)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1058, in fit
    results = self.accelerator_backend.spawn_ddp_children(model)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 123, in spawn_ddp_children
    results = self.ddp_train(local_rank, mp_queue=None, model=model, is_master=True)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_backend.py", line 224, in ddp_train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 396, in _evaluate
    eval_results = self.__run_eval_epoch_end(test_mode, outputs, dataloaders, using_eval_result)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 490, in __run_eval_epoch_end
    eval_results = model.validation_epoch_end(eval_results)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/nemo/collections/tts/models/tacotron2.py", line 266, in validation_epoch_end
    add_audio=False,
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/khalil/anaconda3/envs/nemo_1.0.0b1/lib/python3.7/site-packages/nemo/collections/tts/helpers/helpers.py", line 89, in tacotron2_log_to_tb_func
    swriter.add_image(
AttributeError: 'list' object has no attribute 'add_image'`

**Comment by khalilRhouma** [comment]
Just To let you know that I trained Tacotron2 without wandb logging and it worked successfully

**Comment by blisc** [comment]
That makes sense, since I run TTS experiments with the tensorboard logger only and add_image() is tensorboard's API. I'll add a check so it only logs to tensorboard. If you want to log images to WandB, feel free to submit a PR with that change

**Comment by khalilRhouma** [comment]
> That makes sense, since I run TTS experiments with the tensorboard logger only and add_image() is tensorboard's API. I'll add a check so it only logs to tensorboard. If you want to log images to WandB, feel free to submit a PR with that change

How to disable logging images into WandB? I simply want to track the experiment with WandB that's all
