### ISSUE TITLE
When i use GPU to infer, everything is ok. But when i choose CPU, it turn out runtime error: code is too big. I have no idea what is it mean. Did anybody know how can i fix it.

### ISSUE THREAD

**Issue by tianchaolangzi** [NVIDIA/NeMo#1411]
I set batch_size = 1, it still shows runtime error.
But when my test_set only have one wav, it can run successfully.

part of my code:
    neural_factory = nemo.core.NeuralModuleFactory(
        backend=nemo.core.Backend.PyTorch,
        #local_rank=args.local_rank,
        #optimization_level=args.amp_opt_level,
        placement=nemo.core.DeviceType.CPU,
    )

evaluated_tensors = neural_factory.infer(tensors=eval_tensors, checkpoint_dir=load_dir)

The error message:
/opt/conda/lib/python3.6/site-packages/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
  warnings.warn("video reader based on ffmpeg c++ ops not available")
[NeMo I 2020-11-04 09:53:12 collections:152] Dataset loaded with 12203 files totalling 6.17 hours
[NeMo I 2020-11-04 09:53:12 collections:153] 0 files were filtered totalling 0.00 hours
[NeMo I 2020-11-04 09:53:12 stt_infer:138] Evaluating 12203 examples
[NeMo I 2020-11-04 09:53:12 features:144] PADDING: 16
[NeMo I 2020-11-04 09:53:12 features:152] STFT using conv
[NeMo I 2020-11-04 09:53:13 stt_infer:151] ================================
[NeMo I 2020-11-04 09:53:13 stt_infer:152] Number of parameters in encoder: 18894656
[NeMo I 2020-11-04 09:53:13 stt_infer:153] Number of parameters in decoder: 29725
[NeMo I 2020-11-04 09:53:13 stt_infer:154] Total number of parameters in model: 18924381
[NeMo I 2020-11-04 09:53:13 stt_infer:155] ================================
[NeMo I 2020-11-04 09:53:13 actions:1548] Restoring JasperEncoder from asr_checkpoint/JasperEncoder.pt
[NeMo I 2020-11-04 09:53:13 actions:1548] Restoring JasperDecoderForCTC from asr_checkpoint/JasperDecoderForCTC.pt
[NeMo I 2020-11-04 09:53:13 actions:673] Evaluating batch 0 out of 12203
Traceback (most recent call last):
  File "stt_infer.py", line 221, in <module>
    main()
  File "stt_infer.py", line 168, in main
    evaluated_tensors = neural_factory.infer(tensors=eval_tensors, checkpoint_dir=load_dir)
  File "/NeMo/nemo/core/neural_factory.py", line 421, in infer
    modules_to_restore=modules_to_restore,
  File "/NeMo/nemo/backends/pytorch/actions.py", line 1575, in infer
    offload_to_cpu=offload_to_cpu,
  File "/NeMo/nemo/backends/pytorch/actions.py", line 700, in _infer
    use_cache=use_cache,
  File "/NeMo/nemo/backends/pytorch/actions.py", line 362, in __nm_graph_forward_pass
    new_tensors = pmodule(force_pt=True, **call_set)
  File "/NeMo/nemo/backends/pytorch/nm.py", line 160, in __call__
    return self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/NeMo/nemo/collections/asr/audio_preprocessing.py", line 93, in forward
    processed_signal = self.get_features(input_signal, length)
  File "/NeMo/nemo/collections/asr/audio_preprocessing.py", line 385, in get_features
    return self.featurizer(input_signal, length)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/NeMo/nemo/collections/asr/parts/features.py", line 252, in forward
    x = self.stft(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/NeMo/nemo/collections/asr/parts/features.py", line 160, in forward
    return super(STFTPatch, self).transform(input_data)[0]
  File "/opt/conda/lib/python3.6/site-packages/torch_stft/stft.py", line 86, in transform
    padding=0)
RuntimeError: code is too big

**Comment by ericharper** [comment]
Please upgrade to 1.0.0b* version of NeMo. See https://github.com/NVIDIA/NeMo/issues/1091 for a discussion on the latest changes.

**Comment by tianchaolangzi** [comment]
Need update
