### ISSUE TITLE
VAD infer script looks broken

### ISSUE THREAD

**Issue by diego-fustes** [NVIDIA/NeMo#1555]
I'm trying to perform Voice Activity Detection with NeMo using the script _vad_infer.py_ that is included in the examples. However, the following error comes at first:

```
Traceback (most recent call last):
  File "/home/diego/Sutherland/speechanalytics/speechanalyticsapi/speechanalytics/test.py", line 159, in <module>
    main()
  File "/home/diego/Sutherland/speechanalytics/speechanalyticsapi/speechanalytics/test.py", line 89, in main
    'trim_silence': False,
  File "/home/diego/miniconda3/envs/speechanalytics/lib/python3.6/site-packages/nemo/collections/asr/models/classification_models.py", line 110, in setup_test_data
    self._test_dl = self._setup_dataloader_from_config(config=test_data_config)
  File "/home/diego/miniconda3/envs/speechanalytics/lib/python3.6/site-packages/nemo/collections/asr/models/classification_models.py", line 89, in _setup_dataloader_from_config
    batch_size=config['batch_size'],
KeyError: 'batch_size'
```

I've been able to fix it by including the parameter _batch_size_ in the dict passed to the _vad_model.setup_data_ method. After that, the script runs til the end, but it behaves in an unexpected way as it generates only one prediction value (one float) per audio file, while it should be generating one prediction per frame in every audio file... shouldn't it?

**Environment**

Nemo Toolkit version 1.0.0b2

**Comment by fayejf** [comment]
Hi @diego-fustes  Thanks for reporting this. 
You don't need to include the parameter batch_size in the dict passed.  [It's been set here.](https://github.com/NVIDIA/NeMo/blob/9da1d27ddd7f1d5d9b6cd75f7308787976680dd8/nemo/collections/asr/models/classification_models.py#L167) 
There isn't a vad_infer.py in v1.0.0b2. Could you please try main branch and let me know if you still have this issue and share a demo manifests if possible? Thanks!

**Comment by diego-fustes** [comment]
Hi @fayejf ,

you are right, I was running the script from the main branch, but my installed NeMo version was v1.0.0b2. Updating to the main branch fixed the issue. Many thanks!

**Comment by fayejf** [comment]
Thanks for letting me know :)
