### ISSUE TITLE
PTL 1.2.0 upgrade breaks draco training

### ISSUE THREAD

**Issue by mchrzanowski** [NVIDIA/NeMo#1828]
traceback error on draco:
```
Traceback (most recent call last):
  File "/home/dcg-adlr-mchrzanowski-source/NeMo/examples/nlp/machine_translation/enc_dec_nmt.py", line 127, in main
    trainer.fit(mt_model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 471, in fit
    self.call_setup_hook(model)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1072, in call_setup_hook
    model.setup(stage_name)
  File "/home/dcg-adlr-mchrzanowski-source/NeMo/nemo/collections/nlp/models/machine_translation/mt_enc_dec_model.py", line 453, in setup
    self._trainer.accelerator_backend.ddp_plugin.configure_ddp = self.configure_ddp
AttributeError: 'GPUAccelerator' object has no attribute 'ddp_plugin'
```

reverting the changes from [PR 1774](https://github.com/NVIDIA/NeMo/pull/1774) fixes things.

**Comment by ericharper** [comment]
This should be fixed on main now: https://github.com/NVIDIA/NeMo/pull/1829

Please let use know if there are still issues.

**Comment by blisc** [comment]
Closing, reopen if needed
