### ISSUE TITLE
KeyError: 'EvalLoss'

### ISSUE THREAD

**Issue by spakhomov** [NVIDIA/NeMo#229]
I am getting this EvalLoss key error when trying to do a training/validation run using the ASR tutorial. See the command and the output below. Training seems to work ok but not the evaluation step. 

The same error occurs when trying to follow the notebook in the ASR tutorial. Any suggestions on how to fix this? I am using the Docker container that I pulled with this:

docker pull nvcr.io/nvidia/nemo:v0.9

I made sure I had the latest nemo toolkit and nemo asr modules by running pip install.

================================
Here is the terminal output:

root@9bb9ab3869fc:/workspace/nemo_examples/asr# python -m torch.distributed.launch --nproc_per_node=2 /workspace/nemo_examples/asr/jasper.py --batch_size=64 --num_epochs=100 --lr=0.015 --warmup_steps=8000 --weight_decay=0.001 --train_dataset=/home/pakh0002/data/train-manifests/an4_train_manifest.json --eval_datasets /home/pakh0002/data/test-manifests/an4_test_manifest.json --model_config=/workspace/nemo_examples/asr/configs/quartznet15x5.yaml --exp_name=MyLARGE-ASR-EXPERIMENT
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/opt/conda/lib/python3.6/site-packages/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
  warnings.warn("video reader based on ffmpeg c++ ops not available")
/opt/conda/lib/python3.6/site-packages/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
  warnings.warn("video reader based on ffmpeg c++ ops not available")
Could not import torchaudio. Some features might not work.
Could not import torchaudio. Some features might not work.
2019-12-17 18:39:51,009 - INFO - Doing ALL GPU
2019-12-17 18:39:51,300 - INFO - Dataset loaded with 0.71 hours. Filtered 0.00 hours.
2019-12-17 18:39:51,300 - INFO - Parallelizing DATALAYER
2019-12-17 18:39:51,300 - INFO - Have 948 examples to train on.
2019-12-17 18:39:51,301 - INFO - PADDING: 16
2019-12-17 18:39:51,301 - INFO - STFT using conv
2019-12-17 18:39:51,382 - INFO - Dataset loaded with 0.00 hours. Filtered 0.00 hours.
2019-12-17 18:39:51,382 - INFO - Parallelizing DATALAYER
2019-12-17 18:39:51,752 - INFO - ================================
2019-12-17 18:39:51,754 - INFO - Number of parameters in encoder: 18894656
2019-12-17 18:39:51,754 - INFO - Number of parameters in decoder: 29725
2019-12-17 18:39:51,756 - INFO - Total number of parameters in decoder: 18924381
2019-12-17 18:39:51,756 - INFO - ================================
2019-12-17 18:39:51,824 - WARNING - Data Layer does not have any weights to return. This get_weights call returns None.
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
2019-12-17 18:39:51,835 - INFO - Doing distributed training
2019-12-17 18:39:51,858 - INFO - Starting .....
2019-12-17 18:39:51,862 - INFO - Found 2 modules with weights:
2019-12-17 18:39:51,862 - INFO - JasperDecoderForCTC
2019-12-17 18:39:51,862 - INFO - JasperEncoder
2019-12-17 18:39:51,862 - INFO - Total model parameters: 18924381
2019-12-17 18:39:51,862 - INFO - Restoring checkpoint from folder MyLARGE-ASR-EXPERIMENT-lr_0.015-bs_64-e_100-wd_0.001-opt_novograd-ips_1/checkpoints ...
2019-12-17 18:39:51,864 - WARNING - For module JasperEncoder, no file matches  in MyLARGE-ASR-EXPERIMENT-lr_0.015-bs_64-e_100-wd_0.001-opt_novograd-ips_1/checkpoints
2019-12-17 18:39:51,864 - WARNING - Checkpoint folder MyLARGE-ASR-EXPERIMENT-lr_0.015-bs_64-e_100-wd_0.001-opt_novograd-ips_1/checkpoints present but did not restore
2019-12-17 18:39:51,864 - INFO - Starting epoch 0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
2019-12-17 18:39:56,417 - INFO - Step: 0
2019-12-17 18:39:56,421 - INFO - Loss: 380.2557373046875
2019-12-17 18:39:56,421 - INFO - training_batch_WER:   inf%
2019-12-17 18:39:56,422 - INFO - Prediction: ZJWJBITBIZBWBSJWBJZBJQZQBJB BZQVBBQBPBPWIPBNGBYPWQBQBDBDQBWBPBWWBZBIQBBN
2019-12-17 18:39:56,422 - INFO - Reference:      
2019-12-17 18:39:56,422 - INFO - Step time: 2.671168327331543 seconds
2019-12-17 18:39:56,422 - INFO - Doing Evaluation ..............................
Traceback (most recent call last):
  File "/workspace/nemo_examples/asr/jasper.py", line 309, in <module>
    main()
  File "/workspace/nemo_examples/asr/jasper.py", line 305, in main
    batches_per_step=args.iter_per_step)
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 616, in train
    gradient_predivide=gradient_predivide)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 1512, in train
    self._perform_on_iteration_end(callbacks=callbacks)
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 198, in _perform_on_iteration_end
    callback.on_iteration_end()
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/callbacks.py", line 435, in on_iteration_end
    self.action._eval(self._eval_tensors, self, step)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 709, in _eval
    callback._global_var_dict)
  File "/opt/conda/lib/python3.6/site-packages/nemo_asr/helpers.py", line 154, in process_evaluation_epoch
    eloss = torch.mean(torch.stack(global_vars['EvalLoss'])).item()
KeyError: 'EvalLoss'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', '/workspace/nemo_examples/asr/jasper.py', '--local_rank=1', '--batch_size=64', '--num_epochs=100', '--lr=0.015', '--warmup_steps=8000', '--weight_decay=0.001', '--train_dataset=/home/pakh0002/data/train-manifests/an4_train_manifest.json', '--eval_datasets', '/home/pakh0002/data/test-manifests/an4_test_manifest.json', '--model_config=/workspace/nemo_examples/asr/configs/quartznet15x5.yaml', '--exp_name=MyLARGE-ASR-EXPERIMENT']' returned non-zero exit status 1.

**Comment by okuchaiev** [comment]
Hi, I can't reproduce your error. Here is what I tried:
Step 1: 
```bash
sudo docker run --runtime=nvidia -it --rm -v /home/okuchaiev/repos/NeMo:/NeMo -v /mnt/D1:/mnt/D1 --shm-size=8g -p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit stack=67108864 nvcr.io/nvidia/nemo:v0.9
```
Step 2:
```bash
python -m torch.distributed.launch --nproc_per_node=2 /workspace/nemo_examples/asr/jasper.py --batch_size=64 --num_epochs=100 --lr=0.015 --warmup_steps=8000 --weight_decay=0.001 --train_dataset=/mnt/D1/Data/an4_dataset/an4_train.json --eval_datasets /mnt/D1/Data/an4_dataset/an4_val.json --model_config=/workspace/nemo_examples/asr/configs/quartznet15x5.yaml --exp_name=MyLARGE-ASR-EXPERIMENT
``` 
And it starts with validation and does training. The hyperparams are bad here, but that isn't the point.

Do you: (1) have 2 GPUs available to your docker (since you are attempting to train on 2 GPUs). (2) is your filepath correct and exists inside the docker /home/pakh0002/data/test-manifests/an4_test_manifest.json   ?

**Comment by spakhomov** [comment]
Thanks for the quick response! I figured out the cause of this error - turns out the test manifest file was corrupted, so global variables dictionary never got the loss because there was no audio to calculate it from. I fixed the manifest and that took care of the error. Might be good to add some input checking at some point in the future. I'll close this issue. Thanks again!
