### ISSUE TITLE
Error while training an NMT Model on Machine

### ISSUE THREAD

**Issue by this-is-ac** [NVIDIA/NeMo#2328]
## Issue : 
I'm trying to train a NMT model using Nemo on my machine. I followed the instructions from the [documentation](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/machine_translation.html) using the example script and the default configuration file. This runs perfectly on colab, but when I'm trying it on my local machine, I get the following error :
( I'm using branch r1.0.0rc1 and have tried using the Nemo docker image and installing from a repository on a PyTorch Image.)

## The error : 

Traceback (most recent call last):
  File "enc_dec_nmt.py", line 105, in main
    cfg = update_model_config(default_cfg, cfg)
  File "/opt/conda/lib/python3.6/site-packages/nemo/utils/config_utils.py", line 79, in update_model_config
    model_cls = _add_subconfig_keys(model_cls, update_cfg, subconfig_key='optim')
  File "/opt/conda/lib/python3.6/site-packages/nemo/utils/config_utils.py", line 169, in _add_subconfig_keys
    subconfig = OmegaConf.merge(update_subconfig, subconfig)
ValueError: Cannot merge with a None config
	full_key: model.optim
	reference_type=Any
	object_type=dict

## Here's the code I'm running :

!python enc_dec_nmt.py \
  -cn aayn_base \
  do_training=true \
  trainer.gpus=1 \
  ~trainer.max_epochs \
  +trainer.max_steps=100000 \
  +trainer.val_check_interval=1000 \
  +exp_manager.exp_dir=/workspace/dirname/exp \
  +exp_manager.create_checkpoint_callback=True \
  +exp_manager.checkpoint_callback_params.monitor=val_sacreBLEU \
  +exp_manager.checkpoint_callback_params.mode=max \
  +exp_manager.checkpoint_callback_params.save_top_k=5 \
  model.preproc_out_dir=/workspace/dirname/preproc \
  model.train_ds.use_tarred_dataset=true \
  model.train_ds.lines_per_dataset_fragment=1000000 \
  model.train_ds.num_batches_per_tarfile=200 \
  model.train_ds.src_file_name=/workspace/dirname/train_in \
  model.train_ds.tgt_file_name=/workspace/dirname/train_out \
  model.validation_ds.src_file_name=/workspace/dirname/splits/val_in \
  model.validation_ds.tgt_file_name=/workspace/dirname/val_out \
  model.encoder_tokenizer.vocab_size=32000 \
  model.decoder_tokenizer.vocab_size=32000 \
  ~model.test_ds 

(I have put the aayn_base.yaml file inside a folder _conf_ in the same directory)

## Here's the full stack trace

Traceback (most recent call last):
  File "enc_dec_nmt.py", line 136, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/config/hydra_runner.py", line 103, in wrapper
    strict=None,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/opt/conda/lib/python3.6/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "enc_dec_nmt.py", line 105, in main
    cfg = update_model_config(default_cfg, cfg)
  File "/opt/conda/lib/python3.6/site-packages/nemo/utils/config_utils.py", line 79, in update_model_config
    model_cls = _add_subconfig_keys(model_cls, update_cfg, subconfig_key='optim')
  File "/opt/conda/lib/python3.6/site-packages/nemo/utils/config_utils.py", line 169, in _add_subconfig_keys
    subconfig = OmegaConf.merge(update_subconfig, subconfig)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 321, in merge
    target.merge_with(*others[1:])
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 331, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
ValueError: Cannot merge with a None config
	full_key: model.optim
	reference_type=Any
	object_type=dict

Any help is greatly appreciated. Thank you!

**Comment by okuchaiev** [comment]
Is your training data in "tarred" dataset format (looks like not). If it is not in tarred format, please remove these from command line arguments: 
```
model.train_ds.use_tarred_dataset=true
model.train_ds.lines_per_dataset_fragment=1000000
model.train_ds.num_batches_per_tarfile=200
```
I believe it is false by default. 
Also, please try 1.0.1 version.

**Comment by this-is-ac** [comment]
Thanks for getting back to me!

My data isn't in "tarred" format currently. Even creating it using the Hydra config and training data gives the same error. The code is given on the documentation page, am attaching it here.

```
python enc_dec_nmt.py \
  -cn aayn_base \
  do_training=false \
  model.preproc_out_dir=/workspace/dirname/preproc \
  model.train_ds.use_tarred_dataset=true \
  model.train_ds.lines_per_dataset_fragment=1000000 \
  model.train_ds.num_batches_per_tarfile=200 \
  model.train_ds.src_file_name=train.tokenized.en \
  model.train_ds.tgt_file_name=train.tokenized.hi \
  model.validation_ds.src_file_name=validation.tokenized.en \
  model.validation_ds.tgt_file_name=validation.tokenized.hi \
  model.encoder_tokenizer.vocab_size=32000 \
  model.decoder_tokenizer.vocab_size=32000 \
  ~model.test_ds \
  trainer.gpus=[0,1] \
  +trainer.fast_dev_run=true \
  exp_manager=null \
```

Also, yes "use_tarred_dataset" is **false** by default, I removed those 3 lines as you suggested and it still gives me the same error. I shall try it with the 1.0.1 version.

On another note, if the data is not in tarred format and I supply "use_tarred_dataset" as **true**, the code first creates the tarred dataset and then trains the model, correct?

**Comment by this-is-ac** [comment]
Hello @okuchaiev ,

Just a quick update. Seems to be working fine with version 1.0.1. I was able to create the tarred dataset and have started the training. Thanks a ton!
