### ISSUE TITLE
DDP-related(?): all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by dh7ahn** [NVIDIA/NeMo#2458]
**Describe the bug**

"speech_to_text_bpe.py"(ASR example) with ddp (8-gpus) failed to run.
It produced a "RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable"

**Steps/Code to reproduce bug**

After generating the manifest for LibriSpeech dataset  and tokenization, I ran the following script in a command line
(Below codes are from the comments in examples/asr directory, actually)

python speech_to_text_bpe.py \
    model.train_ds.manifest_filepath=librispeech/train_all.json \
    model.validation_ds.manifest_filepath=librispeech/dev_all.json \
    model.tokenizer.dir=librispeech/tokenizer_spe_bpe_v5000 \
    model.tokenizer.type=bpe \
    trainer.gpus=-1 \
    trainer.accelerator="ddp" \
    trainer.max_epochs=100 \
    model.optim.name="adamw" \
    model.optim.lr=0.001 \
    model.optim.betas=[0.9,0.999] \
    model.optim.weight_decay=0.0001 \
    model.optim.sched.warmup_steps=2000
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name="exp.tst" \
    exp_manager.wandb_logger_kwargs.project="prj.tst"

**Expected behavior**

It should run without errors

**Environment overview (please complete the following information)**

 - Environment location: NVIDIA V100 x8, docker 
 - Method of NeMo install: from source (git-cloned on 10 July, installed with reinstall.sh)

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 18.04.5 LTS
- PyTorch version: 1.7.1+cu110
- Python version: 3.8.5

**Additional context**

Example: GPU model

---
No progress after installing Nemo. :( 
Any help would be appreciated.

**Comment by titu1994** [comment]
This is not a Nemo bug, please make sure nvidia-smi shows that all GPUs are free and not currently being used by other processes. Under DDP only 1 run can use multi gpu.

**Comment by dh7ahn** [comment]
I know it's not a NeMo bug, and all the GPUs are free at the time of launching the trainer (confirmed via nvidia-smi). Rather, I'd like to know how to run it properly under DDP, which I missed probably. 
When I  run the command in the above, it seems to be launched multiple times (same outputs are repeated as many times as the number of GPUs) and later processes don't seem to get one (probably former process takes them all?) 
What can I do to use it properly under DDP?

**Comment by titu1994** [comment]
It depends on your setup and sadly I'm not familiar with NCCL and other related technology for DDP. As far as I know it should work out if the box for 2 GPUs

**Comment by johnchienbronci** [comment]
I'm using 2 GPUs and getting the same error
GPU: RTX-4090
Any solve for this error :frowning: ?

nemo_toolkit: 1.23.0
```

python speech_to_text_finetune.py \
    --config-path="conf/asr_finetune" \
    --config-name="speech_to_text_finetune"
```


```
Creating a Lhotse DynamicCutSampler (bucketing is disabled, (max_batch_duration=300.0 max_batch_size=8)
[NeMo I 2024-10-08 08:41:19 collections:196] Dataset loaded with 4709 files totalling 4.43 hours
[NeMo I 2024-10-08 08:41:19 collections:197] 0 files were filtered totalling 0.00 hours
[NeMo W 2024-10-08 08:41:19 modelPT:612] Trainer wasn't specified in model constructor. Make sure that you really wanted it.
[NeMo I 2024-10-08 08:41:19 modelPT:723] Optimizer config = AdamW (
    Parameter Group 0
        amsgrad: False
        betas: [0.9, 0.98]
        capturable: False
        differentiable: False
        eps: 1e-08
        foreach: None
        fused: None
        lr: 0.0001
        maximize: False
        weight_decay: 0.001
    )
[NeMo W 2024-10-08 08:41:19 lr_scheduler:895] Neither `max_steps` nor `iters_per_batch` were provided to `optim.sched`, cannot compute effective `max_steps` !
    Scheduler will not be instantiated !
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
NOTE! Installing ujson may make loading annotations faster.
rank 1
Error executing job with overrides: []
Traceback (most recent call last):
  File "speech_to_text_finetune.py", line 225, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nemo/core/config/hydra_runner.py", line 129, in wrapper
    _run_hydra(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "speech_to_text_finetune.py", line 202, in main
    asr_model = get_base_model(trainer, cfg)
  File "speech_to_text_finetune.py", line 105, in get_base_model
    asr_model = ASRModel.from_pretrained(model_name=pretrained_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nemo/core/classes/common.py", line 863, in from_pretrained
    instance = class_.restore_from(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nemo/core/classes/modelPT.py", line 449, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nemo/core/connectors/save_restore_connector.py", line 241, in restore_from
    loaded_params = self.load_config_and_state_dict(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/nemo/core/connectors/save_restore_connector.py", line 165, in load_config_and_state_dict
    instance = instance.to(map_location)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 55, in to
    return super().to(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 854, in _apply
    self._buffers[key] = fn(buf)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank: 1] Child process with PID 100646 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
```
