### ISSUE TITLE
bert-case-chinese is not supported 

### ISSUE THREAD

**Issue by zifeis** [NVIDIA/NeMo#2483]
using bert-case-chinese as pre-trained model, but has this issue:

[NeMo I 2021-07-14 13:41:17 bert_module:54] Restoring weights from /data/cmrc2018/bert-base-chinese/pytorch_model.bin
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/tlt-nemo/nlp/question_answering/scripts/train.py", line 118, in main
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/nlp/models/question_answering/qa_model.py", line 61, in __init__
    self.bert_model = get_lm_model(
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/nlp/modules/common/lm_utils.py", line 92, in get_lm_model
    model.restore_weights(restore_path=checkpoint_file)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/nlp/modules/common/bert_module.py", line 79, in restore_weights
    assert len(pretrained_dict) == len(model_dict)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tlt-nemo/nlp/question_answering/scripts/train.py", line 140, in <module>
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/config/hydra_runner.py", line 98, in wrapper
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 237, in run_and_report
    assert mdl is not None
AssertionError
2021-07-14 06:41:18,254 [INFO] tlt.components.docker_handler.docker_handler: Stopping container.

Training with TLT, backend is Nemo bugs

git clone https://huggingface.co/bert-base-chinese

tlt question_answering train \
                        -e /specs/question_answering/train_bert.txt \
                        -g 1  \
                        -k 'tlt_encode' \
                        -r /results/question_answering/train \
                        training_ds.file=/data/cmrc2018/squad-style-data/cmrc2018_train.json \
                        validation_ds.file=/data/cmrc2018/squad-style-data/cmrc2018_dev.json \
                        trainer.max_epochs=2 \
                        trainer.val_check_interval=1.0 \
                        training_ds.num_workers=4 \
                        validation_ds.num_workers=4

[train_bert.txt](https://github.com/NVIDIA/NeMo/files/6816666/train_bert.txt)

**Comment by yzhang123** [comment]
@zifeis  no need to provide vocab , lm_checkpoint, confile_file. only pretrained_model_name is needed.

**Comment by zifeis** [comment]
@yzhang123 Thanks for your feedback, I am fine-tuning the model for down stream Task (QA), therefore the pre-trained model is needed. According to the documentation, it seems like Nemo doesn't provide the pre-trained bert-case-chinese model. I am wondering how I can fine-tune a QA model based on bert-case-chinese pre-trained model. Thanks.

**Comment by yzhang123** [comment]
@zifeis it is supported, all huggingface bert model encoders are supported. when you use those, simply replace the `pretrained_language_model` config argument from default `bert-base-cased` to your huggingface model name. This means no explicity checkpoint, vocab etc need to be provided.

**Comment by magiczixiao** [comment]
@yzhang123 Thank you for your answer. Do you mean that you do not need to load the .pt file of the pre-trained model when you fine-tune the downstream task from the pre-trained model? So how does NeMo obtain the weight parameters of the pre-trained model?
