### ISSUE TITLE
Speech Data Explorer filtering on text throws TypeError if an int or float is used as filter parameter

### ISSUE THREAD

**Issue by KathyReid** [NVIDIA/NeMo#2543]
**Describe the bug**
On the Speech Data Explorer, on the "Samples" page, using an `int` or a `float` value to filter text by results in the Flask app throwing a TypeError such as: 

```
10.2.48.115 - - [23/Jul/2021 14:40:13] "POST /_dash-update-component HTTP/1.1" 500 -
[2021-07-23 14:44:01,300] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/kathyreid/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kathyreid/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kathyreid/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kathyreid/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kathyreid/.local/lib/python3.8/site-packages/dash/dash.py", line 1096, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/kathyreid/.local/lib/python3.8/site-packages/dash/dash.py", line 1017, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "data_explorer.py", line 565, in update_datatable
    data_view = [x for x in data_view if filter_value in str(x[col_name])]
  File "data_explorer.py", line 565, in <listcomp>
    data_view = [x for x in data_view if filter_value in str(x[col_name])]
TypeError: 'in <string>' requires string as left operand, not float
```
Here is a visual: 

![Screenshot from 2021-07-23 14-45-33](https://user-images.githubusercontent.com/114158/126738670-5bff6749-3d56-4812-8004-7b5a9a70765d.png)

**Steps/Code to reproduce bug**

* Go to [IP address that SDE is running through on Flask/samples]
* In the Filter row of the table, enter an `int` or `float` value in the `text` column
* The terminal in which Flask is running will throw the error 

**Expected behavior**

I expect SDE to filter for numbers - so that we can inspect a dataset to see if it has been properly normalized. 

**Environment overview (please complete the following information)**

* Environment, bare metal localhost running Ubuntu Linux 20.04 LTS, running Python 3.8.10
* Install method - git clone from GitHub, SDE is spawned with 
* `$ python3 data_explorer.py ../../scripts/dataset_processing/commonvoice_train_manifest.json  `

* I am evaluating datasets using SDE

**Comment by ekmb** [comment]
@KathyReid try adding quotes around the number, for example `"20"`, the text column expects a string.

**Comment by KathyReid** [comment]
Thanks so much @ekmb, confirming that encasing the `str` in `"` works correctly. 
Closing issue.
