### ISSUE TITLE
Error in create_tarred_transformer_lm_dataset.py

### ISSUE THREAD

**Issue by pehonnet** [NVIDIA/NeMo#2544]
**Describe the bug**

When trying to prepare data for ASR neural LM training, using the script `scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py` getting the following error (and a few preceding log lines):
```
[Parallel(n_jobs=-2)]: Done  68 out of 128 | elapsed:   10.6s remaining:    9.3s
[Parallel(n_jobs=-2)]: Done  81 out of 128 | elapsed:   11.4s remaining:    6.6s
[Parallel(n_jobs=-2)]: Done  94 out of 128 | elapsed:   12.0s remaining:    4.3s
[Parallel(n_jobs=-2)]: Done 107 out of 128 | elapsed:   12.6s remaining:    2.5s
[Parallel(n_jobs=-2)]: Done 120 out of 128 | elapsed:   13.5s remaining:    0.9s
[Parallel(n_jobs=-2)]: Done 128 out of 128 | elapsed:   14.1s finished
Traceback (most recent call last):
  File "./scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py", line 318, in <module>
    main()
  File "./scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py", line 299, in main
    chunk_paths, chunk_lens = __tokenize_text(
  File "./scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py", line 174, in __tokenize_text
    chunk = np.asarray(chunk, dtype=np.int64)
  File "/home/pe.honnet/Tools/miniconda3/envs/nemo/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Read 1000000 lines: : 1048576 lines [00:18, 57331.13 lines/s]
```

**Steps/Code to reproduce bug**
Command run as follows
```bash
python ./scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py \
  --text_path=training_data.txt \
  --data_root=./data/prep_nn_lm \
  --tokenizer_model=conformer_ctc_large/tokenizer/tokenizer.model \
  --tokenizer_vocab_file=bert_uncased_vocab.txt \
  --tokenizer_name='bert-base-uncased'
```
I have tried using the conformer ctc tokenizer vocab as well with the same error.

**Environment overview**

 - nemo installed with `reinstall.sh` script, on CentOS 8.0
 
**Environment details**

commit used: 034941566 (HEAD -> main, origin/main, origin/HEAD) Merge bugfixes and doc updates from 1.2.0 to main (#2533)

**Comment by VahidooX** [comment]
Generally text datasets for LM are not that large that you may need tarred datasets. You may just pass the plain train text file during the training and no need for tarred datasets. 
@AlexGrinch  would you please check this bug?

**Comment by titu1994** [comment]
@AlexGrinch please take a look.

**Comment by AlexGrinch** [comment]
Until recently we only supported yttm tokenizer. However, the support of HF and SentencePiece has been added in https://github.com/NVIDIA/NeMo/pull/2690.

Please, use `examples/nlp/machine_translation/create_tarred_monolingual_dataset.py` as in the LM training documentation (https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/language_modeling.html) instead of `scripts/asr_language_modeling/neural_rescorer/create_tarred_transformer_lm_dataset.py`.
