### ISSUE TITLE
requirements_nlp.txt is not enough

### ISSUE THREAD

**Issue by PeganovAnton** [NVIDIA/NeMo#2688]
**Describe the bug**

Installing `requirements_nlp.txt` is not enough to import `nemo.collections.nlp`.

**Steps/Code to reproduce bug**

1. Create new `conda` `Python 3.8` environment
2. Install PyTorch 1.8.2
3. Run `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[nlp]`
4. Run code
```python
from nemo.collections import nlp as nemo_nlp
```
5. You will get traceback
```
[NeMo W 2021-08-17 21:51:45 optimizers:47] Apex was not found. Using the lamb optimizer will error out.
[NeMo W 2021-08-17 21:51:46 __init__:22] `pynini` is not installed !
    Please run the `nemo_text_processing/setup.sh` scriptprior to usage of this toolkit.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/nlp/models/__init__.py", line 16, in <module>
    from nemo.collections.nlp.models.duplex_text_normalization import (
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/nlp/models/duplex_text_normalization/__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.duplex_text_normalization.duplex_decoder import DuplexDecoderModel
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/nlp/models/duplex_text_normalization/duplex_decoder.py", line 21, in <module>
    from nemo_text_processing.text_normalization.normalize_with_audio import PYNINI_AVAILABLE, NormalizerWithAudio
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo_text_processing/text_normalization/normalize_with_audio.py", line 25, in <module>
    from nemo.collections.asr.metrics.wer import word_error_rate
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/asr/modules/__init__.py", line 15, in <module>
    from nemo.collections.asr.modules.audio_preprocessing import (
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/asr/modules/audio_preprocessing.py", line 24, in <module>
    from nemo.collections.asr.parts.preprocessing.features import FilterbankFeatures
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/asr/parts/preprocessing/__init__.py", line 16, in <module>
    from nemo.collections.asr.parts.preprocessing.features import (
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/asr/parts/preprocessing/features.py", line 37, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
```

**Expected behavior**

No errors

**Environment overview (please complete the following information)**

 - Environment location: Bare metal
 - Method of NeMo install: `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[nlp]`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04.2 LTS
- PyTorch version: 1.8.2
- Python version: 3.8

**Comment by titu1994** [comment]
Thanks for notifying us of this. @blisc could you send a PR to cleanup the refactor of the torch_tts

**Comment by blisc** [comment]
> Thanks for notifying us of this. @blisc could you send a PR to cleanup the import refactor of the torch_tts

This is not a result of `torch_tts` if nlp is importing asr for whatever reason. You need to make nlp depend on asr or move the imported code to the common collection. Please tag whoever is wrote this portion of code:
```
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo/collections/nlp/models/duplex_text_normalization/duplex_decoder.py", line 21, in <module>
    from nemo_text_processing.text_normalization.normalize_with_audio import PYNINI_AVAILABLE, NormalizerWithAudio
  File "/home/lab/anaconda3/envs/tmp/lib/python3.8/site-packages/nemo_text_processing/text_normalization/normalize_with_audio.py", line 25, in <module>
    from nemo.collections.asr.metrics.wer import word_error_rate
```

**Comment by blisc** [comment]
@PeganovAnton Can you look into this or ping the slack channel to find out who introduced this?

**Comment by ekmb** [comment]
This is due to the import from `nemo_text_processing` in the nlp collections, I'll take a look at this
