### ISSUE TITLE
module 'nemo.collections' has no attribute 'nlp'

### ISSUE THREAD

**Issue by atptour2017** [NVIDIA/NeMo#2707]
**Describe the bug**

When I import nemo.collections.nlp module in my code, I got "AttributeError: module 'nemo.collections' has no attribute 'nlp'".

/Users/chendan/.virtualenvs/nemo/bin/python3.6 /Users/chendan/PycharmProjects/nemo_learn/tts_test.py
[NeMo W 2021-08-22 21:52:34 optimizers:47] Apex was not found. Using the lamb optimizer will error out.
[NeMo W 2021-08-22 21:52:35 nemo_logging:349] /Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
    
[NeMo W 2021-08-22 21:52:37 experimental:28] Module <class 'nemo.collections.asr.data.audio_to_text_dali.AudioToCharDALIDataset'> is experimental, not ready for production and is not fully supported. Use at your own risk.
Traceback (most recent call last):
  File "/Users/chendan/PycharmProjects/nemo_learn/tts_test.py", line 4, in <module>
    import nemo.collections.nlp as nemo_nlp
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/__init__.py", line 16, in <module>
    from nemo.collections.nlp.models.duplex_text_normalization import (
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/duplex_text_normalization/__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.duplex_text_normalization.duplex_decoder import DuplexDecoderModel
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/duplex_text_normalization/duplex_decoder.py", line 25, in <module>
    import nemo.collections.nlp.data.text_normalization.constants as constants
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/data/text_normalization/__init__.py", line 14, in <module>
    from nemo.collections.nlp.data.text_normalization.decoder_dataset import TextNormalizationDecoderDataset
  File "/Users/chendan/.virtualenvs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/data/text_normalization/decoder_dataset.py", line 21, in <module>
    import nemo.collections.nlp.data.text_normalization.constants as constants
AttributeError: module 'nemo.collections' has no attribute 'nlp'

Process finished with exit code 1

**Steps/Code to reproduce bug**

pip install nemo_toolkit[all]
import nemo.collections.nlp as nemo_nlp

**Expected behavior**

Importing nemo.collections.nlp be successful.

**Environment overview (please complete the following information)**

 - Environment location: Mac OS
 - Method of NeMo install: pip install nemo_toolkit[all]

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Mac OS 10.15.7
- PyTorch version: 1.9.0
- Python version: 3.6.11

**Additional context**

No GPU

**Comment by blisc** [comment]
This is an known issue: #2679. It has been fixed in `main` and will be pushed to pypip as part of the `r1.3.0` release scheduled for the end of this month.
