### ISSUE TITLE
AttributeError: 'dict' object has no attribute '_get_node_flag'

### ISSUE THREAD

**Issue by lalalalallalaladadada** [NVIDIA/NeMo#2797]
Hi, I installed the nemo 1.3.0 latest version recently and find there is an attribute error as shown below. Although I have reinstall my environment for a few times, it still have this error. Has anyone encounter this recently with NeMo 1.3.0?
my code：
quartznet = nemo_asr.models.EncDecCTCModel.restore_from("./model/QuartzNet15x5-Zh-NR.nemo",strict=False)

error：
 AttributeError: 'dict' object has no attribute '_get_node_flag'

**Comment by titu1994** [comment]
Please post the full stack trace

**Comment by titu1994** [comment]
Also you might need to update your Hydra and Omegaconf versions.

**Comment by lalalalallalaladadada** [comment]
Thank you for your reply. I have updated Hydra and omegaconf. the version is 2.1.1.However, the following errors are still reported:
Traceback (most recent call last):
  File "./test.py", line 21, in <module>
    quartznet.setup_training_data(train_data_config=params['model']['train_ds'])
  File "/python3.7/site-packages/nemo/collections/asr/models/ctc_models.py", line 423, in setup_training_data
    self._train_dl = self._setup_dataloader_from_config(config=train_data_config)
  File "/python3.7/site-packages/nemo/collections/asr/models/ctc_models.py", line 348, in _setup_dataloader_from_config
    audio_to_text_dataset.inject_dataloader_value_from_model_config(self.cfg, config, key='sample_rate')
  File "/python3.7/site-packages/nemo/collections/asr/data/audio_to_text_dataset.py", line 55, in inject_dataloader_value_from_model_config
    with open_dict(dataloader_cfg):
  File "/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/python3.7/site-packages/omegaconf/omegaconf.py", line 943, in open_dict
    prev_state = config._get_node_flag("struct")
AttributeError: 'dict' object has no attribute '_get_node_flag'

**Comment by lalalalallalaladadada** [comment]
Thank you for your reply. I have updated Hydra and omegaconf. the version is 2.1.1.However, the following errors are still reported:
Traceback (most recent call last):
File "./test.py", line 21, in
quartznet.setup_training_data(train_data_config=params['model']['train_ds'])
File "/python3.7/site-packages/nemo/collections/asr/models/ctc_models.py", line 423, in setup_training_data
self._train_dl = self._setup_dataloader_from_config(config=train_data_config)
File "/python3.7/site-packages/nemo/collections/asr/models/ctc_models.py", line 348, in _setup_dataloader_from_config
audio_to_text_dataset.inject_dataloader_value_from_model_config(self.cfg, config, key='sample_rate')
File "/python3.7/site-packages/nemo/collections/asr/data/audio_to_text_dataset.py", line 55, in inject_dataloader_value_from_model_config
with open_dict(dataloader_cfg):
File "/python3.7/contextlib.py", line 112, in enter
return next(self.gen)
File "/python3.7/site-packages/omegaconf/omegaconf.py", line 943, in open_dict
prev_state = config._get_node_flag("struct")
AttributeError: 'dict' object has no attribute '_get_node_flag'
> 
> 
> Please post the full stack trace

**Comment by titu1994** [comment]
These methods take OmegaConf DictConfig objects as values - not python dict. You should use Omegaconf to load yaml config files. Please do from omegaconf import OmegaConf

Then 
 params = OmegaConf.create(params) and finally pass the value of params.model.train_ds to the method

**Comment by lalalalallalaladadada** [comment]
> 
> 
> These methods take OmegaConf DictConfig objects as values - not python dict. You should use Omegaconf to load yaml config files. Please do from omegaconf import OmegaConf
> 
> Then
> params = OmegaConf.create(params) and finally pass the value of params.model.train_ds to the method

let me have a try,thanks

**Comment by titu1994** [comment]
Fixed via https://github.com/NVIDIA/NeMo/pull/2802
