### ISSUE TITLE
CTC segmentation fails with dict' object has no attribute 'get_node flag' when using other pretrained model

### ISSUE THREAD

**Issue by khengkok** [NVIDIA/NeMo#2803]
**Description of bug**: 

The cut-audio.py script fails if using models other than QuartzNet15x5Base-En, e.g. stt_en_quartznet15x5 or stt_en_jasper10x5dr. 

Traceback (most recent call last):
  File "tools/ctc_segmentation/scripts/cut_audio.py", line 299, in <module>
    stats = process_alignment(alignment_file, args)
  File "tools/ctc_segmentation/scripts/cut_audio.py", line 205, in process_alignment
    add_transcript_to_manifest(
  File "tools/ctc_segmentation/scripts/cut_audio.py", line 59, in add_transcript_to_manifest
    transcripts = get_transcript(manifest_original, asr_model, batch_size)
  File "tools/ctc_segmentation/scripts/cut_audio.py", line 93, in get_transcript
    asr_model.setup_test_data(
  File "/home/markk/miniconda3/envs/dlenv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 482, in setup_test_data
    self._test_dl = self._setup_dataloader_from_config(config=test_data_config)
  File "/home/markk/miniconda3/envs/dlenv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 348, in _setup_dataloader_from_config
    audio_to_text_dataset.inject_dataloader_value_from_model_config(self.cfg, config, key='sample_rate')
  File "/home/markk/miniconda3/envs/dlenv/lib/python3.8/site-packages/nemo/collections/asr/data/audio_to_text_dataset.py", line 55, in inject_dataloader_value_from_model_config
    with open_dict(dataloader_cfg):
  File "/home/markk/miniconda3/envs/dlenv/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/markk/miniconda3/envs/dlenv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 943, in open_dict
    prev_state = config._get_node_flag("struct")
AttributeError: 'dict' object has no attribute '_get_node_flag'

**Steps/Code to reproduce bug**

The script I am using as follows:
MODEL=stt_en_quartznet15x5
OUTPUT_DIR=output
TOOLS_DIR=tools/ctc_segmentation/scripts
DATA_DIR=data
WINDOW=16000
OFFSET=0
THRESHOLD=-5

python $TOOLS_DIR/prepare_data.py \
--audio_format '.wav'  \
--in_text $DATA_DIR  \
--output_dir $OUTPUT_DIR/processed  \
--language 'eng' \
--model $MODEL \
--audio_dir $DATA_DIR

python $TOOLS_DIR/run_ctc_segmentation.py \
--output_dir $OUTPUT_DIR \
--data $OUTPUT_DIR/processed \
--model $MODEL \
--window_len $WINDOW \
--no_parallel

python $TOOLS_DIR/cut_audio.py \
--output_dir $OUTPUT_DIR \
--model $MODEL \
--alignment $OUTPUT_DIR/segments/ \
--threshold $THRESHOLD \
--offset $OFFSET

**Environment **

nemo v1.3.0 
python 3.8.11

**Comment by titu1994** [comment]
Fixed via https://github.com/NVIDIA/NeMo/pull/2802
