### ISSUE TITLE
Transcribing with existing Conformer RNNT (tokenizer missing)

### ISSUE THREAD

**Issue by pehonnet** [NVIDIA/NeMo#2993]
**Describe the bug**

When trying to transcribe (or even import) Conformer transducer model, the following error comes:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/NeMo/nemo/core/classes/common.py", line 705, in from_pretrained
    instance = class_.restore_from(
  File "~/NeMo/nemo/core/classes/modelPT.py", line 270, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "~/NeMo/nemo/core/connectors/save_restore_connector.py", line 136, in restore_from
    instance = calling_cls.from_config_dict(config=conf)
  File "~/NeMo/nemo/core/classes/common.py", line 493, in from_config_dict
    raise e
  File "~/NeMo/nemo/core/classes/common.py", line 488, in from_config_dict
    instance = cls(cfg=config)
  File "~/NeMo/nemo/collections/asr/models/rnnt_bpe_models.py", line 124, in __init__
    self._setup_tokenizer(cfg.tokenizer)
  File "~/NeMo/nemo/collections/asr/parts/mixins/mixins.py", line 74, in _setup_tokenizer
    model_path = self.register_artifact('tokenizer.model_path', model_path)
  File "~/NeMo/nemo/core/classes/modelPT.py", line 202, in register_artifact
    return self._save_restore_connector.register_artifact(self, config_path, src, verify_src_exists)
  File "~/NeMo/nemo/core/connectors/save_restore_connector.py", line 280, in register_artifact
    raise FileNotFoundError(
FileNotFoundError: src path does not exist or it is not a path in nemo file. src value I got was: /tokenizers/nemo_asr_set/nemo_asr_set_1.4/no_appen/tokenizer_spe_unigram_v1024/tokenizer.model. Absolute: /tokenizers/nemo_asr_set/nemo_asr_set_1.4/no_appen/tokenizer_spe_unigram_v1024/tokenizer.model

```
**Steps/Code to reproduce bug**
Either directly in python:
```bash
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name="stt_en_conformer_transducer_large")
```
or when using the transcribe script:
```bash
python examples/asr/transcribe_speech.py  pretrained_name="stt_en_conformer_transducer_large" audio_dir="some_data"
```

Also when untarring the .nemo file, there is no tokenizer folder available as opposed to what is there in the conformer-ctc models.

**Expected behavior**

**Environment overview (please complete the following information)**
Nemo installed using ./reinstall.sh at this commit:
commit a0e8018fd72ed8c0c9227bfe583f70eece7af744 (HEAD -> main, origin/main, origin/HEAD)
Author: Evelina <10428420+ekmb@users.noreply.github.com>
Date:   Mon Oct 11 15:56:25 2021 -0700

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by VahidooX** [comment]
Thanks for reporting the bug. Other sizes of Conformer-transducer looks to be working. There should have been a mistake when we uploaded the large model. Let me check it up and fix it. It may take some days to upload the fixed model. Would update you here.

**Comment by VahidooX** [comment]
Would you please try the large model to make sure it is fixed?
I would fix the small one in the meantime.
