### ISSUE TITLE
 Fails when load 'ecapa_tdnn' model configs

### ISSUE THREAD

**Issue by An-BN** [NVIDIA/NeMo#3063]
Hi everyone, i am trying train ecapa_tdnn model but can't load model with [ecapa_tdnn.yaml config](https://github.com/NVIDIA/NeMo/blob/main/examples/speaker_tasks/recognition/conf/ecapa_tdnn.yaml)

This is error log:
```
Traceback (most recent call last):
  File "speaker_veri_training.py", line 61, in <module>
    main()
  File "speaker_veri_training.py", line 57, in main
    model = nemo_asr.models.ExtractSpeakerEmbeddingsModel(cfg=config.model, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/label_models.py", line 380, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/label_models.py", line 92, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 120, in __init__
    self.setup_training_data(self._cfg.train_ds)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/label_models.py", line 152, in setup_training_data
    self._train_dl = self.__setup_dataloader_from_config(config=train_data_layer_config)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/label_models.py", line 109, in __setup_dataloader_from_config
    augmentor = process_augmentations(config['augmentor'])
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/preprocessing/perturb.py", line 832, in process_augmentations
    augmentation = perturbation_types[augment_name](**augment_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/preprocessing/perturb.py", line 401, in __init__
    self._manifest = collections.ASRAudioText(manifest_path, parser=parsers.make_parser([]), index_by_file_id=True)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/common/parts/preprocessing/collections.py", line 193, in __init__
    for item in manifest.item_iter(manifests_files):
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/common/parts/preprocessing/manifest.py", line 68, in item_iter
    for manifest_file in manifests_files:
TypeError: 'NoneType' object is not iterable
```

The manifest file is true and still working with [SpeakerNet config](https://github.com/NVIDIA/NeMo/blob/main/examples/speaker_tasks/recognition/conf/SpeakerNet_recognition_3x2x512.yaml) but got error when using ecapa_tdnn config.

I am using docker container nemo:1.4 what download from ngc
GPU: DGX

**Comment by alamnasim** [comment]
Hi,

How did you solved this error, I am facing same issue.

here is my config file:

name: "ECAPA_TDNN"



model:



  sample_rate: 16000



  train_ds:

    manifest_filepath: '/home/ubuntu/Nasim/NeMo/examples/speaker_tasks/diarization/manifest_train.json'

    sample_rate: ${model.sample_rate}

    labels: null

    batch_size: 64

    shuffle: True

    time_length: 3

    augmentor:

      noise:

        manifest_path: null

        prob: 0.5

        min_snr_db: 0

        max_snr_db: 15



      speed:

        prob: 0.5

        sr: ${model.sample_rate}

        resample_type: 'kaiser_fast'

        min_speed_rate: 0.95

        max_speed_rate: 1.05



  validation_ds:

    manifest_filepath: '/home/ubuntu/Nasim/NeMo/examples/speaker_tasks/diarization/manifest_validation.json'

    sample_rate: ${model.sample_rate}

    labels: null

    batch_size: 128

    shuffle: False

    time_length: 3



Can you pls tell me what should be the number of class? In my training data number of speakers are 40 and in validation its 10.

So is it num_class: 40?



Thanks in advance.
