### ISSUE TITLE
ImportError: cannot import name 'QConfig' from 'torch.ao.quantization'

### ISSUE THREAD

**Issue by pehonnet** [NVIDIA/NeMo#3122]
**Bug description**

Cannot import `asr` from `nemo.collections`

**Steps/Code to reproduce bug**
```bash
# Fresh install
git clone https://github.com/NVIDIA/NeMo.git
cd NeMo/
conda create -n nemo python=3.8
conda activate nemo
./reinstall.sh 

# Then
python

# in the python terminal:
from nemo.collections import asr as nemo_asr
```

Log:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Projects/NeMo/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/home/user/Projects/NeMo/nemo/collections/asr/losses/__init__.py", line 15, in <module>
    from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
  File "/home/user/Projects/NeMo/nemo/collections/asr/losses/angularloss.py", line 18, in <module>
    from nemo.core.classes import Loss, Typing, typecheck
  File "/home/user/Projects/NeMo/nemo/core/__init__.py", line 16, in <module>
    from nemo.core.classes import *
  File "/home/user/Projects/NeMo/nemo/core/classes/__init__.py", line 16, in <module>
    from nemo.core.classes.common import (
  File "/home/user/Projects/NeMo/nemo/core/classes/common.py", line 32, in <module>
    from nemo.utils import logging
  File "/home/user/Projects/NeMo/nemo/utils/__init__.py", line 22, in <module>
    from nemo.utils.lightning_logger_patch import add_memory_handlers_to_pl_logger
  File "/home/user/Projects/NeMo/nemo/utils/lightning_logger_patch.py", line 18, in <module>
    import pytorch_lightning as pl
  File "/home/user/Tools/miniconda3/envs/nemo/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/user/Tools/miniconda3/envs/nemo/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining
  File "/home/user/Tools/miniconda3/envs/nemo/lib/python3.8/site-packages/pytorch_lightning/callbacks/quantization.py", line 30, in <module>
    from torch.ao.quantization import QConfig
ImportError: cannot import name 'QConfig' from 'torch.ao.quantization' (/home/user/Tools/miniconda3/envs/nemo/lib/python3.8/site-packages/torch/ao/quantization/__init__.py)

```

**Expected behavior**
Expected: being able to import without error

**Environment overview (please complete the following information)**
- installed with `reinstall.sh`

- also tried to reinstall different version of pytorch:
`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
and getting exactly the same error
 
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS: ubuntu 20.04
- pytorch version (default from reinstall.sh) 1.10.0+cu102
- python version: 3.8.12
- nvidia driver: 470.82.00

**Comment by pehonnet** [comment]
Seems to be resolved after updating today. I'll close this issue.
now on commit `aaacc4b08`
