### ISSUE TITLE
Correct way to use CyclicLR with config

### ISSUE THREAD

**Issue by zzomg** [NVIDIA/NeMo#3175]
Hi 👋 I'm trying to set up training with CyclicLR using config file and it fails every time. NeMo uses CyclicLR from PyTorch, so I guess it should support all the keyword arguments from `torch.optim.lr_scheduler.CyclicLR`, but I'm not sure how to pass them using config file. Here is the config I'm using:

```
  optim:
    name: adamw
    lr: ${model.lr}
    # optimizer arguments
    betas: [0.9, 0.98]
    weight_decay: 1e-3

   sched:
        name: CyclicLR
        iters_per_batch: null # computed at runtime; mandatory to have
        max_steps: null # computed at runtime or explicitly set here; mandatory to have
        
        # pytorch lightning args <mandatory>
        monitor: val_loss
        reduce_on_plateau: false
        
        base_lr: ${model.lr}
        max_lr: 1.0
        step_size_up: 5000
        step_size_down: 5000
        cycle_momentum: false
```

As far as I understand from docstring to this method `prepare_lr_scheduler` https://github.com/NVIDIA/NeMo/blob/a48be1f2679198905f650e05cc93104a9dda4ec6/nemo/core/optim/lr_scheduler.py#L524 
`iters_per_batch` and `max_steps` are mandatory, but every time I pass them I get this error:
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "base_model.py", line 47, in main
    trainer.fit(asr_model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 873, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu.py", line 42, in setup
    return super().setup(trainer, model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 88, in setup
    self.setup_optimizers(trainer)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 330, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 223, in init_optimizers
    return trainer.init_optimizers(model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 558, in configure_optimizers
    self.setup_optimization()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 549, in setup_optimization
    self._scheduler = prepare_lr_scheduler(
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/nemo/core/optim/lr_scheduler.py", line 619, in prepare_lr_scheduler
    schedule = scheduler_cls(optimizer, **scheduler_args)
TypeError: __init__() got an unexpected keyword argument 'max_steps'
```

**But** even if I remove these keywords, I still get this error.
So, can anyone please help me to figure out what is wrong with my config file and/or provide link to documentation on how to correctly set PyTorch lr schedulers in NeMo config files?
Thanks.

Full config file and run script can be found here: https://github.com/zzomg/conformer_clr

Environment:

Packages:
- pyTorch_debug: True
- pyTorch_version: 1.9.0.
- pytorch-lightning: 1.4.5
- NeMo ver. 1.3.0

**Comment by titu1994** [comment]
Max steps is computed and passed to every single scheduler. Of this scheduler doesn't require max_steps then it will fail as above. I'll look into it, but the solution will probably not be in the coming release but the next one

**Comment by zzomg** [comment]
@titu1994 So right now there is no way to use CyclicLR via config file, did I get it right? Only if I define it as a custom scheduler in `configure_optimizers`?

**Comment by titu1994** [comment]
Yes, you can override configire_optimizer to make it work, or you could subclass CyclicLR to take a dummy value for max_steps and register that into Nemo. Either would work as a work around

**Comment by zzomg** [comment]
@titu1994 Okay, thank you, I'll try that

**Comment by zzomg** [comment]
@titu1994 Hi. I'm trying to override `configire_optimizer` now, but it seem to set optimizer to None and doesn't work. It fails with this error:
```
Traceback (most recent call last):
  File "base_model.py", line 86, in main
    trainer.fit(asr_model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 395, in _optimizer_step
    model_ref.optimizer_step(
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1618, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 209, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 129, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 292, in optimizer_step
    make_optimizer_step = self.precision_plugin.pre_optimizer_step(
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 59, in pre_optimizer_step
    result = lambda_closure()
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 536, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 384, in training_step
    return self.model(*args, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/nemo/utils/model_utils.py", line 339, in wrap_training_step
    output_dict = wrapped(*args, **kwargs)
  File "/home/dev/anaconda3/envs/kenv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 565, in training_step
    tensorboard_logs = {'train_loss': loss_value, 'learning_rate': self._optimizer.param_groups[0]['lr']}
AttributeError: 'NoneType' object has no attribute 'param_groups'
```

This is the script I'm using:
```
import torch
import nemo
import nemo.collections.asr as nemo_asr
import pytorch_lightning as pl
from nemo.utils.exp_manager import exp_manager
from nemo.core.config import hydra_runner

import os
from omegaconf import OmegaConf


class ModelOneCycleLR(nemo_asr.models.EncDecCTCModel):
    def __init__(self, cfg, trainer=None, max_lr=1.0):
        super().__init__(cfg=cfg, trainer=trainer)
        self.save_hyperparameters()  # creates `self.hparams` from kwargs
    
    def configure_optimizers(self):
        self.optimizer = torch.optim.AdamW(self.parameters(), 
                                           lr=0.01,
                                           betas=(0.9, 0.98),
                                           weight_decay=1e-3,)

        self.scheduler = torch.optim.lr_scheduler.CyclicLR(
            self.optimizer, 
            base_lr=0.01, 
            max_lr=1.0,
            step_size_up=5000, 
            step_size_down=5000, 
            cycle_momentum=False, 
            verbose=True)
    
        sched = {
            'scheduler': self.scheduler,
            'interval': 'step',
        }
        
        return [self.optimizer], [sched]


@hydra_runner(config_path="/nas/vkriger/configs", config_name="conformer_ctc_char-ru-clr")
def main(cfg):
    cfg.model.train_ds.manifest_filepath = '/nas/DataProtocolAI/Youtube_train.json'
    cfg.model.validation_ds.manifest_filepath = '/nas/DataProtocolAI/Youtube_val.json'
    cfg.trainer.gpus = 1
    cfg.trainer.auto_lr_find = False

    print("Trainer config - \n")
    print(OmegaConf.to_yaml(cfg.trainer))
    
    trainer = pl.Trainer(**cfg.trainer)
    exp_manager(trainer, cfg.get("exp_manager", None))

    ckpt_path = '/nas/vkriger/nemo_experiments/Conformer-CTC-Char/2021-10-11_13-49-24/checkpoints/Conformer-CTC-Char--val_wer=0.31-epoch=2-last.ckpt'
    ckpt = torch.load(ckpt_path)

    asr_model = ModelOneCycleLR(cfg=cfg.model, trainer=trainer)
    asr_model.load_state_dict(ckpt['state_dict'], strict=False)
    trainer.fit(asr_model)

if __name__ == '__main__':
    main()
    
```

I tried adding `self.setup_optimization()` in `configure_optimizers` before defining the optimizer but it sends me back to the initial error `TypeError: __init__() got an unexpected keyword argument 'max_steps'`.
Can you help, please?

**Comment by titu1994** [comment]
Hmm, it should be self._optimizer inside of the configure_optimizer. Could you try with that ?

**Comment by zzomg** [comment]
@titu1994 That seemed to work, thank you!
