### ISSUE TITLE
(nemo_asr) Unable to get inference on wav files converted from mp3

### ISSUE THREAD

**Issue by Ivanlxw** [NVIDIA/NeMo#318]
I tried running inference on `.wav` files converted from `.mp3` files using `ffmpeg` and this is the error I get.
```
Traceback (most recent call last):
  File "eval.py", line 243, in <module>
    evaluate = GetAsrEval()
  File "eval.py", line 203, in __init__
    checkpoint_dir=('./qn15x5')
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 663, in infer
    modules_to_restore=modules_to_restore,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 1423, in infer
    offload_to_cpu=offload_to_cpu,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 740, in _infer
    use_cache=use_cache,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 429, in __nm_graph_forward_pass
    new_tensors = pmodule(force_pt=True, **call_set)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/backends/pytorch/nm.py", line 130, in __call__
    return self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/collections/asr/audio_preprocessing.py", line 81, in forward
    processed_signal = self.get_features(input_signal, length)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/collections/asr/audio_preprocessing.py", line 390, in get_features
    return self.featurizer(input_signal, length)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/collections/asr/parts/features.py", line 253, in forward
    x = self.stft(x)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nemo/collections/asr/parts/features.py", line 161, in forward
    return super(STFTPatch, self).transform(input_data)[0]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch_stft/stft.py", line 79, in transform
    mode='reflect')
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 2879, in pad
    return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (256, 256) at dimension 3 of input 4
```

This is the script I used to test mp3 files.
```python
"""
This scripts does the full evaluation without all the trouble from runnigng jupyter notebooks
- create manifest
- define model
- inference

Args:
    filepath_manifest : where to get the .wav file from

Run this script as such in command line: python eval.py filepath_manifest
"""
import sys
import glob
import os
import wget
import tarfile
import subprocess

import nemo
import nemo.collections.asr as nemo_asr
from nemo.core import DeviceType
from nemo.collections.asr.helpers import monitor_asr_train_progress,process_evaluation_batch, process_evaluation_epoch
from functools import partial
from nemo.collections.asr.helpers import word_error_rate, \
    post_process_predictions, post_process_transcripts

import torch
import json

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Creating manifest
def build_test_manifest_(filelocation :str, extension: str, manifest_path: str) -> str:
    '''
    Build manifest for files in ./test_data
    Arguments:
        filepattern: for glob.glob
    '''

    wav_files = glob.glob(filelocation+".wav")
    print(wav_files)
    for file in wav_files:
        with open(manifest_path, 'a') as fout:
            duration = librosa.core.get_duration(filename=file)
            
            metadata = {
                "audio_filepath": file,
                "duration" : duration,
                "text": ''
            }
            json.dump(metadata, fout)
            fout.write('\n')
            
    print("test manifest created at {}".format(manifest_path))
    return manifest_path
            
class GetAsrEval:
    def __init__(self):

        # --- Loading Config --- #
        from ruamel.yaml import YAML

        # Parse config and pass to model building function
        config_path = './qn15x5/quartznet15x5.yaml'     # quartznet 15x5.
        yaml = YAML(typ='safe')
        with open(config_path) as f:
            params = yaml.load(f)
            print("******\nLoaded config file.\n******")

        labels = params['labels']  # Vocab of tokens
        sample_rate = params['sample_rate']

        # Create NeuralModuleFactory, which will overc the neural modules
        nf = nemo.core.NeuralModuleFactory(log_dir='./qn15x5_checkpoints', 
                                        placement=(DeviceType.GPU if torch.cuda.is_available() else DeviceType.CPU)
                                        )
        logger = nf.logger

        train_manifest = './train_manifest.json'
        data_layer_train = nemo_asr.AudioToTextDataLayer(
            manifest_filepath=train_manifest,
            sample_rate=sample_rate,
            labels=labels,
            batch_size=32,
            **params['AudioToTextDataLayer']['train'])  # Training datalayer

        data_layer_test = nemo_asr.AudioToTextDataLayer(
            manifest_filepath=test_manifest,
            sample_rate=sample_rate,
            labels=labels,
            batch_size=32,
            **params['AudioToTextDataLayer']['eval'])   # Eval datalayer

        data_preprocessor = nemo_asr.AudioToMelSpectrogramPreprocessor(
            sample_rate=sample_rate,
            **params['AudioToMelSpectrogramPreprocessor'])

        encoder = nemo_asr.JasperEncoder(feat_in=64, **params['JasperEncoder'])
        decoder = nemo_asr.JasperDecoderForCTC(
            feat_in = params['JasperEncoder']['jasper'][-1]['filters'],
            num_classes = len(labels)
        )

        ctc_loss = nemo_asr.CTCLossNM(num_classes=len(labels))
        greedy_decoder = nemo_asr.GreedyCTCDecoder()

        # --- Assemble Training DAG --- #
        spectrogram_aug = nemo_asr.SpectrogramAugmentation(
            rect_masks=5, rect_time=120, rect_freq=50)

        audio_signal, audio_signal_len, transcript, transcript_len = data_layer_train()

        processed_signal, processed_signal_len = data_preprocessor(
            input_signal=audio_signal,
            length=audio_signal_len)

        # encoded, encoded_len = encoder(
        #     audio_signal=processed_signal,
        #     length=processed_signal_len)

        processed_signal_aug = spectrogram_aug(input_spec=processed_signal)

        encoded, encoded_len = encoder(
            audio_signal=processed_signal_aug,  # Change this argument too
            length=processed_signal_len)

        log_probs = decoder(encoder_output=encoded)
        preds = greedy_decoder(log_probs=log_probs)  # Training predictions
        loss = ctc_loss(
            log_probs=log_probs,
            targets=transcript,
            input_length=encoded_len,
            target_length=transcript_len)

        # --- Assemble Validation DAG --- #
        (audio_signal_test, audio_len_test,
        transcript_test, transcript_len_test) = data_layer_test()

        processed_signal_test, processed_len_test = data_preprocessor(
            input_signal=audio_signal_test,
            length=audio_len_test)

        encoded_test, encoded_len_test = encoder(
            audio_signal=processed_signal_test,
            length=processed_len_test)

        log_probs_test = decoder(encoder_output=encoded_test)
        preds_test = greedy_decoder(log_probs=log_probs_test)  # Test predictions
        loss_test = ctc_loss(
            log_probs=log_probs_test,
            targets=transcript_test,
            input_length=encoded_len_test,
            target_length=transcript_len_test)


        # --- Create Callbacks --- #

        # We use these imports to pass to callbacks more complex functions to perform.

        train_callback = nemo.core.SimpleLossLoggerCallback(
            # Notice that we pass in loss, predictions, and the transcript info.
            # Of course we would like to see our training loss, but we need the
            # other arguments to calculate the WER.
            tensors=[loss, preds, transcript, transcript_len],
            # The print_func defines what gets printed.
            print_func=partial(
                monitor_asr_train_progress,
                labels=labels,
                logger=logger)
            )

        # We can create as many evaluation DAGs and callbacks as we want,
        # which is useful in the case of having more than one evaluation dataset.
        # In this case, we only have one.
        eval_callback = nemo.core.EvaluatorCallback(
            eval_tensors=[loss_test, preds_test, transcript_test, transcript_len_test],
            user_iter_callback=partial(
                process_evaluation_batch, labels=labels),
            user_epochs_done_callback=partial(
                process_evaluation_epoch, logger=logger),
            eval_step=300  # How often we evaluate the model on the test set
            )

        checkpoint_saver_callback = nemo.core.CheckpointCallback(
            folder='./qn15x5',
            step_freq=1000  # How often checkpoints are saved
            )

        if not os.path.exists('./qn15x5_checkpoints'):
            os.makedirs('./qn15x5_checkpoints')

        # --- Inference Only --- #

        # We've already built the inference DAG above, so all we need is to call infer().
        evaluated_tensors = nf.infer(
            # These are the tensors we want to get from the model.
            tensors=[loss_test, preds_test, transcript_test, transcript_len_test],
            # checkpoint_dir specifies where the model params are loaded from.
            checkpoint_dir=('./qn15x5')
            )

        # Process the results to get WER
        self.greedy_hypotheses = post_process_predictions(
            evaluated_tensors[1], labels)

        self.references = post_process_transcripts(
            evaluated_tensors[2], evaluated_tensors[3], labels)

        print("DONE.")

    def _get_info(self, mode='hypo', ind=None):
        if mode == 'hypo':
            if ind == None:
                print(self.greedy_hypotheses)
            else:
                print(self.greedy_hypotheses[:ind])
        elif mode == 'ref':
            if ind == None:
                print(self.references)
            else:
                print(self.references[:ind])
        else:
            return

    def _get_wer(self,):
        wer = word_error_rate(hypotheses=self.greedy_hypotheses, references=self.references)
        print("*** Greedy WER: {:.2f} ***".format(wer * 100))


manifest_filename = './test_manifest.json'
try:
    subprocess.run(['rm', manifest_filename])
except:
    pass
# test_manifest = build_test_manifest_("./test_data/", "flac", './test1_manifest.json')
test_manifest = build_test_manifest_(sys.argv[1], "flac", manifest_filename) 

evaluate = GetAsrEval()
evaluate._get_info()
```

Basically I've gotten the file paths of the `.mp3` files, converted them into `.wav` using `ffmpeg`, built a test manifest and then run the model on it.

I used the following command on the command line to convert `.mp3` to `.wav` file
`ffmpeg -i c330248c-21fe-4c32-9bdb-624d3c0f7319.mp3 -ss 10 -t 7 test-1.wav`

Anyone who has faced this error and solved it? Or knows why this problem occurs? Been stuck here for awhile and would really appreciate for any insight!!

**Comment by vsl9** [comment]
@Ivanlxw can you please check that your wav files are single channel (mono) and sample rate is 16 kHz?
If original mp3 files are stereo and sample rate isn't 16kHz then they can be converted by adding `-ac 1` and `-ar 16000` options to ffmpeg:
```
ffmpeg -i c330248c-21fe-4c32-9bdb-624d3c0f7319.mp3 -ss 10 -t 7 -ac 1 -af aresample=resampler=soxr -ar 16000 test-1.wav
```

**Comment by Ivanlxw** [comment]
Thanks @vsl9 it works!!
