### ISSUE TITLE
Error while trying to use the NeMo's pretrained model based on TalkNet in r1.2.0 branch 

### ISSUE THREAD

**Issue by marzieh-razavi** [NVIDIA/NeMo#3206]
**Describe the bug**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by marzieh-razavi** [comment]
Hello, thanks for this great repo. I have been trying to use the pre-trained model based on TalkNet as described in https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/TalkNet_Training.ipynb, and I have already reverted to branch  r1.2.0. But I am getting the following error when trying to load the pre-trained model:

model = TalkNetSpectModel.from_pretrained(pretrained_model)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 679, in from_pretrained
    instance = class_.restore_from(
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/modelPT.py", line 481, in restore_from
    return cls._default_restore_from(restore_path, override_config_path, map_location, strict, return_config)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/modelPT.py", line 434, in _default_restore_from
    instance = cls.from_config_dict(config=conf)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 472, in from_config_dict
    instance = cls(cfg=config)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/tts/models/talknet.py", line 256, in __init__
    self.model = instantiate(cfg.model)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 166, in _validate_get
    self._format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'model' is not in struct
    full_key: model
    object_type=dict

I would be really grateful if you could help me with this problem.

**Comment by titu1994** [comment]
You would need to use the r1.5.0 branch with the Pytorch 1.10. We wont be able to support all past versions of NeMo. Also please provide environment information.

**Comment by Oktai15** [comment]
@stasbel

**Comment by Oktai15** [comment]
@marzieh-razavi this PR (https://github.com/NVIDIA/NeMo/pull/3092/files) will fix the problem in the latest version of NeMo

**Comment by marzieh-razavi** [comment]
@Oktai15 Thank you very much for your help, that fixed the problem.

**Comment by KnurpsBram** [comment]
Could you give some more instructions on how to set up the correct versions to run the pretrained TalkNet model? It's not happening for me. I ran the following:
```
conda create --name nemo_r1.5.0 python=3.9
conda activate nemo_r1.5.0
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.5.0#egg=nemo_toolkit[all]
```
The following python script fails for me:
```
import torch
print(torch.__version__)

import nemo
print(nemo.__version__)

from nemo.collections.tts.models import TalkNetSpectModel
from nemo.collections.tts.models.base import SpectrogramGenerator

# Let's see what pretrained models are available
print(TalkNetSpectModel.list_available_models())

# We can load the pre-trained model as follows
pretrained_model = "tts_en_talknet"
model = TalkNetSpectModel.from_pretrained(pretrained_model)
```
This is the output I see:
```
1.10.0
1.5.0b1
[NeMo W 2021-11-18 16:24:53 optimizers:50] Apex was not found. Using the lamb or fused_adam optimizer will error out.
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

None
Traceback (most recent call last):
  File "/home/bram/Documents/2021-11-17_nemo_talknet_s2t2s_experiment/2021-11-17_nemo_talknet_minimal_bug_reproduction_code.py", line 20, in <module>
    model = TalkNetSpectModel.from_pretrained(pretrained_model)
  File "/home/bram/miniconda3/envs/nemo_r1.5.0/lib/python3.9/site-packages/nemo/core/classes/common.py", line 716, in from_pretrained
    raise FileNotFoundError(
FileNotFoundError: Model tts_en_talknet was not found. Check cls.list_available_models() for the list of all available models.

```

**Comment by KnurpsBram** [comment]
I've opened a new issue #3212. Let's discuss there.

**Comment by marzieh-razavi** [comment]
@KnurpsBram I actually used the r1.2.0 version but modified the talknet.py code as suggested in this PR (https://github.com/NVIDIA/NeMo/pull/3092/files)

**Comment by KnurpsBram** [comment]
How do I find the `talknet.py` file whose contents need to change? That should be somewhere on my local machine, right?

**Comment by KnurpsBram** [comment]
Found it! It's be `miniconda3/envs/MY_ENV/lib/python3.9/site-packages/nemo/collections/tts/models/talknet.pt`. Swap `MY_ENV` over for the name of your environment. 

I can now load and run the pretrained TalkNet2. 

Thanks! You're a champ!
