### ISSUE TITLE
Error while trying to use the NeMo's pretrained model based on TalkNet in r1.5.0 branch

### ISSUE THREAD

**Issue by KnurpsBram** [NVIDIA/NeMo#3212]
**Describe the bug**

The pretrained TalkNet2 model does not appear to be available in 1.5.0. The tutorial notebook https://github.com/NVIDIA/NeMo/blob/stable/tutorials/tts/TalkNet_Training.ipynb states that r1.4.0 is broken and r1.2.0 should be used. I run into the same issue as #3206, where it appears fixed by moving to version 1.5.0, but the pretrained model still does not appear in the list of available models for me.

**Steps/Code to reproduce bug**

Create a fresh environment:
```
conda create --name nemo_r1.5.0 python=3.9
conda activate nemo_r1.5.0
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.5.0#egg=nemo_toolkit[all]
```
Run the following python script:
```
import torch
print(torch.__version__)

import nemo
print(nemo.__version__)

from nemo.collections.tts.models import TalkNetSpectModel
from nemo.collections.tts.models.base import SpectrogramGenerator

# Let's see what pretrained models are available
print(TalkNetSpectModel.list_available_models())

# We can load the pre-trained model as follows
pretrained_model = "tts_en_talknet"
model = TalkNetSpectModel.from_pretrained(pretrained_model)
```
You'll get an error similar to the following:
```
1.10.0
1.5.0b1
[NeMo W 2021-11-18 16:24:53 optimizers:50] Apex was not found. Using the lamb or fused_adam optimizer will error out.
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

None
Traceback (most recent call last):
  File "/home/bram/Documents/2021-11-17_nemo_talknet_s2t2s_experiment/2021-11-17_nemo_talknet_minimal_bug_reproduction_code.py", line 20, in <module>
    model = TalkNetSpectModel.from_pretrained(pretrained_model)
  File "/home/bram/miniconda3/envs/nemo_r1.5.0/lib/python3.9/site-packages/nemo/core/classes/common.py", line 716, in from_pretrained
    raise FileNotFoundError(
FileNotFoundError: Model tts_en_talknet was not found. Check cls.list_available_models() for the list of all available models.
```

**Expected behavior**

The function `print(TalkNetSpectModel.list_available_models())` should return a list with at least `tts_en_talknet` in it. `TalkNetSpectModel.from_pretrained(my_pretrained_model)` should load a pretrained model.

**Environment overview (please complete the following information)**

I hope the following steps to reproduce my environment will suffice:
```
conda create --name nemo_r1.5.0 python=3.9
conda activate nemo_r1.5.0
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.5.0#egg=nemo_toolkit[all]
```

**Environment details**

- OS version; Pop!-os 20.10
- PyTorch version; 1.10
- Python version; 3.9

Any help will be greatly appreciated!

**Comment by KnurpsBram** [comment]
Anyone that encounters the same problem and is looking for a workaround should take a look at #3206. The workaround involves reverting to version `r1.2.0`, then going into the source code of the library on your local machine, and swapping over the source code of `talknet.py` to the code suggested in PR #3092 https://github.com/NVIDIA/NeMo/pull/3092/files. 

There's this side effect of version `1.2.0` that doesn't agree with my gpu, so I have to load every model with `map_location=torch.device("cpu")`, but hey, it runs.

I'm assuming that PR #3092 will take care of this bug, in which case it's a matter of waiting until it gets merged to main, after which we can use pretrained TalkNet2 in `1.5.0`.

**Comment by KnurpsBram** [comment]
Merging #3206 fixed it!

You'll have to install nemo like this: 
```python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]```

which as of today installs version `1.6.0rc0`, which works for TalkNet. For my case it works on gpu as well.

I'm closing this issue
