### ISSUE TITLE
Running examples `enc_dec_nmt.py` script and getting a TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by jpilaul** [NVIDIA/NeMo#3326]
**Describe the bug**

I am running `enc_dec_nmt.py` as is from https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/enc_dec_nmt.py

Here's the error:

```
Traceback (most recent call last):
  File "/home/jpilault/projects/nemo_examples/enc_dec_nmt.py", line 124, in main
    mt_model = MTEncDecModel(cfg.model, trainer=trainer)
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/site-packages/nemo/collections/nlp/models/machine_translation/mt_enc_dec_model.py", line 84, in __init__
    self.setup_enc_dec_tokenizers(
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/site-packages/nemo/collections/nlp/models/machine_translation/mt_enc_dec_model.py", line 442, in setup_enc_dec_tokenizers
    self.encoder_tokenizer = get_nmt_tokenizer(
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/site-packages/nemo/collections/nlp/modules/common/tokenizer_utils.py", line 164, in get_nmt_tokenizer
    return YouTokenToMeTokenizer(model_path=tokenizer_model, bpe_dropout=bpe_dropout, r2l=r2l)
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/site-packages/nemo/collections/common/tokenizers/youtokentome_tokenizer.py", line 26, in __init__
    model_path = Path(model_path).expanduser()
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/jpilault/anaconda3/envs/myenv/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Steps/Code to reproduce bug**

Run the code

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

It should not give an error.

**Environment overview (please complete the following information)**

used pip install

**Environment details**

- OS version:  Ubuntu 20.04.2 LTS
- PyTorch version: 1.10.0+cu113
- Python version: 3.8

**Additional context**

Example: GPU model

**Comment by jpilaul** [comment]
It seems `MTEncDecModel` requires a `MTEncDecModelConfig` object as the `cfg` argument but in `enc_dec_nmt.py` line 84, the config being passed is a `DistConfig`...

**Comment by Vlados09** [comment]
This is because your path for the tokenizer is empty. It should get auto-populated after this line:
```python
 MTDataPreproc(cfg=cfg.model, trainer=trainer)
```
But its not running because you did not specify `cfg.model.preproc_out_dir`. 
If you set that your issue should get resolved

**Comment by okuchaiev** [comment]
thanks @Vlados09 ! @jpilaul  please re-open if the issue persists
