### ISSUE TITLE
Export punctuation and capitalization models for offline use

### ISSUE THREAD

**Issue by agupta54** [NVIDIA/NeMo#3349]
I want to use punctuation and capitalization model by using restore_from function and give my own model path. Even when I am providing the model path myself, it is downloading the model and tokenizer in the background. Is there a way to get this working without any downloads happening?

**Comment by PeganovAnton** [comment]
Hi @agupta54 ! Could you please share your config and a bash command you use to start training?

**Comment by agupta54** [comment]
Hi @PeganovAnton :) I am not training my own model. I want to use the English model provided as a part of the library. I downloaded the checkpoint for English and restoring it in my script - 
`PunctuationCapitalizationModel.restore_from(self.model_path)`
I was able to save the config from this checkpoint. 
`nemo_path: /mnt/sdb/ebakhturina/nemo_ckpts/punctuation/2021.nemo/Punctuation_Capitalization_with_BERT_base_uncased.nemo
punct_label_ids:
  O: 0
  ',': 1
  .: 2
  '?': 3
capit_label_ids:
  O: 0
  U: 1
class_labels:
  punct_labels_file: punct_label_ids.csv
  capit_labels_file: capit_label_ids.csv
dataset:
  data_dir: punct_dataset_complete
  max_seq_length: 128
  pad_label: O
  ignore_extra_tokens: false
  ignore_start_end: false
  use_cache: true
  num_workers: 2
  pin_memory: false
  drop_last: false
train_ds:
  text_file: text_train.txt
  labels_file: labels_train.txt
  shuffle: true
  num_samples: -1
  batch_size: 64
validation_ds:
  ds_item: null
  text_file: text_dev.txt
  labels_file: labels_dev.txt
  shuffle: false
  num_samples: -1
  batch_size: 64
test_ds:
  ds_item: null
  text_file: text_dev.txt
  labels_file: labels_dev.txt
  shuffle: false
  num_samples: -1
  batch_size: 64
tokenizer:
  tokenizer_name: bert-base-uncased
  vocab_file: tokenizer.vocab_file
  tokenizer_model: null
  special_tokens: null
language_model:
  pretrained_model_name: bert-base-uncased
  lm_checkpoint: null
  config_file: bert-base-uncased_encoder_config.json
  config: null
punct_head:
  punct_num_fc_layers: 1
  fc_dropout: 0.1
  activation: relu
  use_transformer_init: true
capit_head:
  capit_num_fc_layers: 1
  fc_dropout: 0.1
  activation: relu
  use_transformer_init: true
optim:
  name: adam
  lr: 0.0001
  weight_decay: 0.0
  sched:
    name: WarmupAnnealing
    warmup_steps: null
    warmup_ratio: 0.1
    last_epoch: -1
    monitor: val_loss
    reduce_on_plateau: false
target: nemo.collections.nlp.models.token_classification.punctuation_capitalization_model.PunctuationCapitalizationModel`

**Comment by PeganovAnton** [comment]
@agupta54 Could you please upload the checkpoint to `lab@10.110.42.118:/home/lab/checkpoints`?

**Comment by agupta54** [comment]
My connection is getting timed out when I try to upload. You can do: 
`wget https://storage.googleapis.com/vakyaansh-open-models/punctuation_models/en/punctuation_en_bert.nemo`

I am using Nemo version 1.0.2

**Comment by PeganovAnton** [comment]
@agupta54 , when I changed HuggingFace cache location, I got this:
```
(issue3349) apeganov@aiapps-061821:~/NeMo/examples/nlp/token_classification$ export TRANSFORMERS_CACHE=debug_transformers_cache
(issue3349) apeganov@aiapps-061821:~/NeMo/examples/nlp/token_classification$ python                                                                                                                    Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nemo.collections.nlp.models.token_classification import PunctuationCapitalizationModel                                                                                                        [NeMo W 2021-12-16 07:48:09 optimizers:46] Apex was not found. Using the lamb optimizer will error out.                                                                                                >>> model = PunctuationCapitalizationModel.restore_from('/home/apeganov/checkpoints/issue_checkpoints/punctuation_en_bert.nemo')                                                                       Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 36.8kB/s]Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 409kB/s]Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226k/226k [00:00<00:00, 272kB/s]Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 455k/455k [00:01<00:00, 328kB/s]Using bos_token, but it is not set yet.                                                                                                                                                                Using eos_token, but it is not set yet.                                                                                                                                                                [NeMo W 2021-12-16 07:48:24 nemo_logging:349] /home/apeganov/anaconda3/envs/issue3349/lib/python3.8/site-packages/torch/cuda/__init__.py:120: UserWarning:                                                     Found GPU%d %s which is of cuda capability %d.%d.                                                                                                                                                      PyTorch no longer supports this GPU because it is too old.                                                                                                                                             The minimum cuda capability supported by this library is %d.%d.                                                                                                                                                                                                                                                                                                                                             warnings.warn(old_gpu_warn.format(d, name, major, minor, min_arch // 10, min_arch % 10))                                                                                                                                                                                                                                                                                                                [NeMo W 2021-12-16 07:48:24 nemo_logging:349] /home/apeganov/anaconda3/envs/issue3349/lib/python3.8/site-packages/torch/cuda/__init__.py:143: UserWarning:                                                 NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.                                                                                                   The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
    If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/                                                                                                                                                                                                                                                                             warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

[NeMo W 2021-12-16 07:48:24 modelPT:137] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    text_file: text_train.txt
    labels_file: labels_train.txt
    shuffle: true
    num_samples: -1
    batch_size: 64

[NeMo W 2021-12-16 07:48:24 modelPT:144] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    ds_item: null
    text_file: text_dev.txt
    labels_file: labels_dev.txt
    shuffle: false
    num_samples: -1
    batch_size: 64

[NeMo W 2021-12-16 07:48:24 modelPT:151] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    ds_item: null
    text_file: text_dev.txt
    labels_file: labels_dev.txt
    shuffle: false
    num_samples: -1
    batch_size: 64

[NeMo W 2021-12-16 07:48:24 modelPT:1198] World size can only be set by PyTorch Lightning Trainer.
[NeMo W 2021-12-16 07:48:24 modelPT:197] You tried to register an artifact under config key=tokenizer.vocab_file but an artifact forit has already been registered.
[NeMo W 2021-12-16 07:48:24 nemo_logging:349] /home/apeganov/anaconda3/envs/issue3349/lib/python3.8/site-packages/nemo/core/classes/modelPT.py:243: UserWarning: update_node() is deprecated, use OmegaConf.update(). (Since 2.0)
      self.cfg.update_node(config_path, return_path)
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 420M/420M [00:03<00:00, 117MB/s]Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertEncoder: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertEncoder from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertEncoder from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[NeMo I 2021-12-16 07:48:32 modelPT:434] Model PunctuationCapitalizationModel was successfully restored from /home/apeganov/checkpoints/issue_checkpoints/punctuation_en_bert.nemo.
 ```
HuggingFace configs, tokenizer, and model for `bert-base-uncased` are downloaded. In my case, when `restore_from()` is called the second time, then no downloading is performed and cache is used instead. Would a preliminary call of `restore_from()` suffice?

**Comment by PeganovAnton** [comment]
I suppose, we will not incorporate HuggingFace tokenizers into checkpoints. Restoring a NeMo model model without initializing it first is not planned, as far as I know. @okuchaiev , what do you think?

**Comment by agupta54** [comment]
@PeganovAnton thanks for looking into this. I was looking for something in which nothing is downloaded even once if provided the appropriate paths. Like for HuggingFace instead of loading tokenizer and model by pointing it to `bert-base-uncased` if I download all the vocab, tokenizer and model files and point to the directory, then nothing is downloaded even once.

**Comment by PeganovAnton** [comment]
@agupta54 I got your question. As work around, you could use `TRANSFORMERS_CACHE` environment variable:
```
export TRANSFORMERS_CACHE=bert_base_uncased_huggingface_files
python download_bert_base_uncased_files.py
```
`download_bert_base_uncased_files.py`:
```python
from transformers import AutoTokenizer, AutoModelForMaskedLM
  
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModelForMaskedLM.from_pretrained("bert-base-uncased")
```
Now all required files should be in `bert_base_uncased_huggingface_files` directory. Set
```
export TRANSFORMERS_CACHE=bert_base_uncased_huggingface_files
```
before running your script with restoring and no downloading will be performed.

**Comment by agupta54** [comment]
@PeganovAnton I tried it out. When set the 'TRANSFORMERS_CACHE` variable and run the python script given by you three things are downloaded which used to get downloaded when I was restoring the checkpoint.  
```
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 242kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:03<00:00, 59.0kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:03<00:00, 131kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 440M/440M [00:39<00:00, 11.3MB/s]
```
However, when I am restoring punctuation model after specifying the cache variable, it is still downloading one thing. 
```
>>> model = PunctuationCapitalizationModel.restore_from('punctuation_en_bert.nemo')
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 13.7kB/s]
Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.
```
Seems to be a small file but cannot figure out what it is since tokenizers and models are already set.

**Comment by agupta54** [comment]
When I turned off internet and tried to restore checkpoint after specifying transformer cache this is the error I get if it helps: 
```
>>> model = PunctuationCapitalizationModel.restore_from('punctuation_en_bert.nemo')
Traceback (most recent call last):
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1371cef710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1371cef710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/common/tokenizers/huggingface/auto_tokenizer.py", line 105, in __init__
    pretrained_model_name_or_path=pretrained_model_name, vocab_file=vocab_file, use_fast=False
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py", line 488, in from_pretrained
    pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/transformers/models/auto/configuration_auto.py", line 580, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/transformers/configuration_utils.py", line 554, in get_config_dict
    local_files_only=local_files_only,
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/transformers/configuration_utils.py", line 842, in get_configuration_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/transformers/file_utils.py", line 1952, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/huggingface_hub/hf_api.py", line 603, in list_repo_files
    repo_id, revision=revision, token=token, timeout=timeout
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/huggingface_hub/hf_api.py", line 585, in model_info
    r = requests.get(path, headers=headers, timeout=timeout)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1371cef710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/nlp_model.py", line 428, in restore_from
    return super().restore_from(restore_path, override_config_path, map_location, strict, return_config)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/core/classes/modelPT.py", line 479, in restore_from
    return cls._default_restore_from(restore_path, override_config_path, map_location, strict, return_config)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/core/classes/modelPT.py", line 430, in _default_restore_from
    instance = cls.from_config_dict(config=conf)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/core/classes/common.py", line 471, in from_config_dict
    instance = cls(cfg=config)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/token_classification/punctuation_capitalization_model.py", line 57, in __init__
    self.setup_tokenizer(cfg.tokenizer)
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/models/nlp_model.py", line 115, in setup_tokenizer
    tokenizer_model=self.register_artifact(config_path='tokenizer.tokenizer_model', src=cfg.tokenizer_model),
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/nlp/modules/common/tokenizer_utils.py", line 99, in get_tokenizer
    pretrained_model_name=tokenizer_name, vocab_file=vocab_file, **special_tokens_dict, use_fast=use_fast
  File "/home/anirudh/miniconda3/envs/nemo/lib/python3.6/site-packages/nemo/collections/common/tokenizers/huggingface/auto_tokenizer.py", line 112, in __init__
    raise ValueError(f'{pretrained_model_name} is not supported by HuggingFace. {e}')
ValueError: bert-base-uncased is not supported by HuggingFace. HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1371cef710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by PeganovAnton** [comment]
@agupta54 , could you please tell what `transformers` version do you use? MIne is `4.14.1`.

**Comment by agupta54** [comment]
@PeganovAnton I use the same version

**Comment by PeganovAnton** [comment]
@agupta54 The small file is tokenizer config. I got these files in my cache dir
1) `c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79`
```
{
  "do_lower_case": true
}
```
2) `c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79.json`
```
{"url": "https://huggingface.co/bert-base-uncased/resolve/main/tokenizer_config.json", "etag": "\"a661b1a138dac6dc5590367402d100765010ffd6\""}
```
No new line in the end.
3) `c1d7f0a763fb63861cc08553866f1fc3e5a6f4f07621be277452d26d71303b7e.20430bd8e10ef77a7d2977accefe796051e01bc2fc4aa146bc862997a1a15e79.lock`
This file is empty

I could not yet see why in your case tokenizer config is not downloaded.

**Comment by PeganovAnton** [comment]
My downloads look like this.
```
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 20.9kB/s]Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 327kB/s]Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226k/226k [00:01<00:00, 119kB/s]Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 455k/455k [00:01<00:00, 271kB/s]Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 420M/420M [00:03<00:00, 115MB/s]
```
I noticed, that other files sizes in my and your downloads differ.

**Comment by agupta54** [comment]
Somehow when I log into a cloud VM and do it I get all four files! Thanks got looking into @PeganovAnton
