### ISSUE TITLE
ConformerCTC with input problems after ONNX conversion

### ISSUE THREAD

**Issue by DanBmh** [NVIDIA/NeMo#3352]
I'm trying to convert the ConformerCTC (small) to ONNX, which works without problems, but when I'm testing the model with a single audio file I get a shape error:

```
 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_378' 
Status Message: /onnxruntime/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:37 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) size != 0 && (input_shape.Size() % size) == 0 was false. 
The input tensor cannot be reshaped to the requested shape. Input shape:{1,115,176}, requested shape:{16,-1,4,44}

  0%|                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/dsp_nemo/testing_nemo.py", line 186, in <module>
    run_full_test("stt_en_conformer_ctc_small", batch_size=1, print_predictions=True)
  File "/dsp_nemo/testing_nemo.py", line 161, in run_full_test
    ologits = ort_session.run(None, ort_inputs)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
```

The code is the following:
```python3
test_manifest = "/dsp_nemo/data/test.json"

def run_full_test(nemo_model_name, batch_size, print_predictions):

    config = {"batch_size": batch_size, "manifestpath": test_manifest}
    model = nemo_asr.models.EncDecCTCModel.restore_from(
        restore_path="/dsp_nemo/models/" + nemo_model_name + ".nemo"
    )
    ort_session = onnxruntime.InferenceSession(
        "/dsp_nemo/models/" + nemo_model_name + ".onnx"
    )
    temporary_datalayer = setup_transcribe_dataloader(config, model.decoder.vocabulary)
    wer_calc = WER(
        vocabulary=model.decoder.vocabulary,
        batch_dim_index=0,
        use_cer=False,
        ctc_decode=True,
    )

    wer_nums = []
    wer_denoms = []

    for test_batch in tqdm.tqdm(temporary_datalayer):
        processed_signal, processed_signal_len = model.preprocessor(
            input_signal=test_batch[0].to(model.device),
            length=test_batch[1].to(model.device),
        )
        ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(processed_signal)}

        print(processed_signal.shape, processed_signal_len)  # torch.Size([1, 80, 458]) tensor([458], device='cuda:0')
        if "conformer" in nemo_model_name:
            ort_inputs[ort_session.get_inputs()[1].name] = to_numpy(
                processed_signal_len
            )

        ologits = ort_session.run(None, ort_inputs)
        alogits = np.asarray(ologits)
        logits = torch.from_numpy(alogits[0])
        greedy_predictions = logits.argmax(dim=-1, keepdim=False)

        if print_predictions:
            hypotheses = wer_calc.ctc_decoder_predictions_tensor(greedy_predictions)
            print(hypotheses)

        targets = test_batch[2]
        targets_lengths = test_batch[3]
        model._wer.update(greedy_predictions, targets, targets_lengths)
        _, wer_num, wer_denom = model._wer.compute()
        wer_nums.append(wer_num.detach().cpu().numpy())
        wer_denoms.append(wer_denom.detach().cpu().numpy())

    # We need to sum all numerators and denominators first. Then divide.
    print(f"WER = {sum(wer_nums) / sum(wer_denoms)}")

run_full_test("stt_en_conformer_ctc_small", batch_size=1, print_predictions=True)
# run_full_test("QuartzNet5x5LS-En", batch_size=1, print_predictions=True)
```

Running the same code with the QuartzNet model works as expected.

Tested with NeMo docker container (nvcr.io/nvidia/nemo:1.4.0) with onnxruntime (v1.7.2) additionally installed.
Onnx export with:
```
python3 /NeMo/scripts/export.py \
    /dsp_nemo/models/stt_en_conformer_ctc_small.nemo /dsp_nemo/models/stt_en_conformer_ctc_small.onnx
```
<br>

Any ideas on this?

**Comment by borisfom** [comment]
Can you try it with the latest NeMo/PyTorch container? There were some recent internal Pytorch changes that fixed this.

**Comment by DanBmh** [comment]
I get a few more errors with the new container. I can't export the model anymore:
```
 [INFO] Restoring NeMo model from '/dsp_nemo/models/stt_en_conformer_ctc_small.nemo'
 [ERROR] Failed to restore model from NeMo file : /dsp_nemo/models/stt_en_conformer_ctc_small.nemo. Please make sure you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/NeMo/scripts/export.py", line 129, in <module>
    nemo_export(sys.argv[1:])
  File "/NeMo/scripts/export.py", line 97, in nemo_export
    raise e
  File "/NeMo/scripts/export.py", line 90, in nemo_export
    model = ModelPT.restore_from(restore_path=nemo_in)
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 287, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/connectors/save_restore_connector.py", line 142, in restore_from
    instance = calling_cls.from_config_dict(config=conf, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 493, in from_config_dict
    instance = cls(cfg=config, trainer=trainer)
TypeError: Can't instantiate abstract class ModelPT with abstract methods list_available_models, setup_training_data, setup_validation_data
```
<br>

When I tried it with the old onnx model, the error didn't change. I also got a new one: `ImportError: Numba needs NumPy 1.20 or less` which required me to downgrade _numpy_.

<br>

I could solve the above exporting error by reinstalling NeMo `./reinstall.sh`, but the error didn't change when using the newly exported model:
```
[E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_349' Status Message: /onnxruntime/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:37 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,115,176}, requested shape:{16,-1,4,44}

  0%|                                                                                                                           | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/dsp_nemo/testing_nemo.py", line 188, in <module>
    run_full_test("stt_en_conformer_ctc_small", batch_size=1, print_predictions=True)
  File "/dsp_nemo/testing_nemo.py", line 163, in run_full_test
    ologits = ort_session.run(None, ort_inputs)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_349' Status Message: /onnxruntime/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:37 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,115,176}, requested shape:{16,-1,4,44}

```

**Comment by borisfom** [comment]
I should have been more specific : you need both the latest Torch (1.10) and NeMo ToT for this to work correctly.
The easiest way to get this setup running is probably to start with NGC 21.12 Pytorch container, clone Nemo ToT and run ./reinstall.sh. I just exported stt_en_conformer_ctc_small as you described above and I am able to run resulting ONNX via ONNXruntime with the shapes that failed in your setup.

**Comment by Slava715** [comment]
Hello, I faced the same problem, did you manage to solve it?

**Comment by DanBmh** [comment]
Thanks, when using the pytorch container and installing nemo into it, it's working.

But when predicting the text, the dataloader seems to have some problems with whitespaces:
```
# print(hypotheses)
['▁they▁were▁subjected▁to▁constant▁surveillance▁and▁periodic▁searches']
    
[NeMo I 2022-01-10 19:03:01 wer_bpe:204] reference:theyweresubjectedtoconstantsurveillanceandperiodicsearches
[NeMo I 2022-01-10 19:03:01 wer_bpe:205] predicted:they were subjected to constant surveillance and periodic searches
WER = 9.0


# With QuartzNet.onnx model was working:
['they were subjected to constant surveillance and periodic searches ']
WER = 0.0
```

Did the manifest definition change? Currently it's:
```
{"audio_filepath": "/dsp_nemo/data/test.wav", "duration": 4.572, "text": "they were subjected to constant surveillance and periodic searches"}
```

**Comment by titu1994** [comment]
QuartzNet is a character based model - Conformer is a subword based model. You need to use the models tokenizer to decide the text. This should be done automatically in Nemo but won't be handled outside it. Since it uses Sentencepiece you can use it to decode the text v

**Comment by DanBmh** [comment]
The decoding is working in the above example, the problem is only that the WER calculation is incorrect. The logs show that the prediction is correct and matches the reference, except that in the reference text the whitespaces are missing.

**Comment by rGitcy** [comment]
> ```python
> setup_transcribe_dataloader
> ```

hi, setup_transcribe_dataloader is not fined!wherr is it?
