### ISSUE TITLE
Bug in examples/applications/asr_service

### ISSUE THREAD

**Issue by ggrunin** [NVIDIA/NeMo#343]
Error on application start:
```
Error: While importing "asr_service", an ImportError was raised:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/data/atc_tenant/temp/nemo/asr_servicec_refact_mixed/asr_service.py", line 2, in <module>
    from app import app
  File "/data/atc_tenant/temp/nemo/asr_servicec_refact_mixed/app/__init__.py", line 4, in <module>
    from app import routes
  File "/data/atc_tenant/temp/nemo/asr_servicec_refact_mixed/app/routes.py", line 6, in <module>
    from app import (
ImportError: cannot import name 'ENABLE_NGRAM'
```
To fix it the following line https://github.com/NVIDIA/NeMo/blob/c6a3cdd0223be6e8a53b40ae5f88eb62ffd80489/examples/applications/asr_service/app/__init__.py#L4 has to be moved to the line above https://github.com/NVIDIA/NeMo/blob/c6a3cdd0223be6e8a53b40ae5f88eb62ffd80489/examples/applications/asr_service/app/__init__.py#L53

**Comment by okuchaiev** [comment]
thanks for the fix!
