### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by Sushmitha-Deva** [NVIDIA/NeMo#3501]
**Describe the bug**

Below error is thrown while importing `nemo.collections.asr` package 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/collections/asr/losses/__init__.py", line 15, in <module>
    from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/collections/asr/losses/angularloss.py", line 18, in <module>
    from nemo.core.classes import Loss, Typing, typecheck
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/core/__init__.py", line 16, in <module>
    from nemo.core.classes import *
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/core/classes/__init__.py", line 16, in <module>
    from nemo.core.classes.common import (
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/core/classes/common.py", line 32, in <module>
    from nemo.utils import logging
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/utils/__init__.py", line 22, in <module>
    from nemo.utils.lightning_logger_patch import add_memory_handlers_to_pl_logger
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/nemo/utils/lightning_logger_patch.py", line 18, in <module>
    import pytorch_lightning as pl
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 26, in <module>
    from torchmetrics.functional.audio.pesq import perceptual_evaluation_speech_quality  # noqa: F401
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 20, in <module>
    import pesq as pesq_backend
  File "/home/local/miniconda3/envs/nemo1/lib/python3.8/site-packages/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

```

**Steps/Code to reproduce bug**

```
import nemo
import nemo.collections.asr as nemo_asr
```

**Environment overview (please complete the following information)**
 - conda environment: conda create -n nemo python=3.8 -y 
 - Method of NeMo install: pip install nemo_toolkit['all']

**Environment details**

- OS version - Ubuntu 20.04
- PyTorch version -  1.10.1
- PyTorch Lightning  version  - 1.5.8
- Python version - 3.8.12 
- Numpy version - 1.21.5
- Numba version - 0.55.0

**Comment by VahidooX** [comment]
Have you tried suggestions given here? 
https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by OjoDojoJo** [comment]
> Have you tried suggestions given here? https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

Following the suggestions leads to the following errors:
In case of upgrading numpy to the newest version: `ImportError: Numba needs NumPy 1.21 or less`
In case of downgrading numpy to 1.21.x and lower: `ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by b5y** [comment]
I am getting the same error in one of the AWS EC2 instances. Previously I resolved it with many tries of uninstallation and installation. Currently it doesn't help at all.

Could you please specify correct versions of all packages and their dependencies in the next release? For instance, if I try to upgrade `numpy`, then `Numba` doesn't work. If I try to downgrade `numpy`, then `pip` raises an error saying that `pytorch-lightning` is not compatible with `numpy`.

**Comment by b5y** [comment]
The main problem here is when you try to install `NeMo` via command (or any other option from README.md):

```bash
pip install nemo_toolkit[all]
```

then you run

```

conda remove numba
pip uninstall numba
conda install -c numba numba
```

It reinstalls `numpy`. And it doesn't matter if you install `Numba` first or `NeMo`.

**Comment by titu1994** [comment]
Numba may be incompatible with numpy for the time being. You can use Numba 0.55 since if seems to note that if supports numpy 1.21. And don't use conda install -c Numba. It's got an older version for some reason, use conda install -c conda-forge numba Numba>=0.55

**Comment by Sushmitha-Deva** [comment]
Installing numba using the `conda-forge` channel installs numba with version `0.55.0` and numpy with `1.21.5` . But this still doesn't solve the `ValueError` .

**Comment by titu1994** [comment]
Then apart from not installing Numba, using the Nemo container or asking on the lightning slack what's up with this torch metric's package, I don't have a solution. Numpy is a core library, if it causes a crash there's not much our team can do other than wait for other libraries to be compatible with if.

**Comment by b5y** [comment]
@titu1994 Regarding `Numba` installation. In `NeMo` documentation this [command](https://github.com/NVIDIA/NeMo#rnnt) was mentioned. If you use other command to install `Numba`, please update the documentation.

@titu1994 Your team can put relevant package versions for every dependency in every `NeMo` release. It could help for this kind of situations and install older versions of `NeMo`. If you take a look at [requirements](https://github.com/NVIDIA/NeMo/tree/main/requirements) folder you might notice that many dependency packages don't have exact versions in `*.txt` files.

**Comment by b5y** [comment]
Looks like support for [new](https://github.com/numba/numba/issues/7754) `numpy` version in `Numba` is one the way.

**Comment by titu1994** [comment]
> Your team can put relevant package versions for every dependency in every NeMo release

We won't be doing this since it leads to stale packages remaining for long periods of time. Some code packages such as Lightning are fixed for release branches, but the best way to expect a perfect environment is to use docker and not depend on conda. There will always be "compatible" libraries - Numba 0.55 does claim to support numpy 1.21 https://numba.readthedocs.io/en/stable/release-notes.html

If that is not the case, then Nemo team can't do much but wait for either 1) wait for Numba to be updated 2) wait for a patch release on numpy (which is what is 1.22

Again, do not expect perfect environments other than on docker. It is not a good engineering exercise to pin every requirement, that's what docker exists for.

**Comment by nkaenzig-aifund** [comment]
I had the same issue and wasn't able to resolve it using python 3.8.5.
However, I found a working configuration after downgrading to python 3.7.13

I used the following requirements.txt file:
[requirements.txt](https://github.com/NVIDIA/NeMo/files/8410508/requirements.txt)

**Comment by bfss** [comment]
Sorry for reopen this issue, you should:
uninstall numpy 
delete your pesq wheel cache
install numpy with specific version
So the pesq will rebuild with the specific numpy you just installed
