### ISSUE TITLE
nemo2riva Tacotron2 model

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/NeMo#3509]
When trying to convert a Tacotron2 TTS model trained with nemo I receive the following error:
```
W0125 21:12:08.102883 140527509010240 schema.py:118] Validation schema not found for nemo.collections.tts.models.Tacotron2Model.                
That means Riva does not yet support a pipeline for this network and likely will not work with it.                                              
I0125 21:12:08.860513 140527509010240 artifacts.py:54] Found model at ./model_weights.ckpt                                                      
I0125 21:12:08.861304 140527509010240 artifacts.py:120] Retrieved artifacts: dict_keys(['model_config.yaml'])                                   
E0125 21:12:08.861998 140527509010240 cookbook.py:58] Your NeMo model class (nemo.collections.tts.models.tacotron2.Tacotron2Model) is not Exportable.                                                                                                                                           
```
regardless that on https://docs.nvidia.com/deeplearning/riva/user-guide/docs/service-tts.html#model-deployment, mention both FastPitch+HifiGAN and Tacotron2+Waveglow.

**Comment by blisc** [comment]
You do not use nemo2riva for Tacotron2. You use the tacotron2.nemo file in the riva-build command as can be found in our docs: https://docs.nvidia.com/deeplearning/riva/user-guide/docs/service-tts.html#riva-build-tacotron2-and-waveglow-pipeline-configuration

We will improve the Riva TTS docs to make this clearer in an upcoming release.

**Comment by itzsimpl** [comment]
Sorry, but that too does not work. First of all the instructions indicate to use a `/servicemaker-dev/<waveglow_riva_filename>:<encryption_key> \` but there is no riva file available. If I instead supply the `tts_waveglow.nemo` file (following the approach for the `tacotron2.nemo` parameter) the conversion crashes with the following. I use Riva 1.8.0 and NeMo:1.6.0rc0.

```
root@fc7376e28dad:/servicemaker-dev# riva-build speech_synthesis data/rmir/t2wg.rmir data/nemo/tts_en_tacotron2.nemo data/nemo/tts_waveglow.nemo --voice_name=test
2022-01-26 20:48:14,670 [INFO] Retrieved artifacts: dict_keys(['model_config.yaml', 'model_weights.ckpt'])
2022-01-26 20:48:22,520 [INFO] Retrieved artifacts: dict_keys(['model_config.yaml', 'model_weights.ckpt'])
Traceback (most recent call last):
  File "/opt/conda/bin/riva-build", line 8, in <module>
    sys.exit(build())
  File "/opt/conda/lib/python3.8/site-packages/servicemaker/cli/build.py", line 97, in build
    pipeline_config.init_from(nm.get_config())
  File "/opt/conda/lib/python3.8/site-packages/servicemaker/pipelines/tts.py", line 202, in init_from
    config.init_from(self, src_config)
  File "/opt/conda/lib/python3.8/site-packages/servicemaker/modules/tts.py", line 300, in init_from
    wg_params = src_config['waveglow']['params']
KeyError: 'params'
```

**Comment by blisc** [comment]
Do nemo2riva on waveglow

**Comment by itzsimpl** [comment]
Nemo2riva on tts_waveglow.nemo crashes with 
```
W0126 21:20:23.777717 140065183713088 schema.py:118] Validation schema not found for nemo.collections.tts.models.WaveGlowModel.
That means Riva does not yet support a pipeline for this network and likely will not work with it.
I0126 21:20:26.362541 140065183713088 artifacts.py:54] Found model at ./model_weights.ckpt
I0126 21:20:26.363363 140065183713088 artifacts.py:120] Retrieved artifacts: dict_keys(['model_config.yaml'])
I0126 21:20:26.370697 140065183713088 cookbook.py:68] Exporting model with autocast=False
[NeMo W 2022-01-26 21:20:27 export_utils:198] Swapped 0 modules
[NeMo W 2022-01-26 21:20:29 export_utils:198] Swapped 253 modules
E0126 21:20:29.174381 140065183713088 cookbook.py:71] Export failed. Please make sure your NeMo model class (nemo.collections.tts.models.waveglow.WaveGlowModel) has working export() and that you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/opt/conda/bin/nemo2riva", line 8, in <module>
    sys.exit(nemo2riva())
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/cli/nemo2riva.py", line 50, in nemo2riva
    Nemo2Riva(args)
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/convert.py", line 65, in Nemo2Riva
    save_archive(obj=model, save_path=riva_out, cfg=cfg, artifacts=artifacts, metadata=manifest['metadata'])
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/cookbook.py", line 76, in save_archive
    raise e
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/cookbook.py", line 69, in save_archive
    _, descriptions = obj.export(export_file, check_trace=cfg.args.runtime_check)
  File "/data/ilb.nemo/nemo/core/classes/exportable.py", line 179, in export
    output_example = tuple(self.forward(*input_list, **input_dict))
  File "/data/ilb.nemo/nemo/collections/tts/models/waveglow.py", line 252, in forward_for_export
    return self.waveglow(spec, z)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ilb.nemo/nemo/collections/tts/modules/waveglow.py", line 128, in forward
    audio_pred = self.norm_dist_to_audio(spec=spec, sigma=sigma, z=z)
  File "/data/ilb.nemo/nemo/collections/tts/modules/waveglow.py", line 216, in norm_dist_to_audio
    spec = torch.unsqueeze(spec, 3)
TypeError: unsqueeze(): argument 'input' (position 1) must be Tensor, not str
```

**Comment by blisc** [comment]
Ok, I'll file a bug. In the meantime, you can try https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/models/speechsynthesis_waveglow/files

**Comment by itzsimpl** [comment]
Thank you, the linked riva file it does work. But I would really like to be able to deploy mine. Any pointers on how to do it?

**Comment by itzsimpl** [comment]
Looking to the files contained in `.nemo` and `.riva`, I noticed that `denoiser.json` is missing in `.nemo` .

**Comment by okuchaiev** [comment]
waiting for https://github.com/NVIDIA/NeMo/pull/3586 to close.
