### ISSUE TITLE
_youtokentome.so: undefined symbol: _ZNSt7__cxx...

### ISSUE THREAD

**Issue by akashrajkn** [NVIDIA/NeMo#3533]
**Describe the bug**

I am unable to use nemo models due to some issue with the tokenizer: 
```
    from nemo.collections.asr.models      import EncDecCTCModel
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/models/__init__.py", line 18, in <module>
    from nemo.collections.asr.models.classification_models import EncDecClassificationModel
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/models/classification_models.py", line 33, in <module>
    from nemo.collections.common.metrics import TopKClassificationAccuracy
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/__init__.py", line 16, in <module>
    from nemo.collections.common import data, losses, parts, tokenizers
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/tokenizers/__init__.py", line 24, in <module>
    from nemo.collections.common.tokenizers.youtokentome_tokenizer import YouTokenToMeTokenizer
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/tokenizers/youtokentome_tokenizer.py", line 17, in <module>
    import youtokentome as yttm
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/youtokentome/__init__.py", line 1, in <module>
    from .youtokentome import BPE
  File "/home/linux/miniconda3/envs/env/lib/python3.9/site-packages/youtokentome/youtokentome.py", line 4, in <module>
    import _youtokentome_cython
ImportError: /home/linux/miniconda3/envs/env/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv

```

**Steps/Code to reproduce bug**

```
from nemo.collections.asr.models import EncDecCTCModel
```

**Environment overview (please complete the following information)**

 - Environment location: local
 - Method of NeMo install: `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]`

**Environment details**

- OS version: `Pop OS 21.10` (similar issue on Ubuntu 21.04)
- PyTorch version: `1.10.1`
- Python version: `3.9`

**Comment by akashrajkn** [comment]
Here's the full traceback for reference:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <module>
----> 1 from nemo.collections.asr.models import EncDecCTCModel

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/__init__.py:15, in <module>
      1 # Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 15 from nemo.collections.asr import data, losses, models, modules
     16 from nemo.package_info import __version__
     18 # Set collection version equal to NeMo version.

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/models/__init__.py:18, in <module>
     16 try:
     17     from nemo.collections.asr.models.asr_model import ASRModel
---> 18     from nemo.collections.asr.models.classification_models import EncDecClassificationModel
     19     from nemo.collections.asr.models.clustering_diarizer import ClusteringDiarizer
     20     from nemo.collections.asr.models.ctc_bpe_models import EncDecCTCModelBPE

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/models/classification_models.py:28, in <module>
     25 from pytorch_lightning import Trainer
     26 from torchmetrics.regression import MeanAbsoluteError, MeanSquaredError
---> 28 from nemo.collections.asr.data import audio_to_label_dataset
     29 from nemo.collections.asr.models.asr_model import ASRModel, ExportableEncDecModel
     30 from nemo.collections.asr.parts.preprocessing.features import WaveformFeaturizer

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/data/audio_to_label_dataset.py:15, in <module>
      1 # Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 15 from nemo.collections.asr.data import audio_to_label
     16 from nemo.collections.asr.data.audio_to_text_dataset import convert_to_config_list, get_chain_dataset
     19 def get_classification_label_dataset(featurizer, config: dict) -> audio_to_label.AudioToClassificationLabelDataset:

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/data/audio_to_label.py:22, in <module>
     19 import torch
     20 import webdataset as wd
---> 22 from nemo.collections.asr.parts.preprocessing.segment import available_formats as valid_sf_formats
     23 from nemo.collections.common.parts.preprocessing import collections
     24 from nemo.core.classes import Dataset, IterableDataset

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/__init__.py:16, in <module>
      1 # Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 from nemo.collections.asr.parts.preprocessing.feature_loader import ExternalFeatureLoader
---> 16 from nemo.collections.asr.parts.preprocessing.features import (
     17     STFT,
     18     FeaturizerFactory,
     19     FilterbankFeatures,
     20     STFTExactPad,
     21     STFTPatch,
     22     WaveformFeaturizer,
     23 )
     24 from nemo.collections.asr.parts.preprocessing.perturb import (
     25     AudioAugmentor,
     26     AugmentationDataset,
   (...)
     39     register_perturbation,
     40 )
     41 from nemo.collections.asr.parts.preprocessing.segment import AudioSegment

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/features.py:46, in <module>
     43 from librosa.util import tiny
     44 from torch.autograd import Variable
---> 46 from nemo.collections.asr.parts.preprocessing.perturb import AudioAugmentor
     47 from nemo.collections.asr.parts.preprocessing.segment import AudioSegment
     48 from nemo.utils import logging

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/asr/parts/preprocessing/perturb.py:50, in <module>
     47 from torch.utils.data import IterableDataset
     49 from nemo.collections.asr.parts.preprocessing.segment import AudioSegment
---> 50 from nemo.collections.common.parts.preprocessing import collections, parsers
     51 from nemo.utils import logging
     53 # TODO @blisc: Perhaps refactor instead of import guarding

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/__init__.py:16, in <module>
      1 # Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 import nemo.collections.common.callbacks
---> 16 from nemo.collections.common import data, losses, parts, tokenizers
     17 from nemo.package_info import __version__
     19 # Set collection version equal to NeMo version.

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/tokenizers/__init__.py:24, in <module>
     22     from nemo.collections.common.tokenizers.huggingface.auto_tokenizer import AutoTokenizer
     23     from nemo.collections.common.tokenizers.sentencepiece_tokenizer import SentencePieceTokenizer
---> 24     from nemo.collections.common.tokenizers.youtokentome_tokenizer import YouTokenToMeTokenizer
     25 except ModuleNotFoundError:
     26     from nemo.utils.exceptions import CheckInstall

File ~/miniconda3/envs/env/lib/python3.9/site-packages/nemo/collections/common/tokenizers/youtokentome_tokenizer.py:17, in <module>
      1 # Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 from pathlib import Path
---> 17 import youtokentome as yttm
     19 from nemo.collections.common.tokenizers import TokenizerSpec
     21 __all__ = ['YouTokenToMeTokenizer']

File ~/miniconda3/envs/env/lib/python3.9/site-packages/youtokentome/__init__.py:1, in <module>
----> 1 from .youtokentome import BPE
      2 from .youtokentome import OutputType

File ~/miniconda3/envs/env/lib/python3.9/site-packages/youtokentome/youtokentome.py:4, in <module>
      1 from enum import Enum
      2 from typing import List, Union, Optional, Collection
----> 4 import _youtokentome_cython
      7 class OutputType(Enum):
      8     ID = 1

ImportError: /home/linux/miniconda3/envs/env/lib/python3.9/site-packages/_youtokentome_cython.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv

```

**Comment by MaximumEntropy** [comment]
This looks like an issue with the youtokentome installation. Can you try installing youtokentome in a separate env to see if that works?

**Comment by NiziL** [comment]
For future reader:

I had the exact same issue on an up-to-date Archlinux, with python 3.10 and pytorch 1.11.0

A simple `pip uninstall youtokentome` followed by `conda install youtokentome` solved it.
Can't explain why... But hope it will help you ;)
