### ISSUE TITLE
How do we mute these warnings?

### ISSUE THREAD

**Issue by orrburgel** [NVIDIA/NeMo#3558]
Hey, I'm a windows user who tries to do ASR using Nemo without Cuda, I therefor can't install Apex and pynini no matter how hard we tried, **I would like to simply mute these apex errors** or optionally other warnings along and will love any solution for installing pynini so I can use the NLP module:
```
[NeMo W 2022-01-29 11:23:23 optimizers:52] Apex was not found. Using the lamb or fused_adam optimizer will error out.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function get_argmin_mat at 0x00000221299F81F0> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function getMultiScaleCosAffinityMatrix at 0x00000221299F8280> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function parse_scale_configs at 0x00000221299F8CA0> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function get_embs_and_timestamps at 0x00000221299F8D30> is experimental, not ready for production and is not fully supported. Use at your own risk.
Transcribing:   0%|                                                                              | 0/1 [00:00<?, ?it/s][NeMo W 2022-01-29 11:23:27 nemo_logging:349] C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
      warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')

Transcribing: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.54it/s]
```

Code Used:
```
import nemo.collections.asr as nemo_asr
import logging
logging.getLogger('nemo_logger').setLevel(logging.CRITICAL)
#TIP: to see a list of available pre-trained ASR models, in a Python shell do:
nemo_asr.models.EncDecCTCModel.list_available_models()
# This will initiate pre-trained model download from NGC
asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained("stt_en_quartznet15x5")
transcriptions = asr_model.transcribe(['2086-149220-0033.wav'])
print(transcriptions)

# Now, lets add punctuation
import nemo.collections.nlp as nemo_nlp 
# this will also trigger model download
punctuation = nemo_nlp.models.PunctuationCapitalizationModel.from_pretrained(model_name='punctuation_en_distilbert')
res = punctuation.add_punctuation_capitalization(queries=transcriptions)
print(res)
```

Win10
Py3.6-Py3.10
Worked on 3.8 and 3.9
by worked I mean transcribed, along with these errors:
```
[NeMo W 2022-01-29 11:23:23 optimizers:52] Apex was not found. Using the lamb or fused_adam optimizer will error out.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function get_argmin_mat at 0x00000221299F81F0> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function getMultiScaleCosAffinityMatrix at 0x00000221299F8280> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function parse_scale_configs at 0x00000221299F8CA0> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2022-01-29 11:23:24 experimental:27] Module <function get_embs_and_timestamps at 0x00000221299F8D30> is experimental, not ready for production and is not fully supported. Use at your own risk.
Transcribing:   0%|                                                                              | 0/1 [00:00<?, ?it/s][NeMo W 2022-01-29 11:23:27 nemo_logging:349] C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\torch\autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
      warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')

Transcribing: 100%|██████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.54it/s]
["well i don't wish to see it any more observed phoebe turning away her eyes it is certainly very likt the old portrait"]
Traceback (most recent call last):
  File "C:\Users\orrbu\Desktop\test.py", line 12, in <module>
    import nemo.collections.nlp as nemo_nlp
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\__init__.py", line 27, in <module>
    from nemo.collections.nlp.models.machine_translation import MTEncDecModel
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\machine_translation\__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.machine_translation.mt_enc_dec_bottleneck_model import MTBottleneckModel
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\machine_translation\mt_enc_dec_bottleneck_model.py", line 29, in <module>
    from sacrebleu import corpus_bleu
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\sacrebleu\__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\sacrebleu\utils.py", line 12, in <module>
    import portalocker
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\portalocker\portalocker.py", line 11, in <module>
    import win32file
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```

Which means that the second codeblock regarding NLP gave this error:
```
Traceback (most recent call last):
  File "C:\Users\orrbu\Desktop\test.py", line 12, in <module>
    import nemo.collections.nlp as nemo_nlp
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\__init__.py", line 27, in <module>
    from nemo.collections.nlp.models.machine_translation import MTEncDecModel
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\machine_translation\__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.machine_translation.mt_enc_dec_bottleneck_model import MTBottleneckModel
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\nemo\collections\nlp\models\machine_translation\mt_enc_dec_bottleneck_model.py", line 29, in <module>
    from sacrebleu import corpus_bleu
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\sacrebleu\__init__.py", line 21, in <module>
    from .utils import smart_open, SACREBLEU_DIR, download_test_set  # noqa: F401
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\sacrebleu\utils.py", line 12, in <module>
    import portalocker
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\Users\orrbu\anaconda3\envs\py39\lib\site-packages\portalocker\portalocker.py", line 11, in <module>
    import win32file
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```
```

**Comment by titu1994** [comment]
Nemo does not support windows. You may try to use if with WSL 2 (or 1 if you want only CPU).

**Comment by orrburgel** [comment]
How can you claim it doesnt work on windows after I claim I got it to work
and Im just trying to get rid of some warnings, this is not errors, this
code above is actually working on windows without wsl

**Comment by titu1994** [comment]
You can try the suggestion here then - https://stackoverflow.com/questions/2266646/how-to-disable-logging-on-the-standard-error-stream or  https://www.delftstack.com/howto/python/suppress-warnings-python/ after importing the Nemo logger.

**Comment by orrburgel** [comment]
Hey @titu1994, thanks, But as you can see in the code I shared originally I already used the logger and it did not help, Did I used it wrong?
If you read my code it will already have the logger module:

```
import nemo.collections.asr as nemo_asr
import logging
logging.getLogger('nemo_logger').setLevel(logging.CRITICAL)
```

**Comment by orrburgel** [comment]
@titu1994 Boom I got it:
```
import logging
logging.disable()

import nltk
_old_download = nltk.download
def _new_download(package, quiet=True):
    pass #punkt
    _old_download(package, quiet=quiet)
nltk.download = _new_download

import nemo.collections.asr as nemo_asr
import nemo.collections.nlp as nemo_nlp

if __name__ == "__main__":
    print("==========================FINISHED0")
    asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained("stt_en_quartznet15x5")
    punctuation = nemo_nlp.models.PunctuationCapitalizationModel.from_pretrained(model_name='punctuation_en_distilbert')
    print("==========================FINISHED1")
    transcriptions = asr_model.transcribe(['2086-149220-0033.wav'])
    print(transcriptions)
    print("==========================FINISHED2")
    res = punctuation.add_punctuation_capitalization(queries=transcriptions)
    print(res)
```

Cleanest output you can get, But, I still have this transcribing progress bar, is there any way to remove it?

**Comment by orrburgel** [comment]
this actually works on widows, do you want to collaborate to help me add windows support to nemo? listen I know how to fix every error on windows now lets bring this to the public :)

**Comment by EmreOzkose** [comment]
@burgil Did you solve this issue? I am a Linux user and wondering if there is a workaround or not. I am using cuda, but there are some `experimental` warnings like yours.

**Comment by EmreOzkose** [comment]
That is the solution: https://github.com/NVIDIA/NeMo/issues/1376#issuecomment-1040284570
