### ISSUE TITLE
W&B Causing GPT3 Run to Crash

### ISSUE THREAD

**Issue by markelsanz14** [NVIDIA/NeMo#3608]
Weights and Biases is causing some GPT-3 runs to fail. This seems to occur randomly. When launching multiple identical jobs, the first two can fail because of this and the third one works.

Traceback:

> Traceback (most recent call last):
  File "/opt/conda/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/cli/cli.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/cli/cli.py", line 235, in login
    wandb.login(relogin=relogin, key=key, anonymous=anon_mode, host=host, force=True)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 65, in login
    configured = _login(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 268, in _login
    wlogin.configure_api_key(key)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 154, in configure_api_key
    apikey.write_key(self._settings, key)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/apikey.py", line 223, in write_key
    api.clear_setting("anonymous", globally=True, persist=True)
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 75, in clear_setting
    return self.api.clear_setting(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 19, in api
    self._api = InternalApi(*self._api_args, **self._api_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 78, in __init__
    self._settings = Settings(
  File "/opt/conda/lib/python3.8/site-packages/wandb/old/settings.py", line 23, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/opt/conda/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/opt/conda/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/root/.config/wandb/settings', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

**Comment by titu1994** [comment]
You can rm the entire wandb folder inside /.config/ so that it correctly writes the file in the next run. It's odd because we run multi node experiments too but haven't encountered this yet. @ericharper any idea about this ?

**Comment by orrburgel** [comment]
I'm sorry to interfere but I'm curios how were you able to run GPT3 without their API (which I'm a part of), it's closed source, did they open source it?

**Comment by markelsanz14** [comment]
@orrburgel NeMo supports the GPT-3 architecture, I trained it with NeMo, not the OpenAI API.

**Comment by orrburgel** [comment]
Interesting, How will you go about getting the GPT-3 architecture without access to OpenAI API? @markelsanz14

**Comment by markelsanz14** [comment]
@aidanjdonohue I will give it a try. I think I tried it before and it didn't work, but it might be due to running multiple jobs simultaneously.

**Comment by michalivne** [comment]
The issue of a race condition due to `wand login` in a multi-node job can be avoided with
```
export WANDB_API_KEY=${WANDB}
```
instead of 
```
wandb login ${WANDB}
```
in the launch script
