### ISSUE TITLE
CUDA error: an illegal memory access was encountered when training fastpitch

### ISSUE THREAD

**Issue by godspirit00** [NVIDIA/NeMo#3620]
**Describe the bug**

When I tried to train / finetune FastPitch, the following error shows up:

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 277, in _run_optimization
    self.trainer.fit_loop.epoch_loop.batch_loop._update_running_loss(result.loss)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 127, in _update_running_loss
    self.accumulated_loss.append(current_loss)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 78, in append
    x = x.to(self.memory)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/tts/fastpitch_finetune.py", line 37, in main
    trainer.fit(model)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 698, in _call_and_handle_interrupt
    self.training_type_plugin.reconciliate_processes(traceback.format_exc())
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 533, in reconciliate_processes
    raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \n {trace}")
pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 0 
 Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 277, in _run_optimization
    self.trainer.fit_loop.epoch_loop.batch_loop._update_running_loss(result.loss)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 127, in _update_running_loss
    self.accumulated_loss.append(current_loss)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 78, in append
    x = x.to(self.memory)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Steps/Code to reproduce bug**

I tried to train a FastPitch model on the Nancy Corpus, the above error showed up at first with the cmd: `examples/tts/fastpitch.py --config-name=fastpitch_align.yaml train_dataset=/root/autodl-tmp/nancy_train.json validation_datasets=/root/autodl-tmp/nancy_val.json prior_folder=/root/autodl-tmp/nemo-training/nancy_22k/prior exp_manager.exp_dir=/root/autodl-tmp/nemo-training/nancy_22k +exp_manager.resume_if_exists=True +exp_manager.resume_ignore_no_checkpoint=True model.train_ds.dataloader_params.batch_size=24 model.validation_ds.dataloader_params.batch_size=24`, then I changed the `exp_dir`
, it started training.
Then I tried to finetune the resulting model on my own dataset with cmd `python examples/tts/fastpitch_finetune.py --config-name=fastpitch_align.yaml train_dataset=/root/autodl-tmp/male-speakers--with--nancy_train.json validation_datasets=/root/autodl-tmp/male-speakers--with--nancy_val.json +init_from_nemo_model=/root/autodl-tmp/nemo-training/nancy_fastpitch.nemo prior_folder=/root/autodl-tmp/nemo-training/multi-males/prior_multi-males model.train_ds.dataloader_params.batch_size=24 model.validation_ds.dataloader_params.batch_size=24   exp_manager.exp_dir=/root/autodl-tmp/nemo-training/multi-males model.n_speakers=5 model.pitch_avg=121.9 model.pitch_std=37.1 model.pitch_fmin=30 model.pitch_fmax=512 model.optim.lr=2e-4 ~model.optim.sched`, the error showed up again, and this time changing `exp_dir` does not help.

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: Cloud: [AutoDL](https://www.autodl.com/)
 - Method of NeMo install: From source, `git clone` and `pip install .[tts]`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
PyTorch  1.10.0, Python  3.8, Cuda  11.3

**Additional context**

GPU: RTX 3090 * 2
VRAM: 24GB
CPU: 30 Cores AMD EPYC 7543 32-Core Processor
RAM: 160GB

**Comment by godspirit00** [comment]
Update:  adding `model.optim.name=adam` to the cmd solved the problem. Looks like it has something to do with the lamb optimizer.

**Comment by okuchaiev** [comment]
@Oktai15  any thoughts on lamb for this model? Otherwise, please close the issue.

**Comment by Oktai15** [comment]
@godspirit00, did you install apex?
