### ISSUE TITLE
fastpitch_finetuning.ipynb does not work from scratch

### ISSUE THREAD

**Issue by gedefet** [NVIDIA/NeMo#3687]
Hi all. 

The tutorial https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_Finetuning.ipynb does not work from scratch.

First, I have to replace NeMo for NVIDIA in the first setup cell for enable it to run:

```
!python -m pip install git+https://github.com/NeMo/NeMo.git@$BRANCH#egg=nemo_toolkit[all]
```

for

```
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]
```

Then, I got the following error in the 11th cell:

First commands of the cell:

```
new_speaker_id = 6097
duration_mins = 5
mixing = False
original_speaker_id = "ljspeech"

_ ,last_ckpt = get_best_ckpt("./", new_speaker_id, duration_mins, mixing, original_speaker_id)
print(last_ckpt)
```

Error:

```
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _check_seekable(f)
    307     try:
--> 308         f.seek(f.tell())
    309         return True

AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
8 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in raise_err_msg(patterns, e)
    302                                 + " Please pre-load the data into a buffer like io.BytesIO and"
    303                                 + " try to load from it instead.")
--> 304                 raise type(e)(msg)
    305         raise e
    306 

AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

Best,

**Comment by Oktai15** [comment]
@gedefet, do you use colab or local/remote machine?

**Comment by gedefet** [comment]
@Oktai15 Colab and Colab PRO +, same behaviour in both.

**Comment by Oktai15** [comment]
@gedefet, could you provide the public link where you can get this error?

**Comment by gedefet** [comment]
@Oktai15 yes sure, https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_Finetuning.ipynb

**Comment by Oktai15** [comment]
@gedefet, try it, please:

https://github.com/NVIDIA/NeMo/blob/fix_bug_tts_tutorials/tutorials/tts/FastPitch_Finetuning.ipynb

**Comment by gedefet** [comment]
@Oktai15 , another error, cannot find the checkpoint,  same line:

```
new_speaker_id = 6097
duration_mins = 5
mixing = False
original_speaker_id = "ljspeech"

----> last_ckpt = get_best_ckpt_from_last_run("./", new_speaker_id, duration_mins, mixing, original_speaker_id)
```

Error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-11-a97c845d885c>](https://localhost:8080/#) in <module>()
      4 original_speaker_id = "ljspeech"
      5 
----> 6 last_ckpt = get_best_ckpt_from_last_run("./", new_speaker_id, duration_mins, mixing, original_speaker_id)
      7 print(last_ckpt)
      8 

[<ipython-input-10-7bc5c0112a54>](https://localhost:8080/#) in get_best_ckpt_from_last_run(base_dir, new_speaker_id, duration_mins, mixing_enabled, original_speaker_id, model_name)
     48 
     49     if len(last_ckpt) == 0:
---> 50         raise ValueError(f"There is no last checkpoint in {last_checkpoint_dir}.")
     51 
     52     return str(last_ckpt[0])

ValueError: There is no last checkpoint in ljspeech_to_6097_no_mixing_5_mins/FastPitch/2022-02-18_12-45-05/checkpoints.
```

Thanks,

**Comment by Oktai15** [comment]
@gedefet, which part of code needs `folium` and `tf-estimator-nightly`? I suppose you don't need it.

Try to use this tutorial (it is not in main currently, but it will be soon): https://github.com/NVIDIA/NeMo/blob/fix_bug_tts_tutorials/tutorials/tts/FastPitch_Finetuning.ipynb

**Comment by gedefet** [comment]
That was the one I was using. Same error. Also changing `BRANCH = 'main'` to `BRANCH = 'fix_bug_tts_tutorials'`

**Comment by Oktai15** [comment]
@gedefet, which python version do you use?

**Comment by gedefet** [comment]
@Oktai15 Python 3.7.12, the one that comes with Colab

**Comment by Oktai15** [comment]
You need to change `BRANCH` and re-install NeMo.

**Comment by gedefet** [comment]
Well, from your image I see you run Colab directly from the link. I always ran it copying it to my drive first. 

Run the Colab directly and it worked, at least to train FastPitch. Then copied to my drive and also run correctly. I honestly don't know why this happen, given I always used the same link. 

I changed `BRANCH` to `fix_bug_tts_tutorials`.

Thanks,

**Comment by Oktai15** [comment]
@gedefet, great! We can close this issue?

**Comment by gedefet** [comment]
@Oktai15 yes, I'll be using this branch `fix_bug_tts_tutorials` then until it is merged in `main`.

Thank you!

**Comment by Oktai15** [comment]
@gedefet, merged. You can use main.

**Comment by gedefet** [comment]
@Oktai15 Worked! Thank you very much

**Comment by evelyn-f-king** [comment]
Hello,

The dependency changes that @gedefet mentioned are still required & not added to main. In order to get it to run from scratch. Running everything as-is from main, you end up with this:

```
Traceback (most recent call last):
  File "fastpitch_finetune.py", line 32, in main
    model = FastPitchModel(cfg=cfg.model, trainer=trainer)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 59, in __init__
    self._setup_normalizer(cfg)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 134, in _setup_normalizer
    self.normalizer = instantiate(cfg.text_normalizer, **normalizer_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 66, in _call_target
    ).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nemo_text_processing/text_normalization/normalize.py", line 72, in __init__
    raise ImportError(get_installation_msg())
ImportError: Error instantiating 'nemo_text_processing.text_normalization.normalize.Normalizer' : `pynini` is not installed ! 
 Please run the `nemo_text_processing/setup.sh` script prior to usage of this toolkit.
```

I tried without the `tf-estimator` because it seemed like a particularly weird dependency, but even with it, it fails with a different error:

```
Traceback (most recent call last):
  File "fastpitch_finetune.py", line 32, in main
    model = FastPitchModel(cfg=cfg.model, trainer=trainer)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 72, in __init__
    self._setup_tokenizer(cfg)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 152, in _setup_tokenizer
    text_tokenizer_kwargs["g2p"] = instantiate(cfg.text_tokenizer.g2p, **g2p_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 66, in _call_target
    ).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
TypeError: Error instantiating 'nemo.collections.tts.torch.g2ps.EnglishG2p' : __init__() got an unexpected keyword argument 'phoneme_probability'
```
Just using a standard Colab GPU notebook- going to try the MixerTTS + FastSpeech example as well.
