### ISSUE TITLE
nemo2riva Can't instantiate abstract class ModelPT with abstract methods

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#3882]
**Describe the bug**

I'm trying to convert a CitriNet model I trained with NeMo v1.7.0 to the Riva format using the `nemo2riva` CLI tool.
Everytime I run:

```sh
nemo2riva --out my-model.riva my-model.nemo
```
I get the following error:

```sh
ERROR: Failed to restore model from NeMo file : my-model.nemo. Please make sure you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/nm-debug/bin/nemo2riva", line 8, in <module>
    sys.exit(nemo2riva())
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo2riva/cli/nemo2riva.py", line 50, in nemo2riva
    Nemo2Riva(args)
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo2riva/convert.py", line 42, in Nemo2Riva
    raise e
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo2riva/convert.py", line 35, in Nemo2Riva
    model = ModelPT.restore_from(restore_path=nemo_in)
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 270, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo/core/connectors/save_restore_connector.py", line 136, in restore_from
    instance = calling_cls.from_config_dict(config=conf)
  File "/home/allabana/.virtualenvs/nm-debug/lib/python3.8/site-packages/nemo/core/classes/common.py", line 473, in from_config_dict
    instance = cls(cfg=config)
TypeError: Can't instantiate abstract class ModelPT with abstract methods list_available_models, setup_training_data, setup_validation_data
```

I've tried every combination of `nemo2riva` and `nemo_toolkit` from 1.7.0-1.10.0 and 1.3.0-1.7.0 respectively.
I would install using:

```sh
# X = [7, 8, 9, 10]
pip install  nemo2riva-1.X.0b0-py3-none-any.whl
# X = [3, 4, 5, 6, 7]
pip install 'nemo_toolkit[all]==1.X.0'
```

**Steps/Code to reproduce bug**

Use any nemo model, including the pretrained citrinet models and try to convert it

```sh
ngc registry resource download-version "nvidia/riva/riva_quickstart:1.10.0-beta"
cd riva_quickstart_v1.10.0-beta
pip install nemo2riva-1.10.0b0-py3-none-any.whl
nemo2riva --out my-model.riva my-model.nemo
```

**Expected behavior**

`nemo2riva` converts the model succesfully.

**Environment overview (please complete the following information)**

 - Environment location: Docker and Bare metal
 - Method of NeMo install: `pip install 'nemo_toolkit[all]==1.7.0'`
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 Using Docker image `nvcr.io/nvidia/riva/riva-speech:1.10.0-beta-servicemaker`

**Environment details**

Docker and local
Otherwise, please provide:
- OS version: Ubuntu 20.04
- PyTorch version: 1.10.0
- Python version: 3.8

**Additional context**

GPU model: RTX 3090

**Comment by piraka9011** [comment]
I tried the following and all failed with the same error:

```py
>>> from nemo.core import ModelPT
>>> m  = ModelPT.restore_from("my-model.nemo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 292, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/connectors/save_restore_connector.py", line 142, in restore_from
    instance = calling_cls.from_config_dict(config=conf, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 505, in from_config_dict
    raise e
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 497, in from_config_dict
    instance = cls(cfg=config, trainer=trainer)
TypeError: Can't instantiate abstract class ModelPT with abstract methods list_available_models, setup_training_data, setup_validation_data
>>> from nemo.collections.asr.models import ASRModel
>>> m = ASRModel.restore_from("my-model.nemo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 292, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/connectors/save_restore_connector.py", line 142, in restore_from
    instance = calling_cls.from_config_dict(config=conf, trainer=trainer)
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 505, in from_config_dict
    raise e
  File "/opt/conda/lib/python3.8/site-packages/nemo/core/classes/common.py", line 497, in from_config_dict
    instance = cls(cfg=config, trainer=trainer)
TypeError: Can't instantiate abstract class ASRModel with abstract methods setup_training_data, setup_validation_data, transcribe
```

Except for

```py
>>> from nemo.collections.asr.models import EncDecCTCModelBPE
>>> m = EncDecCTCModelBPE.restore_from("my-model.nemo")
[NeMo I 2022-03-25 00:11:34 mixins:146] Tokenizer SentencePieceTokenizer initialized with 1024 tokens
[NeMo W 2022-03-25 00:11:35 modelPT:135] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /audio-data/EA-UD/train_ea-ud_manifest.absolute.json,/audio-data/TLUD/train_tlud_manifest.absolute.json
    sample_rate: 16000
    max_duration: 31
    batch_size: 8
    num_workers: 16
    trim_silence: false
    use_dali: false
    shuffle: true
    is_tarred: false

[NeMo W 2022-03-25 00:11:35 modelPT:142] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /audio-data/EA-UD/val_ea-ud_manifest.absolute.json,/audio-data/TLUD/val_tlud_manifest.absolute.json
    sample_rate: 16000
    max_duration: 31
    batch_size: 8
    num_workers: 16
    trim_silence: false
    shuffle: false
    use_dali: false
    is_tarred: false

[NeMo I 2022-03-25 00:11:35 features:264] PADDING: 16
[NeMo I 2022-03-25 00:11:35 features:281] STFT using torch
[NeMo I 2022-03-25 00:11:43 save_restore_connector:154] Model EncDecCTCModelBPE was successfully restored from /workspace/data/nemo_models/my-model.nemo.
```

**Comment by piraka9011** [comment]
The config of the `.nemo` file for some reason was missing the following key:

`target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE`

I got this working w/ NeMo (1.4.0) and nemo2riva (1.8.0).
I will try different combos and if they work, I will close this issue.

**Comment by piraka9011** [comment]
Using NeMo (1.7.0) and nemo2riva (1.10.0), I was able to successfully convert a `.nemo` model to `.riva` 🎉 .
I did have to however re-install `torch` to get the Cuda version and use the nemo2riva wheel from ngc and not the one in the container.

Is that intended? I can also open a discussion in the Riva forums.
I had to do the following:

```sh
docker run --gpus all --shm-size=1gb --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v $(pwd):/workspace --entrypoint /bin/bash \
    nvcr.io/nvidia/riva/riva-speech:1.10.0-beta-servicemaker
$ apt update && apt remove -y python3-pip && apt install -y python3-pip
$ python -m pip uninstall -y torch torchvision torchaudio
$ python -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
$ python -m pip install nemo_toolkit[all]==1.7.0 setuptools==59.5.0 nemo2riva-1.10.0b0-py3-none-any.whl
$ nemo2riva path/to/my-model.nemo
```

**Comment by titu1994** [comment]
The nemo2riva tool should be used only on Riva containers, since that is where it's officially supported. While yes it can be pip installed and uses underlying Nemo code to export, it's support matrix between Nemo version and Riva compatible version is very strict as you found out. 

As to the particular issue with installing torch, yes I would open a issue on the Riva developer discussions forum.

**Comment by borisfom** [comment]
Yes having 'target' key is requirement for Riva. The best way to get working Nemo2Riva setup is to use ServiceMaker container from Riva and reinstall latest NeMo in it (either from source with 'reinstall.sh dev or using  "pip install -U  nemo_toolkit[all]"

**Comment by borisfom** [comment]
Another, probably more practical rule to follow: at least from Nemo 1.7 up, you should be able to install nemo2riva wheel and use it successfully from wherever you are currently successfully running NeMo (which means you can at least successfully restore your networks of interest from .nemo and export them, e.g by using NeMo's own scripts/export.py).

**Comment by titu1994** [comment]
@piraka9011 how was this Nemo model trained and then saved ? The fact that not even Nemo can restore it is odd - we inject target into the config automatically since the release candidate of Nemo, so there should be no reason that target didn't exist in the Nemo model config v

**Comment by piraka9011** [comment]
The model was trained by finetuning a `stt_en_citrinet_1024` model.
It seems that the original model when downloaded from ngc has the `target` key but after training, that key is not saved.

**Comment by titu1994** [comment]
Target is injected by the constructor - if the entire model.cfg is replaced this will happen.

**Comment by piraka9011** [comment]
I see... in my training script, I do:

```py
...
model_class = model_utils.import_class_by_path(cfg.model_target)
asr_model = model_class.from_pretrained(model_name=cfg.init_from_pretrained_model)
asr_model.cfg = cfg.model   # Overwrites cfg?
asr_model.set_trainer(trainer)
...
```

It seems that third line overwrites the model's cfg.

**Comment by piraka9011** [comment]
Confirmed that removing that line solves the issue...

Sorry for the false alarm and thanks for the feedback!
