### ISSUE TITLE
the "FastPitch Duration and Pitch Control" tutorial doesn't work

### ISSUE THREAD

**Issue by anchpop** [NVIDIA/NeMo#3910]
**Describe the bug**

when running the second cell of [Inference_DurationPitchControl.ipynb](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/tts/Inference_DurationPitchControl.ipynb#scrollTo=Om8Q6noETUxt) in colab, I get

```
[NeMo E 2022-03-30 19:30:51 vocabs:325] Torch distributed needs to be initialized before you initialized <nemo.collections.common.data.vocabs.Phonemes object at 0x7ff436821290>. This class is prone to data access race conditions. Now downloading corpora from global rank 0. If other ranks pass this before rank 0, errors might result.
[NeMo E 2022-03-30 19:30:53 vocabs:325] Torch distributed needs to be initialized before you initialized <nemo.collections.common.data.vocabs.Phonemes object at 0x7ff42eb93410>. This class is prone to data access race conditions. Now downloading corpora from global rank 0. If other ranks pass this before rank 0, errors might result.
[NeMo E 2022-03-30 19:30:55 common:480] Model instantiation failed!
    Target class:	nemo.collections.tts.models.fastpitch.FastPitchModel
    Error(s):	dump_all() got an unexpected keyword argument 'sort_keys'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/nemo/core/classes/common.py", line 459, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 83, in __init__
        super().__init__(cfg=cfg, trainer=trainer)
      File "/usr/local/lib/python3.7/dist-packages/nemo/core/classes/modelPT.py", line 149, in __init__
        f"If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method "
      File "/usr/local/lib/python3.7/dist-packages/omegaconf/omegaconf.py", line 774, in to_yaml
        Dumper=get_omega_conf_dumper(),
      File "/usr/local/lib/python3.7/dist-packages/yaml/__init__.py", line 200, in dump
        """
    TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
    
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-27feb807c5d3>](https://localhost:8080/#) in <module>()
     17 
     18 # Load the models from NGC
---> 19 fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch").eval().cuda()
     20 hifigan = HifiGanModel.from_pretrained("tts_hifigan").eval().cuda()
     21 sr = 22050

8 frames
[/usr/local/lib/python3.7/dist-packages/yaml/__init__.py](https://localhost:8080/#) in dump(data, stream, Dumper, **kwds)
    198     Emit YAML parsing events into a stream.
    199     If stream is None, return the produced string instead.
--> 200     """
    201     getvalue = None
    202     if stream is None:

TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
```

**Steps/Code to reproduce bug**

1. Open [Inference_DurationPitchControl.ipynb](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/tts/Inference_DurationPitchControl.ipynb#scrollTo=Om8Q6noETUxt) in Colab
2. Change runtime type to "GPU"
3. Run cell 1
4. Run cell 2

**Expected behavior**

Cell should run without errors or warnings

**Environment overview (please complete the following information)**

 - Environment location: Colab
 - Method of NeMo install: `!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]`

**Comment by redoctopus** [comment]
I'm unable to reproduce this bug with the link and steps given, everything is running fine on my end. Was there anything else that was changed?

**Comment by anchpop** [comment]
@redoctopus it seems to work, not sure why I was having trouble before
