### ISSUE TITLE
FastPitch_MixerTTS_Training tutorial not working on Colab

### ISSUE THREAD

**Issue by simsax** [NVIDIA/NeMo#3961]
**Describe the bug**

The function `pre_calculate_supplementary_data` fails when running _FastPitch_MixerTTS_Training.ipynb_ on Colab.

**Steps/Code to reproduce bug**

Open https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_MixerTTS_Training.ipynb on Colab, then run all the cells. It should fail here:
```
fastpitch_sup_data_path = "fastpitch_sup_data_folder"
sup_data_types = ["align_prior_matrix", "pitch"]

pitch_mean, pitch_std, pitch_min, pitch_max = pre_calculate_supplementary_data(
    fastpitch_sup_data_path, sup_data_types, text_tokenizer, text_normalizer, text_normalizer_call_kwargs
)
```
This is the output
```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/torch/data.py", line 447, in __getitem__
    align_prior_matrix = beta_binomial_prior_distribution(text_length, mel_len)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/torch/helpers.py", line 57, in beta_binomial_prior_distribution
    mel_i_prob = betabinom(phoneme_count, a, b).pmf(x)
  File "/usr/local/lib/python3.7/dist-packages/scipy/stats/_distn_infrastructure.py", line 495, in pmf
    return self.dist.pmf(k, *self.args, **self.kwds)
  File "/usr/local/lib/python3.7/dist-packages/scipy/stats/_distn_infrastructure.py", line 2997, in pmf
    cond1 = (k >= _a) & (k <= _b) & self._nonzero(k, *args)
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'Tensor'
```

**Expected behavior**

I expect it to work

**Environment overview (please complete the following information)**

 - Environment location: Google Colab

**Environment details**

- PyTorch version 1.10.0+cu111
- Python version 3.7.13

**Comment by redoctopus** [comment]
PR #3967 should fix this for the next release. In the meantime, you can also manually add a pinned `scipy==1.7.3` install to fix it locally.
