### ISSUE TITLE
Problem with speaker diarization using long audios

### ISSUE THREAD

**Issue by yogso** [NVIDIA/NeMo#4051]
Good morning, 

Thank you very much for your excellent repository. 

I am having problems when I want to use Nemo for speaker diarization with "long" audios, could you please help me to make it work correctly?.

The error is the following:

```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/data/audio_to_label.py", line 420, in vad_frame_seq_collate_fn
    return _vad_frame_seq_collate_fn(self, batch)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/data/audio_to_label.py", line 194, in _vad_frame_seq_collate_fn
    audio_signal = torch.stack(audio_signal)
RuntimeError: stack expects a non-empty TensorList
```

I leave an example of the code to reproduce the error:

https://colab.research.google.com/drive/1DnrIBrqaBiIZX-nPcoEMg3jrEGFR1zWF?usp=sharing

And one of the audios I am testing with:

https://drive.google.com/file/d/1eyzfzLh7u_xo3pzkGJ_GqYx38nukolrR/view?usp=sharing

Thank you very much for your time

**Comment by nithinraok** [comment]
Hi @yogso, Thanks much for the detailed issue info. 

The audio you provided is sampled at 44.1Khz, downsample it to 16Khz then try again.

**Comment by yogso** [comment]
Hi @nithinraok, thank you very much for your help, it works perfectly now!

Greetings
