### ISSUE TITLE
Unable to run Fastpitch_finetuning.ipynb version main from scratch

### ISSUE THREAD

**Issue by gedefet** [NVIDIA/NeMo#4076]
Hi, I'm trying to run FastPitch_finetuning.ipynb from scratch, but I'm getting this error:

```
# TODO(oktai15): remove +model.text_tokenizer.add_blank_at=true when we update FastPitch checkpoint
!(python fastpitch_finetune.py --config-name=fastpitch_align_v1.05.yaml \
  train_dataset=./6097_manifest_train_dur_5_mins_local.json \
  validation_datasets=./6097_manifest_dev_ns_all_local.json \
  sup_data_path=./fastpitch_sup_data \
  phoneme_dict_path=tts_dataset_files/cmudict-0.7b_nv22.01 \
  heteronyms_path=tts_dataset_files/heteronyms-030921 \
  whitelist_path=tts_dataset_files/whitelist_lj_speech.tsv \
  exp_manager.exp_dir=./ljspeech_to_6097_no_mixing_5_mins \
  +init_from_nemo_model=./tts_en_fastpitch_align.nemo \
  +trainer.max_steps=1000 ~trainer.max_epochs \
  trainer.check_val_every_n_epoch=25 \
  model.train_ds.dataloader_params.batch_size=24 model.validation_ds.dataloader_params.batch_size=24 \
  model.n_speakers=1 model.pitch_mean=121.9 model.pitch_std=23.1 \
  model.pitch_fmin=30 model.pitch_fmax=512 model.optim.lr=2e-4 \
  ~model.optim.sched model.optim.name=adam trainer.devices=1 trainer.strategy=null \
  +model.text_tokenizer.add_blank_at=true \
)
```
And the error:
```
Error executing job with overrides: ['train_dataset=./6097_manifest_train_dur_5_mins_local.json', 'validation_datasets=./6097_manifest_dev_ns_all_local.json', 'sup_data_path=./fastpitch_sup_data', 'phoneme_dict_path=tts_dataset_files/cmudict-0.7b_nv22.01', 'heteronyms_path=tts_dataset_files/heteronyms-030921', 'whitelist_path=tts_dataset_files/whitelist_lj_speech.tsv', 'exp_manager.exp_dir=./ljspeech_to_6097_no_mixing_5_mins', '+init_from_nemo_model=./tts_en_fastpitch_align.nemo', '+trainer.max_steps=1000', '~trainer.max_epochs', 'trainer.check_val_every_n_epoch=25', 'model.train_ds.dataloader_params.batch_size=24', 'model.validation_ds.dataloader_params.batch_size=24', 'model.n_speakers=1', 'model.pitch_mean=121.9', 'model.pitch_std=23.1', 'model.pitch_fmin=30', 'model.pitch_fmax=512', 'model.optim.lr=2e-4', '~model.optim.sched', 'model.optim.name=adam', 'trainer.devices=1', 'trainer.strategy=null', '+model.text_tokenizer.add_blank_at=true']
Traceback (most recent call last):
  File "fastpitch_finetune.py", line 32, in main
    model = FastPitchModel(cfg=cfg.model, trainer=trainer)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 84, in __init__
    self._setup_normalizer(cfg)
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/tts/models/fastpitch.py", line 166, in _setup_normalizer
    'text_normalizer.whitelist', cfg.text_normalizer.whitelist
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/classes/modelPT.py", line 220, in register_artifact
    return self._save_restore_connector.register_artifact(self, config_path, src, verify_src_exists)
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/connectors/save_restore_connector.py", line 345, in register_artifact
    f"src path does not exist or it is not a path in nemo file. src value I got was: {src}. Absolute: {os.path.abspath(src)}"
FileNotFoundError: src path does not exist or it is not a path in nemo file. src value I got was: tts_dataset_files/whitelist_lj_speech.tsv. Absolute: /content/tts_dataset_files/whitelist_lj_speech.tsv
```

Thanks in advance

**Comment by redoctopus** [comment]
It can't find the LJSpeech whitelist file that you've passed in as `whitelist_path=tts_dataset_files/whitelist_lj_speech.tsv`.

The file can be found here: https://github.com/NVIDIA/NeMo/blob/main/nemo_text_processing/text_normalization/en/data/whitelist/lj_speech.tsv

As a side note, it looks like the file was recently renamed. I'll update the tutorial to reflect the new name.
