### ISSUE TITLE
Fine-tuning Conformer with Persian language

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [NVIDIA/NeMo#4129]
Hi, would you please share with me a collab notebook file for fine-tuning conformer_ctc_bpe? I want to use it for the Persian language. when I use the` ASR_CTC_Language_Finetuning.ipynb` notebook I got the desired result with all Citrinet models, but I can not use this notebook file for any of the CTC Conformer models. For example when I use `stt_en_conformer_ctc_large` model in the following part `results = analyse_ctc_failures_in_model(model)` I have this error:

`
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.7/dist-packages/webdataset/iterators.py", line 226, in map
    for sample in data:
  File "/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/data/audio_to_text.py", line 671, in __next__
    audio_bytes, audio_filename = next(self.iterator)
  File "/usr/local/lib/python3.7/dist-packages/webdataset/iterators.py", line 282, in to_tuple
    for sample in data:
  File "/usr/local/lib/python3.7/dist-packages/webdataset/iterators.py", line 240, in rename
    for sample in data:
  File "/usr/local/lib/python3.7/dist-packages/webdataset/iterators.py", line 187, in shuffle
    for sample in data:
  File "/usr/local/lib/python3.7/dist-packages/webdataset/tariterators.py", line 153, in group_by_keys
    for fname, value in data:
  File "/usr/local/lib/python3.7/dist-packages/webdataset/tariterators.py", line 131, in tar_file_expander
    for source in data:
  File "/usr/local/lib/python3.7/dist-packages/webdataset/tariterators.py", line 86, in url_opener
    if handler(exn):
  File "/usr/local/lib/python3.7/dist-packages/webdataset/utils.py", line 12, in reraise_exception
    raise exn
  File "/usr/local/lib/python3.7/dist-packages/webdataset/tariterators.py", line 82, in url_opener
    stream = gopen.gopen(sample["url"], **kw)
  File "/usr/local/lib/python3.7/dist-packages/webdataset/gopen.py", line 192, in gopen
    return open(url, mode, buffering=bufsize)
FileNotFoundError: [Errno 2] No such file or directory: '/data/NeMo_ASR_SET/English/v2.0/train/audio_2568.tar'
`

How should I solve this error?

Thanks

**Comment by VahidooX** [comment]
This method would try to pass all the train data through the model and check if the CTC loss fails on any of the sample or not. You may just ignore this part of the tutorial for the pretrained models as it is not crucial. But if you want to make it work, you need to set cfg.train_ds.is_tarred=false in the previous section where it sets the data loaders. You may also set is_tarred=false for the test and validation.

**Comment by titu1994** [comment]
@VahidooX let's develop a model config cleaning script based off of the asr Adapters example of config merging so that such issues don't pop up in newer checkpoints.
