### ISSUE TITLE
ImportError: Could not compile megatron dataset C++ helper functions in Synthetic tabular data turorial

### ISSUE THREAD

**Issue by leoqzm** [NVIDIA/NeMo#4546]
**Describe the bug**
In NeMo/tutorials/nlp/Megatron_Synthetic_Tabular_Data_Generation.ipynb notebook, when I wanted to run it in Google Colab, the ImportError occurs. And I am not sure what package should I install to resolve this error.

**Steps/Code to reproduce bug**

It occurs in this step: ( I got the main branch of the NeMo, and follow the steps in notebook)
```
!python megatron_gpt_pretraining.py \
        trainer.devices={NUM_GPUS} \
        trainer.accelerator=gpu \
        trainer.log_every_n_steps=100 \
        trainer.val_check_interval=500 \
        trainer.accumulate_grad_batches=1 \
        trainer.max_steps=10000 \
        trainer.precision=16 \
        trainer.gradient_clip_val=1.0 \
        exp_manager.exp_dir=gpt_creditcard_results \
        model.tensor_model_parallel_size={TENSOR_MP_SIZE} \
        model.pipeline_model_parallel_size={PIPELINE_MP_SIZE} \
        model.optim.name=fused_adam \
        model.optim.lr=2e-4 \
        model.optim.sched.warmup_steps=2 \
        model.optim.sched.constant_steps=2 \
        model.optim.sched.min_lr=8e-5 \
        model.max_position_embeddings={SEQ_LENGTH} \
        model.encoder_seq_length={SEQ_LENGTH} \
        model.data.seq_length={SEQ_LENGTH} \
        model.tokenizer.type=Tabular \
        model.tokenizer.library=tabular \
        model.tokenizer.vocab_file={CC_OUTPUT_P} \
        model.tokenizer.delimiter=\',\' \
        model.data.eod_mask_loss=True \
        model.data.splits_string=\'3800,198,2\' \
        model.num_layers={NUM_LAYERS} \
        model.hidden_size={HIDDEN_SIZE} \
        model.num_attention_heads={NUM_ATTENTION_HEADS} \
        model.activations_checkpoint_method=\'block\' \
        model.activations_checkpoint_num_layers=1 \
        model.data.data_prefix=[tabular_data_text_document]
```

**Comment by yidong72** [comment]
Could you try it locally in your container instead of Colab? I don't think Colab has enough compute resource to train a GPT.

**Comment by leoqzm** [comment]
> 

Thank you Dr. Dong, and I solve this problem by running it on google cloud. However, I am facing a new problem in the inference session.  Could you please response this comment as soon as possible, because we will have a coming up meeting. very appreciate for that.

After I run the 
```python megatron_gpt_eval.py \
    gpt_model_file=tabular.nemo \
    prompts=[\'\',\'\'] \
    server=True
```

The server works normal, but when I run 
```
with open(CC_OUTPUT_P, 'rb') as handle:
        cc: ColumnCodes = pickle.load(handle)

batch_size = 4
num_of_rows = 50
token_per_rows = sum(cc.sizes) + 1
history_rows = 40
num_of_blocks = 100

port_num = 5555
headers = {"Content-Type": "application/json"}

prefix_name = 'synthetic'
files = []


for i in range(batch_size):
    files.append(open("{}_{}.txt".format(prefix_name, i), 'w'))


def request_data(data):
    resp = requests.put('http://localhost:{}/generate'.format(port_num),
                        data=json.dumps(data), headers=headers)
    sentences = resp.json()['sentences']
    return sentences


def get_condition_text(sentences, history_rows):
    condition_text = ['\n'.join([ss for ss in s.split(
        '\n')[-(history_rows+1):]]) for s in sentences]
    return condition_text


def get_extra_text(sentences, history_rows):
    extra_text = ['\n'.join([ss for ss in s.split(
        '\n')[history_rows:]]) for s in sentences]
    return extra_text

# generate the inital transactions 
data = {
    "sentences": [""] * batch_size,
    "tokens_to_generate": num_of_rows * token_per_rows,
    "temperature": 1.0,
    "add_BOS": True
}

sentences = request_data(data)

for i in range(batch_size):
    s = sentences[i]
    files[i].write(s.replace('<|endoftext|>', '\n'))

# generate the transactions conditioned on the previous ones
for block in range(num_of_blocks):
    print("block id: {}".format(block))
    condition_text = get_condition_text(sentences, history_rows)
    data = {
        "sentences": condition_text,
        "tokens_to_generate": num_of_rows * token_per_rows,
        "temperature": 1.0,
        "add_BOS": False
    }

    sentences = request_data(data)

    extra_text = get_extra_text(sentences, history_rows)

    for i in range(batch_size):
        s = extra_text[i]
        files[i].write(s.replace('<|endoftext|>', '\n---------------\n'))
        files[i].flush()


for i in range(batch_size):
    files[i].close()
```
Which my input is 
```
['<|endoftext|>2009,8,5,2009,8,5,2009,8,5,0,0,0,1,0,0,0,0.00000000,DuPage County  Illinois,0.39999999,0.01146859,DuPage,0,0,0,0,0.02411849,0,0,0.00000000,0.00320100,0.00000000,0,0,0,33142.58795002,0,0,38.51639122,0.01263096,0,0,0.00001790,0.04483753,23535.01899925,0,IL,0.00000000,0,0.00027097,ILLINOIS,0.00000000,0.00514994,0.00000000,0.18736810,0.00000000,0.00000000,505.19999700,0,0,0.00000000,0.20474800,0,0.00000000,0,112.99999799,0.70947094,1564.99998712,0,0.00000000,0,6.44739868,0.14987446,0,0,0,7.09999984,0,0,0.00000000,0.02450772,0.00000000,0.62586532,0.03907797,0,0.00000000,0.08629999,0.00000000,0.00639999,20,0,0,0,0.00724985,5.88235274,0,0.00064839,34.50950248,0,0.00000000,0.00000000,0.43256712,0.00094952,0,0.00478976,0.00000000,0.19999999,0.21915005,0.00000430,0\n2009,9,20,2009,9,20,2009,9,20,0,0,0,1,0,0,0,0.00000000,DuPage County  Illinois,0.39999999,0.01146859,DuPage,0,0,0,0,0.02411849,0,0,0.00000000,0.00320100,0.00000000,0,0,0,33142.58795002,0,0,38.51639122,0.01263096,0,0,0.00001790,0.04483753,23535.01899925,0,IL,0.00000000,0,0.00027097,ILLINOIS,0.00000000,0.00514994,0.00000000,0.18736810,0.00000000,0.00000000,505.19999700,0,0,0.00000000,0.20474800,0,0.00000000,0,112.99999799,0.70947094,1564.99998712,0']
```
, I first face the tokenizer encoder issues with this error log:
```
Exception on /generate [PUT]
Traceback (most recent call last):
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/nlp/modules/common/text_generation_server.py", line 147, in put
    output = generate(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/nlp/modules/common/text_generation_utils.py", line 445, in generate
    context_tokens_tensor, context_length_tensor = tokenize_batch(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/nlp/modules/common/text_generation_utils.py", line 232, in tokenize_batch
    context_tokens = [tokenizer.text_to_ids(s) for s in sentences]
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/nlp/modules/common/text_generation_utils.py", line 232, in <listcomp>
    context_tokens = [tokenizer.text_to_ids(s) for s in sentences]
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/common/tokenizers/tabular_tokenizer.py", line 61, in text_to_ids
    return self.encode(text)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/common/tokenizers/tabular_tokenizer.py", line 175, in encode
    return self.tokens_to_ids(self.text_to_tokens(text))
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/common/tokenizers/tabular_tokenizer.py", line 132, in tokens_to_ids
    ids.extend(self.code_column.encode(column, token))
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/common/tokenizers/column_coder.py", line 277, in encode
    return self.column_codes[col].encode(item)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/nemo/collections/common/tokenizers/column_coder.py", line 149, in encode
    raise ValueError("not right length")
ValueError: not right length
```
Which I think is the '<|endoftext|>' cause the issue for the tokenizer. So I delete the '<|endoftext|>' at first of the every input sentences.
However, then the ```get_extra_text(sentences, history_rows)``` function only have empty list output.
So Dr. Dong, could you please help me to solve this issues?
Thank you so much.
Best

**Comment by Liuzirui666** [comment]
> [@leoqzm](https://github.com/leoqzm) I was trying to reproduce the synthetic data notebook, while using `TabularTokenizer` I also faced the issue of `not right length`, this happens because of `code_len` while configuring `tab_structure`, I solved this by increasing the value of `code_len` and it solved that issue, if you have solved this then I am writing here for documenting the solution to this problem.

Can you explain more in detail about this?
