### ISSUE TITLE
loss equals to nan when I use rir and noise augmentor

### ISSUE THREAD

**Issue by ZurabDz** [NVIDIA/NeMo#4549]
this one was closed but bug is not fixed and I have no idea where should I add a check for nan.

https://github.com/NVIDIA/NeMo/issues/2246

Basically this issue, I am trying to train conformer-char with rir

**Comment by ZurabDz** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1646, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 286, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 85, in optimizer_step
    closure_result = closure()
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 143, in closure
    self._backward_fn(step_output.closure_loss)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 311, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1765, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 168, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, *args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1391, in backward
    loss.backward(*args, **kwargs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/.conda/envs/nemo_env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'AddmmBackward0' returned nan values in its 2th output.

```

well, now the error seems like this.  Could you please tell me which file should I handle my data? I am new to Nemo ;(

**Comment by titu1994** [comment]
I dunno what your data is, I'd suggest preprocessing all the files to 1' channel 16khz using ffmpeg and then try using small subsets of all your data to try and augment your model. It's probably your data is corrupted or has similar issue as on the previous thread so there's not much I can help with

**Comment by ZurabDz** [comment]
ok, so for formatting data I used FFmpeg -ar -ac flags. I double-checked and it's 1 channel 16khz. I don't think data is corrupted(if by corrupted we mean non-audible or something like that). Assuming I have a similar issue as in the previous thread, how should I proceed?

**Comment by titu1994** [comment]
Write a script looping through your files, load it and pass it to the model preprocessors and check if output is nan or not. Or just use a small set of audio files first and check if it causes NAN or not, and keep adding your audio until it no longer crashes due to nabc

**Comment by ZurabDz** [comment]
Oh yeah I am a moron sorry, I will do that

**Comment by titu1994** [comment]
No worries hope it works. I'm closing this for now since the resolution is on the data side
