### ISSUE TITLE
Which NeMo Docker Container is working good

### ISSUE THREAD

**Issue by Shaiken** [NVIDIA/NeMo#4727]
i use nvcr.io/nvidia/nemo:22.05, and git master

try test .py

test .py code content only

import nemo.collections.asr as nemo_asr

had a error about

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import nemo.collections.asr as nemo_asr
  File "/code/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/code/nemo/collections/asr/models/__init__.py", line 16, in <module>
    from nemo.collections.asr.models.classification_models import EncDecClassificationModel
  File "/code/nemo/collections/asr/models/classification_models.py", line 27, in <module>
    from pytorch_lightning.metrics.regression import MeanAbsoluteError, MeanSquaredError
ModuleNotFoundError: No module named 'pytorch_lightning.metrics'
```
i try install pip install pytorch-lightning==1.2.2

had another error about
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import nemo.collections.asr as nemo_asr
  File "/code/nemo/collections/asr/__init__.py", line 15, in <module>
    from nemo.collections.asr import data, losses, models, modules
  File "/code/nemo/collections/asr/models/__init__.py", line 16, in <module>
    from nemo.collections.asr.models.classification_models import EncDecClassificationModel
  File "/code/nemo/collections/asr/models/classification_models.py", line 31, in <module>
    from nemo.collections.asr.parts.features import WaveformFeaturizer
  File "/code/nemo/collections/asr/parts/features.py", line 44, in <module>
    from torch_stft import STFT
ModuleNotFoundError: No module named 'torch_stft'
```

i try install pip install torch-stft

now is work, but I don't know if there will be the next problem

**Comment by Shaiken** [comment]
不急的答案
