### ISSUE TITLE
Conformer Transducer - Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by shahin-trunk** [NVIDIA/NeMo#4882]
**Describe the bug**

Error while training conformer transducer bpe ASR model.

**Steps/Code to reproduce bug**
Use the attached config and initiate the training. After a few steps before epoch completion the following 
`Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE` error occurs and the training get stopped.

`Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
Error executing job with overrides: []
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt_pytorch.py", line 174, in forward
    return self.loss(
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt_pytorch.py", line 64, in forward
    loss_func(
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/rnnt.py", line 223, in rnnt_loss_gpu
    status = wrapper.cost_and_grad(
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/utils/cuda_utils/gpu_rnnt.py", line 249, in cost_and_grad
    return self.compute_cost_and_score(acts, grads, costs, pad_labels, label_lengths, input_lengths)
  File "/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/numba/rnnt_loss/utils/cuda_utils/gpu_rnnt.py", line 161, in compute_cost_and_score
    gpu_rnnt_kernel.compute_alphas_kernel[self.minibatch_, self.maxU_, self.stream_, 0](
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 729, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 919, in call
    kernel.launch(args, griddim, blockdim, stream, sharedmem)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/compiler.py", line 576, in launch
    driver.launch_kernel(cufunc.handle,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 2550, in launch_kernel
    driver.cuLaunchKernel(cufunc_handle,
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 319, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/opt/conda/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 387, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
`
**Expected behavior**

Run training without any error.

**Environment overview (please complete the following information)**

 - SLURM Managed cluster
 - DGX-1 8x V100 GPU
 - Singularity environment - nvcr.io/nvidia/nemo:22.05

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**
DGX-1 8x V100 GPU x 4 Nodes
**Training Config**
[cmr_en_rnnt_v2_n4.txt](https://github.com/NVIDIA/NeMo/files/9497280/cmr_en_rnnt_v2_n4.txt)

**Comment by titu1994** [comment]
What length is your target sequence length? I think it fails the kernel launch cause there's more than 1024 tokens in the U dimension, and thats the maximum number of threads in cuda 11 for a kernel launch

**Comment by shahin-trunk** [comment]
It is working. Thanks @titu1994. As always you are the best.
I put a filter across my datasets and discarded the samples with number of tokens > 1024.
