### ISSUE TITLE
AttributeError: type object 'LightningModule' has no attribute 'trainer'

### ISSUE THREAD

**Issue by chensuo2048** [NVIDIA/NeMo#5017]
/opt/miniconda3/envs/nemo/bin/python /home/henry/Projects/NeMo/nemo_text_processing/text_normalization/normalize.py --lang zh --text 最高气温38°C
[NeMo W 2022-09-27 17:45:38 optimizers:55] Apex was not found. Using the lamb or fused_adam optimizer will error out.
Traceback (most recent call last):
  File "/home/henry/Projects/NeMo/nemo_text_processing/text_normalization/normalize.py", line 38, in <module>
    from nemo.collections.common.tokenizers.moses_tokenizers import MosesProcessor
  File "/home/henry/Projects/NeMo/nemo/collections/common/__init__.py", line 16, in <module>
    from nemo.collections.common import data, losses, parts, tokenizers
  File "/home/henry/Projects/NeMo/nemo/collections/common/losses/__init__.py", line 15, in <module>
    from nemo.collections.common.losses.aggregator import AggregatorLoss
  File "/home/henry/Projects/NeMo/nemo/collections/common/losses/aggregator.py", line 19, in <module>
    from nemo.core.classes import Loss, typecheck
  File "/home/henry/Projects/NeMo/nemo/core/__init__.py", line 16, in <module>
    from nemo.core.classes import *
  File "/home/henry/Projects/NeMo/nemo/core/classes/__init__.py", line 33, in <module>
    from nemo.core.classes.modelPT import ModelPT
  File "/home/henry/Projects/NeMo/nemo/core/classes/modelPT.py", line 43, in <module>
    class ModelPT(LightningModule, Model):
  File "/home/henry/Projects/NeMo/nemo/core/classes/modelPT.py", line 1374, in ModelPT
    @LightningModule.trainer.getter
AttributeError: type object 'LightningModule' has no attribute 'trainer'

**Comment by chensuo2048** [comment]
Hello, can anyone help me solve this issue?

**Comment by SeanNaren** [comment]
Am able to run this locally, I suspect this could be a lightning version issue. What version of lightning are you using? Could you try upgrading this version to see if this fixes the issue?

**Comment by chensuo2048** [comment]
> Am able to run this locally, I suspect this could be a lightning version issue. What version of lightning are you using? Could you try upgrading this version to see if this fixes the issue?

Thanks! I have upgrade lighting to 1.7.7, now it works～
