### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kinfey** [NVIDIA/NeMo#5282]
I try to install from gihub repo

but it always show me 

 command: /anaconda/envs/azureml_py38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"/NeMo/setup.py'"'"'; __file__='"'"'/NeMo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/batch/tasks/shared/LS_root/mounts/clusters/k80gpu/code/Users/lokinfey/NeMo/
    Complete output (44 lines):
    running develop
    /anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/k80gpu/code/Users/lokinfey/NeMo/setup.py", line 209, in <module>
        setuptools.setup(
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/dist.py", line 984, in run_command
        cmd_obj.ensure_finalized()
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 268, in finalize_options
        self._expand(
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1344, in _expand
        config_vars = self.get_finalized_command('install').config_vars
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/command/install.py", line 45, in finalize_options
        orig.install.finalize_options(self)
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/command/install.py", line 366, in finalize_options
        self.set_undefined_options('build',
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
        src_cmd_obj = self.distribution.get_command_obj(src_cmd)
      File "/anaconda/envs/azureml_py38/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/setuptools/dist.py", line 890, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in load
        return self.resolve()
      File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'setuptools.command.build'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda/envs/azureml_py38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/batch/tasks/shared/LS_root/mounts/clusters/k80gpu/code/Users/lokinfey/NeMo/setup.py'"'"'; __file__='"'"'/mnt/batch/tasks/shared/LS_root/mounts/clusters/k80gpu/code/Users/lokinfey/NeMo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

can you  help me

**Comment by titu1994** [comment]
We don't support easy_install - only pip. 
Please follow the setup instructions here or on the GitHub readme page - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

**Comment by kinfey** [comment]
but I try to insall with pip , and then show me this error

![Screenshot 2022-10-30 at 15 58 49](https://user-images.githubusercontent.com/93169410/198868450-46df27b1-416e-4a28-ab24-2a1a8a0c5dd5.png)

**Comment by titu1994** [comment]
Use python 3.9 if possible, or follow these steps if for some reason python 3.9 is not possible - https://github.com/NVIDIA/NeMo/issues/4800#issuecomment-1259819917

Note that 3.9 is the recommended python version for NeMo.
