### ISSUE TITLE
Training stuck for a long time

### ISSUE THREAD

**Issue by Johnson-NLP** [NVIDIA/NeMo#5536]
I try to train a Squeezeformer ASR model with speech_to_text_ctc_bpe.py. But the train log stucks for quite a long time after showing the "Total estimated model params size (MB)" ,without giving any error or training information. My GPUs keep 100% occupation as well. How to deal with this problem?

**Comment by titu1994** [comment]
Possibly just caused due to ddp desyncing. Use killall -9 python to be sure no ddp process is active before launching the run.

**Comment by Johnson-NLP** [comment]
I found the solution in a similar issue #1247. Due to low Nemo_toolkit version, the training will stuck for multi-GPU mode. I update the toolkit version and problem fixed. Issue closed.

**Comment by hellangleZ** [comment]
> I found the solution in a similar issue #1247. Due to low Nemo_toolkit version, the training will stuck for multi-GPU mode. I update the toolkit version and problem fixed. Issue closed.

Hi what is the toolkit version? how to change it ?  I use 24.05 docker ,but still has this problem

**Comment by titu1994** [comment]
Can you try - nvcr.io/nvidia/nemo:24.05.01

**Comment by hellangleZ** [comment]
> Can you try - nvcr.io/nvidia/nemo:24.05.01

even I use 24.05.01， still stuck in this status

![image](https://github.com/user-attachments/assets/37a28c81-32fc-49a2-b3b9-bf20c53fa788)

**Comment by hellangleZ** [comment]
> Can you try - nvcr.io/nvidia/nemo:24.05.01

use another sft script which refer by official document is also not work by this error

https://docs.nvidia.com/nemo-framework/user-guide/latest/modelalignment/sft.html#step-2-sft-training


Traceback (most recent call last):
  File "/opt/NeMo-Aligner/examples/nlp/gpt/train_gpt_sft.py", line 243, in <module>
    main()
  File "/opt/NeMo/nemo/core/config/hydra_runner.py", line 129, in wrapper
    _run_hydra(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/opt/NeMo-Aligner/examples/nlp/gpt/train_gpt_sft.py", line 129, in main
    ptl_model, updated_cfg = load_from_nemo(
  File "/opt/NeMo-Aligner/nemo_aligner/utils/utils.py", line 98, in load_from_nemo
    model = cls.restore_from(
  File "/opt/NeMo/nemo/collections/nlp/models/nlp_model.py", line 465, in restore_from
    return super().restore_from(
  File "/opt/NeMo/nemo/core/classes/modelPT.py", line 464, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/opt/NeMo-Aligner/nemo_aligner/utils/utils.py", line 51, in restore_from
    return super().restore_from(*args, **kwargs)
  File "/opt/NeMo/nemo/collections/nlp/parts/nlp_overrides.py", line 1172, in restore_from
    checkpoint = checkpoint_io.load_checkpoint(tmp_model_weights_dir, sharded_state_dict=checkpoint)
  File "/opt/NeMo/nemo/utils/callbacks/dist_ckpt_io.py", line 78, in load_checkpoint
    return dist_checkpointing.load(
  File "/opt/megatron-lm/megatron/core/dist_checkpointing/serialization.py", line 133, in load
    validate_sharding_integrity(nested_values(sharded_state_dict))
  File "/opt/megatron-lm/megatron/core/dist_checkpointing/serialization.py", line 425, in validate_sharding_integrity
    torch.distributed.all_gather_object(all_sharding, sharding)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2310, in all_gather_object
    all_gather(object_size_list, local_size, group=group)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2724, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
torch.distributed.DistBackendError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1961, internal error - please report this issue to the NCCL developers, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
Attribute busid of node nic not found****

**Comment by titu1994** [comment]
That script is for LLM, not ASR models. 

ASR seems to be working fine with that container for our usage, we are doing experiments with it daily. Are you working on ASR task or llm task ? LLM task should open another issue since it's unrelated to ASR domain.

**Comment by hellangleZ** [comment]
> That script is for LLM, not ASR models.
> 
> ASR seems to be working fine with that container for our usage, we are doing experiments with it daily. Are you working on ASR task or llm task ? LLM task should open another issue since it's unrelated to ASR domain.

LLM , OK understand , so NEMO only for ASR domain, right?

**Comment by titu1994** [comment]
No, it's for all speech and LLM tasks, but this is an ASR related issue originally. Please create a separate issue for LLM
