### ISSUE TITLE
Pretraining argument for tokenizer

### ISSUE THREAD

**Issue by pradeepsinghnitk** [NVIDIA/NeMo#5751]
" ${model.language_model.pretrained_model_name} # tokenizer that inherits from TokenizerSpec"
AttributeError: 'BERTLMModel' object has no attribute 'tokenizer'

**Comment by pradeepsinghnitk** [comment]
[NeMo I 2023-01-12 06:41:36 bert_pretraining:28] Config:
     name: PretrainingBERTFromText
    trainer:
      devices: 8
      num_nodes: 1
      max_steps: 7000
      accumulate_grad_batches: 1
      precision: 16
      accelerator: gpu
      gradient_clip_val: 0.0
      log_every_n_steps: 1
      val_check_interval: 1.0
      enable_checkpointing: false
      logger: false
    model:
      nemo_path: /NeMo/output/
      only_mlm_loss: true
      num_tok_classification_layers: 1
      num_seq_classification_layers: 2
      max_seq_length: 128
      mask_prob: 0.15
      short_seq_prob: 0.1
      language_model:
        pretrained_model_name: bert-base-uncased
        lm_checkpoint: null
        config:
          attention_probs_dropout_prob: 0.1
          hidden_act: gelu
          hidden_dropout_prob: 0.1
          hidden_size: 768
          initializer_range: 0.02
          intermediate_size: 3072
          max_position_embeddings: 512
          num_attention_heads: 12
          num_hidden_layers: 12
          type_vocab_size: 2
          vocab_size: 30522
        config_file: null
      tokenizer:
        tokenizer_name: ${model.language_model.pretrained_model_name}
        vocab_file: null
        tokenizer_model: null
        special_tokens:
          unk_token: '[UNK]'
          sep_token: '[SEP]'
          pad_token: '[PAD]'
          bos_token: '[CLS]'
          mask_token: '[MASK]'
          eos_token: '[SEP]'
          cls_token: '[CLS]'
      train_ds:
        data_file: /NeMo/train_5percent.txt
        max_seq_length: ${model.max_seq_length}
        mask_prob: ${model.mask_prob}
        short_seq_prob: ${model.short_seq_prob}
        batch_size: 16
        shuffle: true
        num_samples: -1
        num_workers: 2
        drop_last: false
        pin_memory: false
      validation_ds:
        data_file: /NeMo/seen_samples.txt
        max_seq_length: ${model.max_seq_length}
        mask_prob: ${model.mask_prob}
        short_seq_prob: ${model.short_seq_prob}
        batch_size: 16
        shuffle: false
        num_samples: -1
        num_workers: 2
        drop_last: false
        pin_memory: false
      optim:
        name: adamw
        lr: 3.0e-05
        weight_decay: 0.0
        sched:
          name: CosineAnnealing
          warmup_steps: null
          warmup_ratio: 0.1
          min_lr: 0.0
          last_epoch: -1
    exp_manager:
      exp_dir: /NeMo/experiment
      name: PretrainingBERTFromText
      create_tensorboard_logger: true
      create_checkpoint_callback: true
    
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
[NeMo I 2023-01-12 06:41:36 exp_manager:361] Experiments will be logged at /NeMo/experiment/PretrainingBERTFromText/2023-01-12_06-41-36
[NeMo I 2023-01-12 06:41:36 exp_manager:766] TensorboardLogger has been set up
[NeMo W 2023-01-12 06:41:36 exp_manager:1053] The checkpoint callback was told to monitor a validation value and trainer's max_steps was set to 7000. Please ensure that max_steps will run for at least 1 epochs to ensure that checkpointing will not error out.
Error executing job with overrides: []
Traceback (most recent call last):
  File "bert_pretraining.py", line 31, in main
    bert_model = BERTLMModel(cfg.model, trainer=trainer)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/nlp/models/language_modeling/bert_lm_model.py", line 70, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/modelPT.py", line 138, in __init__
    self.setup_training_data(self._cfg.train_ds)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/nlp/models/language_modeling/bert_lm_model.py", line 200, in setup_training_data
    if self.tokenizer is None
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1504, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BERTLMModel' object has no attribute 'tokenizer'
