### ISSUE TITLE
Domain language adaptation functionality in Nemo

### ISSUE THREAD

**Issue by manjuke** [NVIDIA/NeMo#5793]
Hi All, 
I wanted to adapt some specific domain text to a model trained on Generic datasets. In Kaldi, this is done by adding more domain data to LM and use it during decoding. 

Is it this similar in Nemo too, like building a LM by adding domain specific text data & generic training text data together, then use this LM at the time of decoding? Or any other specific Nemo feature/ functionality that provide better support to accomplish this?
Thanks

**Comment by titu1994** [comment]
Please refer to our docs. We have a section for LM use with ASR inference, including how to build your own kenlm.

**Comment by manjuke** [comment]
Sure, Thanks for your quick response.

**Comment by manjuke** [comment]
I had referred Nvidia documentation available at https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html . I have a understanding the use of "Neural Rescoring" approach might solve my issue of adaptation of domain text (on top of existing LM). Please confirm, if this is correct.
Or Pls suggest, if there is some other better method for doing such adaptation. 
Also, to build "TransformerLMModel" should I use domain specific adaption text, or the training text used for training nemo model. Thanks

**Comment by titu1994** [comment]
Most of the adaptation process is just using an LM that is trained on text that matches your domain. Rescoring will help further, but is not really a major source of improvement by itself if the base LM is not trained on appropriate domain you need to perform inference on

**Comment by manjuke** [comment]
Sure, Thank you @titu1994

**Comment by uni-manjunath-ke** [comment]
Hi @titu1994, I was just exploring neural rescorer. I understand we need to build a TransformerLMModel. To train this should I use only domain text, or only training text datasets, or any generic text in that language?
Or can I simply use pretrained transformer LM available for that language (path to .nemo file of the LM or the name of a HF pretrained model)?
or pls suggest what should be input passed to "lm_model" arguement?
Because, I already would have built a kenlm LM using training datasets, which would be used as input to scripts/asr_language_modeling/neural_rescorer/eval_neural_rescorer.py script along-with TransformerLMModel.
Pls suggest. Thanks

**Comment by uni-manjunath-ke** [comment]
Hi @titu1994 / @okuchaiev , Pls suggest something on this. Thanks.

**Comment by titu1994** [comment]
You can do language adaptation with kenlm. Rescoring only helps slightly. Use all the text, original and new domain together to train your kenlm and transformer LM

**Comment by uni-manjunath-ke** [comment]
Thanks @titu1994 . I tried building a transformer LM model for it's use in eval_neural_rescorer.py using 
python examples/nlp/language_modeling/transformer_lm.py   -cn transformer_lm_config   trainer.devices=2   trainer.accelerator='gpu'   +exp_manager.exp_dir=/transformerLM/results   +exp_manager.create_checkpoint_callback=True   +exp_manager.checkpoint_callback_params.monitor=val_PPL   +exp_manager.checkpoint_callback_params.mode=min   +exp_manager.checkpoint_callback_params.save_top_k=5   model.train_ds.file_name=/transformerLM/train.txt   model.validation_ds.file_name=/transformerLM/dev.txt model.tokenizer.tokenizer_model=/transformerLM/results/yttm_model model.test_ds.file_name=/transformerLM/test.txt"

But, I get below error:
================================
Traceback (most recent call last):
  File "/hindi/NeMo-main/examples/nlp/language_modeling/transformer_lm.py", line 35, in <module>
    main()
  File "/hindi/NeMo-main/nemo/core/config/hydra_runner.py", line 104, in wrapper
    _run_hydra(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/hindi/NeMo-main/examples/nlp/language_modeling/transformer_lm.py", line 30, in main
    transformer_lm = TransformerLMModel(cfg.model, trainer=trainer)
  File "/hindi/NeMo-main/nemo/collections/nlp/models/language_modeling/transformer_lm_model.py", line 93, in __init__
    use_transformer_init=cfg.head.use_transformer_init,
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/_utils.py", line 741, in format_and_raise
    _raise(ex, cause)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 465, in _get_node
    self._validate_get(key)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 166, in _validate_get
    self._format_and_raise(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/<user>/anaconda3/envs/wv/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'use_transformer_init' is not in struct
    full_key: head.use_transformer_init
    object_type=dict
    ==========================================================
    
I tried downgrading omegaconf to 2.0.0 from 2.1.2. But, it did not succed as hydra-core needs omegaconf = 2.1.2 to work.
Please suggest. Thanks
