### ISSUE TITLE
[Bug] Cannot import C++ compiled "helpers"

### ISSUE THREAD

**Issue by dat-browny** [NVIDIA/NeMo#6158]
I had run the the megatron_gpt_pretraining.py file completely success yesterday, by using NeMo v1.11.0 and apex nmv1.11.0, but about 10 hours ago I changed some config to export to .nemo on exp argument, then I met this error. 
```output
Traceback (most recent call last):
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 420, in _build_index_mappings
		    from nemo.collections.nlp.data.language_modeling.megatron import helpers
		ImportError: cannot import name 'helpers' from 'nemo.collections.nlp.data.language_modeling.megatron' (/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/__init__.py)
		
		During handling of the above exception, another exception occurred:
		
		Traceback (most recent call last):
		  File "/root/NeMo/examples/nlp/language_modeling/megatron_gpt_pretraining.py", line 89, in main
		    trainer.fit(model)
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
		    self._call_and_handle_interrupt(
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
		    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
		    return function(*args, **kwargs)
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
		    results = self._run(model, ckpt_path=self.ckpt_path)
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1172, in _run
		    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1492, in _call_setup_hook
		    self._call_lightning_module_hook("setup", stage=fn)
		  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
		    output = fn(*args, **kwargs)
		  File "/root/NeMo/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py", line 601, in setup
		    self.build_train_valid_test_datasets()
		  File "/root/NeMo/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py", line 516, in build_train_valid_test_datasets
		    self._train_ds, self._validation_ds, self._test_ds = build_train_valid_test_datasets(
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 81, in build_train_valid_test_datasets
		    train_ds, valid_ds, test_ds = _build_train_valid_test_datasets(
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 168, in _build_train_valid_test_datasets
		    train_dataset = build_dataset(0, 'train')
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 154, in build_dataset
		    dataset = GPTDataset(
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 220, in __init__
		    self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
		  File "/root/NeMo/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py", line 422, in _build_index_mappings
		    raise ImportError(
		ImportError: Could not compile megatron dataset C++ helper functions and therefore cannot import helpers python file.
```
Note that I run this file on Google Colab with GPU, with Cuda 11.8 (try to downgrade to 11.7 but not success, but still successful for first training), tokenizer with SentencePiece, and guarantee that the code does not change at the second time training.

Moreover, the [Migrating from Megatron-LM](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/nemo_megatron/mlm_migration.html) especially file megatron_lm_ckpt_to_nemo.py the does not run successfully. After training complete, I want change file from .ckpt to .nemo, i met the error "Default process group has not been initialized, please make sure to call init_process_group"
This is my code
```python
!python /root/NeMo/examples/nlp/language_modeling/megatron_lm_ckpt_to_nemo.py \
  --checkpoint_folder './NeMo-Deploying/nemo_experiments/megatron_gpt/checkpoints' \
  --checkpoint_name megatron_gpt--val_loss=4.78-step=300-consumed_samples=57600.0 \
  --nemo_file_path './NeMo-Deploying/GPT-Pretrain/megatron_gpt_122m_bs1.nemo' \
  --model_type gpt \
  --tensor_model_parallel_size 1 
``` 
Can you check my above piece of code then it had any problem to this error?

**Comment by titu1994** [comment]
Could you try a newer NeMo version? The most recent is NeMo 1.16.0. Fyi @okuchaiev

**Comment by dat-browny** [comment]
I had try the newest NeMo version but it had some conflict with apex, this make I can not training the megatron_gpt_pretraining.py. So the version i mentioned can run successfully. Or can you recommend the newest version that the NeMo and apex that matching with the python 3.8 or 3.9 with Ubuntu 20.04 Focal.

**Comment by okuchaiev** [comment]
please probably need to re-install apex. I'd recommend you: (1) either use our docker container or (2) create a fresh conda environment and follow instructions on https://github.com/NVIDIA/NeMo/tree/v1.16.0 README and install that specific apex version.

**Comment by FeixLiu** [comment]
Encounter with same problems on the newest NeMo, with CUDA 118 and python 38. The apex was complied from source code. Is there some updated solutions? THX.

**Comment by ericharper** [comment]
Hi, do you see this file: `helpers.cpython-38-x86_64-linux-gnu.so`
in `NeMo/nemo/collections/nlp/data/language_modeling/megatron` ? If not, please run `make` to make sure it can compile.

**Comment by ericharper** [comment]
Please try prepending this to the conversion script command:
```
python -m torch.distributed.launch --nproc_per_node=<tensor_model_parallel_size> megatron_lm_ckpt_to_nemo.py
```

**Comment by FeixLiu** [comment]
Solve my prob by changing the python-config to the absolute path in the Makefile for the dataset.

**Comment by ericharper** [comment]
@FeixLiu , could you post the code change you made?

**Comment by FeixLiu** [comment]
Of course. https://github.com/NVIDIA/NeMo/blob/v1.16.0/nemo/collections/nlp/data/language_modeling/megatron/Makefile#L18, just change the `python3-config` to the absolute path to the python3-config.
