### ISSUE TITLE
error in making tokenizer

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#6439]
Hi, I wanna fine-tune the multilingual model. For this purpose, I downloaded a pre-trained english model.
Now according to the tutorials in your repository, first of all we should train the tokenizer. I want to train spe bpe.
I made manifest files like the manifest exists in tutorial and run the code like you said.
But when I run the code, I encounter the below error:

'''
trainer_interface.cc(350) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(181) LOG(INFO) Loading corpus: /home/multilingual/dataset/deepmine_voices/text_corpus/document.txt
trainer_interface.cc(406) LOG(INFO) Loaded all 0 sentences
trainer_interface.cc(422) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(427) LOG(INFO) Normalizing sentences...
Traceback (most recent call last):
  File "NeMo/scripts/tokenizers/process_asr_text_tokenizer.py", line 323, in <module>
    main()
  File "NeMo/scripts/tokenizers/process_asr_text_tokenizer.py", line 301, in main
    tokenizer_path = __process_data(
  File "NeMo/scripts/tokenizers/process_asr_text_tokenizer.py", line 246, in __process_data
    tokenizer_path, vocab_path = create_spt_model(
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/common/tokenizers/sentencepiece_tokenizer.py", line 372, in create_spt_model
    sentencepiece.SentencePieceTrainer.Train(cmd)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 945, in _Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 923, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
RuntimeError: Internal: src/trainer_interface.cc(428) [!sentences_.empty()]
'''

I want to fine-tune it on a persian dataset.
Could you please help me to solve this problem?

**Comment by alexandercesarr** [comment]
that was my fault I think. In manifest file I put the text in quotation but I shouldn't do that.

**Comment by alexandercesarr** [comment]
@titu1994
