### ISSUE TITLE
Conformer-Transducer Small and Medium models give ERROR: omegaconf.errors.ConfigAttributeError: Key 'att_context_size' is not in struct

### ISSUE THREAD

**Issue by abarcovschi** [NVIDIA/NeMo#6606]
**Describe the bug**
I am getting an error when running inference on a test dataset using the Conformer-Transducer [Small](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_small) and [Medium](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_medium) models downloaded from NGC. I do not get receive this issue when using the [Large](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_large), [XLarge](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_xlarge) and [XXLarge](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_xxlarge) models. However, since I am interested in running inference on embedded devices, I would like to use the Small and Medium models more than the Large ones.

The error is as follows:
```
Traceback (most recent call last):
  File "transcribe_speech.py", line 327, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/config/hydra_runner.py", line 105, in wrapper
    _run_hydra(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "transcribe_speech.py", line 200, in main
    asr_model, model_name = setup_model(cfg, map_location)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/parts/utils/transcribe_utils.py", line 191, in setup_model
    asr_model.change_attention_model(
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/parts/mixins/mixins.py", line 426, in change_attention_model
    self.encoder.change_attention_model(self_attention_model, att_context_size, update_config, self.device)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/modules/conformer_encoder.py", line 841, in change_attention_model
    att_context_size = self._cfg.att_context_size
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 820, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'att_context_size' is not in struct
    full_key: att_context_size
    object_type=dict
```

**Steps/Code to reproduce bug**
The main script I am trying to run is https://github.com/NVIDIA/NeMo/blob/main/examples/asr/transcribe_speech.py with the following command line call:
```
OC_CAUSE=1 HYDRA_FULL_ERROR=1 python3 transcribe_speech.py model_path=/workspace/nemo/non-finetuned/models/stt_en_conformer_transducer_small.nemo dataset_manifest=/workspace/datasets/myst_w2v2_asr/test_manifest.json output_filename=/workspace/nemo/non-finetuned/results/stt_en_conformer_transducer_xxlarge_myst_test_predictions.json batch_size=8 cuda=1 amp=True
```

**Expected behavior**

Expected to receive the following successful output, just like when using Conformer-Transducer Large models:
```
[NeMo I 2023-05-09 11:12:08 transcribe_utils:235]
    Transcribing 2566 files...

[NeMo I 2023-05-09 11:12:08 transcribe_speech:251] AMP enabled!

Transcribing: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321/321 [02:39<00:00,  2.01it/s]
[NeMo I 2023-05-09 11:14:48 transcribe_speech:305] Finished transcribing 2566 files !
```

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of NeMo install: docker pull nvcr.io/nvidia/nemo:23.02

**Environment details**

I used the latest NeMo docker image as my environment.

**Additional context**

GPU model: Nvidia A6000

**Comment by sam1373** [comment]
This should now be fixed by https://github.com/NVIDIA/NeMo/pull/6608

**Comment by abarcovschi** [comment]
@sam1373 I have updated the code for conformer_encoder.py and mixins.py as per the changes in #6608 but now I get a new error:
```
Error executing job with overrides: ['model_path=/workspace/nemo/non-finetuned/models/stt_en_conformer_transducer_small.nemo', 'dataset_manifest=/workspace/datasets/myst_w2v2_asr/test_manifest.json', 'output_filename=/workspace/nemo/non-finetuned/results/stt_en_conformer_transducer_small_myst_test_predictions.json', 'batch_size=8', 'cuda=1', 'amp=True']
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/modules/conformer_encoder.py", line 419, in __init__
    layer = ConformerLayer(
TypeError: __init__() got an unexpected keyword argument 'global_tokens'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "transcribe_speech.py", line 327, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/config/hydra_runner.py", line 105, in wrapper
    _run_hydra(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "transcribe_speech.py", line 200, in main
    asr_model, model_name = setup_model(cfg, map_location)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/parts/utils/transcribe_utils.py", line 187, in setup_model
    asr_model = imported_class.restore_from(
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/modelPT.py", line 436, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/connectors/save_restore_connector.py", line 239, in restore_from
    loaded_params = self.load_config_and_state_dict(
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/connectors/save_restore_connector.py", line 162, in load_config_and_state_dict
    instance = calling_cls.from_config_dict(config=conf, trainer=trainer)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 507, in from_config_dict
    raise e
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 499, in from_config_dict
    instance = cls(cfg=config, trainer=trainer)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/models/rnnt_bpe_models.py", line 282, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/models/rnnt_models.py", line 56, in __init__
    self.encoder = EncDecRNNTModel.from_config_dict(self.cfg.encoder)
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 468, in from_config_dict
    instance = hydra.utils.instantiate(config=config)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 339, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'nemo.collections.asr.modules.conformer_encoder.ConformerEncoder':
TypeError("__init__() got an unexpected keyword argument 'global_tokens'")
```

**Comment by abarcovschi** [comment]
@sam1373 if I am using NeMo inside a docker container that I pulled via the command "docker pull nvcr.io/nvidia/nemo:23.02", how should I update the container with the bug fix? I tried just copy-pasting the files that got modified by #6608 but I got the error as per my previous comment.

**Comment by sam1373** [comment]
@abarcovschi Can you try checking out the full current main branch? Either that or only change the parts of the files that got modified in the PR, instead of the whole file

**Comment by sam1373** [comment]
I will check the latest container to see what needs to be modified. For now you could also try switching to a slightly earlier container, since these are older models anyway. I think 22.08 should not have this issue

**Comment by abarcovschi** [comment]
@sam1373 I managed to work around this by pulling the Nvidia PyTorch docker image and installing NeMo in the PyTorch container via the following:
```
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]
```

However, unfortunately I get a new error now:
```
Exception has occurred: ConfigAttributeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Key 'decoding' not in 'TranscriptionConfig'
    full_key: decoding
    object_type=TranscriptionConfig
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/_utils.py", line 820, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.8/dist-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/parts/utils/transcribe_utils.py", line 293, in write_transcription
    assert cfg.decoding.beam.return_best_hypothesis, "Works only with return_best_hypothesis=true"
  File "/workspace/nemo/transcribe_speech.py", line 316, in main
    output_filename = write_transcription(
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/usr/local/lib/python3.8/dist-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/config/hydra_runner.py", line 105, in wrapper
    _run_hydra(
  File "/workspace/nemo/transcribe_speech.py", line 330, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
omegaconf.errors.ConfigAttributeError: Key 'decoding' not in 'TranscriptionConfig'
    full_key: decoding
    object_type=TranscriptionConfig
```

**Comment by sam1373** [comment]
Based on this error I think you're using new code with the old container

**Comment by titu1994** [comment]
You have to update your container to use the newer code,  NeMo does not have forward compatibility

**Comment by abarcovschi** [comment]
I wasn't sure how to update the code in a NeMo container. Would you recommend using a PyTorch container and installing the latest NeMo code from the main branch inside the container?

**Comment by titu1994** [comment]
The current latest Nemo container is Nemo:23.02 g

**Comment by abarcovschi** [comment]
The NeMo:23.02 container is based on the stable release version of the NeMo GitHub repo that does not include bug fixes #6608 hence running transcribe_speech.py will result in the same error as originally described. The only solution I see is to build a Nvidia PyTorch container and install NeMo main branch manually inside the PyTorch container. I have tried this and I get a new `Key 'decoding' not in 'TranscriptionConfig'` error instead.

**Comment by titu1994** [comment]
On a fresh container from main branch, you get the decoding error ? Can you post the full stack trace please ?

**Comment by abarcovschi** [comment]
In a fresh nvcr.io/nvidia/pytorch:23.03-py3 container with latest NeMo main branch installed, running `python3 transcribe_speech.py model_path=/workspace/nemo/non-finetuned/models/stt_en_conformer_transducer_small.nemo dataset_manifest=/workspace/datasets/myst_w2v2_asr/test_manifest.json output_filename=/workspace/nemo/non-finetuned/results/predictions_test.json` results in the following error:
```
[NeMo I 2023-05-11 10:12:55 transcribe_utils:233] 
    Transcribing 2566 files...
    
Transcribing: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 81/81 [01:17<00:00,  1.04it/s]
[NeMo I 2023-05-11 10:14:12 transcribe_speech:308] Finished transcribing 2566 files !
[NeMo I 2023-05-11 10:14:12 transcribe_speech:309] Writing transcriptions into file: /workspace/nemo/non-finetuned/results/predictions_test.json
Error executing job with overrides: ['model_path=/workspace/nemo/non-finetuned/models/stt_en_conformer_transducer_small.nemo', 'dataset_manifest=/workspace/datasets/myst_w2v2_asr/test_manifest.json', 'output_filename=/workspace/nemo/non-finetuned/results/predictions_test.json']
Traceback (most recent call last):
  File "transcribe_speech.py", line 316, in main
    output_filename = write_transcription(
  File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/parts/utils/transcribe_utils.py", line 293, in write_transcription
    assert cfg.decoding.beam.return_best_hypothesis, "Works only with return_best_hypothesis=true"
omegaconf.errors.ConfigAttributeError: Key 'decoding' not in 'TranscriptionConfig'
    full_key: decoding
    object_type=TranscriptionConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

The transcriptions seemingly have been completed, but an output JSON file is not created due to the error.

**Comment by titu1994** [comment]
Just to confirm, you're using the script inside main branch along with the container from main branch built in the last 6-7 hours ? Main files are subject to change - only release branches are stable. So you'll need to manually update your scripts folder to keep up with your container - https://github.com/NVIDIA/NeMo/blob/main/examples/asr/transcribe_speech.py (last updated 8 hours ago)

**Comment by abarcovschi** [comment]
Yes that is correct. I just realised I was using an older version of transcribe_speech.py from the latest stable release, but I now ran the latest script from the main branch, and I now receive the following error:
```

```
However on a positive note, the output JSON file does get created successfully!

**Comment by stevehuang52** [comment]
The `wer` error will be fixed by this PR https://github.com/NVIDIA/NeMo/pull/6633, @titu1994 please review

**Comment by titu1994** [comment]
Merged the fix thanks @stevehuang52 !

**Comment by abarcovschi** [comment]
Looks like changes done by #6608 aren't included in r1.18.0 because when I run transcribe_speech.py after installing r1.18.0 in a pytorch container I get the same `Key 'att_context_size' is not in struct` error.

**Comment by VahidooX** [comment]
Merged the fix into r1.18 here:
https://github.com/NVIDIA/NeMo/pull/6635

**Comment by titu1994** [comment]
Thanks for helping us verify the fix !
