### ISSUE TITLE
ModuleNotFoundError: No module named 'ctc_decoders'

### ISSUE THREAD

**Issue by marziye-A** [NVIDIA/NeMo#6690]
hello
while using eval_beamsearch_ngram.py , i face the following error:
"
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/modules/beam_search_decoder.py", line 64, in __init__
    from ctc_decoders import Scorer, ctc_beam_search_decoder_batch
ModuleNotFoundError: No module named 'ctc_decoders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/azad2/NeMo/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py", line 393, in main
    candidate_wer, candidate_cer = beam_search_eval(
  File "/home/azad2/NeMo/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py", line 185, in beam_search_eval
    _, beams_batch = model.decoding.ctc_decoder_predictions_tensor(
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/metrics/wer.py", line 418, in ctc_decoder_predictions_tensor
    hypotheses_list = self.decoding(
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/ctc_beam_decoding.py", line 166, in __call__
    return self.forward(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/core/classes/common.py", line 1087, in __call__
    outputs = wrapped(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/ctc_beam_decoding.py", line 280, in forward
    hypotheses = self.search_algorithm(prediction_tensor, out_len)
  File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/parts/submodules/ctc_beam_decoding.py", line 329, in default_beam_search
    self.default_beam_scorer = BeamSearchDecoderWithLM(
  File "/root/anaconda3/lib/python3.10/site-packages/nemo/collections/asr/modules/beam_search_decoder.py", line 66, in __init__
    raise ModuleNotFoundError(
ModuleNotFoundError: BeamSearchDecoderWithLM requires the installation of ctc_decoders from scripts/asr_language_modeling/ngram_lm/install_beamsearch_decoders.sh

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
"
even though i have run install_bemsearch_decoders.py.
does any one know whats the problem?
is there any other way to install "ctc_decoders"?

**Comment by karpnv** [comment]
You are using Python 3.10 but for NeMo Python 3.8 is recommended.
You can try this script on latest main branch

`# make NeMo venv
conda create --name nemo python==3.8.10
conda activate nemo

# install NeMo
sudo apt-get update && apt-get install -y libsndfile1 ffmpeg
git clone https://github.com/NVIDIA/NeMo
cd NeMo
./reinstall.sh

# install ctc-decoders
./scripts/asr_language_modeling/ngram_lm/install_beamsearch_decoders.sh $(pwd)`
