### ISSUE TITLE
inference.compute_logprob=True fails

### ISSUE THREAD

**Issue by arendu** [NVIDIA/NeMo#6881]
**Describe the bug**

setting compute_logprob=Ture in the megatron_gpt_eval.py script is failing.

**Steps/Code to reproduce bug**
1. checkout main
2. Run ```python examples/nlp/language_modeling/megatron_gpt_eval.py gpt_model_file=path_to_nemo_gpt_model/megatron_gpt.nemo 'prompts=[How to fix GPU memory? A:]' tensor_model_parallel_size=1 inference.tokens_to_generate=32 trainer.precision=16 inference.compute_logprob=True```

This is the error:
```
Traceback (most recent call last):
  File "examples/nlp/language_modeling/megatron_gpt_eval.py", line 273, in main
    response = model.generate(
  File "/home/adithyare/NeMo/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py", line 1100, in generate
    return megatron_gpt_generate(self.cuda(), inputs, self.tokenizer, length_params, sampling_params)
  File "/home/adithyare/NeMo/nemo/collections/nlp/modules/common/text_generation_utils.py", line 108, in megatron_gpt_generate
    compute_attention_mask=sampling_params.get("compute_attention_mask", True) ** strategy_args,
TypeError: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'
```

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by arendu** [comment]
addressed by #6882
