### ISSUE TITLE
Inverse Normalization has some issue

### ISSUE THREAD

**Issue by shreerakshaachlady** [NVIDIA/NeMo#6967]
Hi Team,

I am trying latest itn model t5 for inference.(https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/itn_en_t5) 

Getting error as the following:
Error executing job with overrides: ['lang=en', 'mode=itn', 'tagger_pretrained_model=itn_en_t5', 'decoder_pretrained_model=itn_en_t5', 'inference.interactive=False', 'inference.from_file=[sample.txt]']
Traceback (most recent call last):
  File "NeMo/examples/nlp/duplex_text_normalization/duplex_text_normalization_infer.py", line 78, in main
    normalizer_electronic = ElectronicNormalizer(input_case="cased", lang=lang, deterministic=True)
  File "/home/ubuntu/NeMo/examples/nlp/duplex_text_normalization/nn_wfst/en/electronic/normalize.py", line 46, in __init__
    self.tagger = ClassifyFst(
  File "/home/ubuntu/NeMo/examples/nlp/duplex_text_normalization/nn_wfst/en/electronic/tokenize_and_classify.py", line 66, in __init__
    electonic_graph = ElectronicFst(deterministic=deterministic).fst
TypeError: __init__() missing 1 required positional argument: 'cardinal'

Is it the issue with the "nemo_text_processing" package?or version mismatch of other packages?

**Comment by Qairad21** [comment]
gh repo clone NVIDIA/NeMo

**Comment by EmreOzkose** [comment]
Hi @shreerakshaachlady , have you solved this problem ? I am facing the same one.
