### ISSUE TITLE
How to avoid downloading from huggingface

### ISSUE THREAD

**Issue by tinctura13** [NVIDIA/NeMo#7035]
**Describe the bug**
I've made fine-tuning custom Bert model from huggingface for TokenClassification, saved the best checkpoint as .nemo file as the result.
Then I want to load that checkpoint for model inference 
```
model = TokenClassificationModel.restore_from("/tmp/model/best_ckpt.nemo")
```
but at first nemo downloads the original model from HF 
```
[NeMo W 2023-07-14 03:24:30 lm_utils:80] ai-forever/ruBert-large is not in get_pretrained_lm_models_list(include_external=False), will be using AutoModel from HuggingFace.
Downloading: 100%|██████████| 1.71G/1.71G [01:12<00:00, 23.5MB/s] 
```
and only then restores it from the checkpoint. 
```
[NeMo I 2023-07-14 03:26:04 save_restore_connector:247] Model TokenClassificationModel was successfully restored from /tmp/model/best_ckpt.nemo
```
Is it necessary do download the original model from HF? I can't find the way to avoid it

**Comment by titu1994** [comment]
You can probably do `TRANSFORMERS_OFFLINE=1` on the second run.

**Comment by tinctura13** [comment]
I've added `export TRANSFORMERS_OFFLINE=1`
And now I have this error
```
[NeMo W 2023-07-14 05:21:31 nemo_logging:349] /opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py:41: LightningDeprecationWarning: `pytorch_lightning.utilities.cloud_io.load` has been deprecated in v1.8.0 and will be removed in v2.0.0. This function is internal but you can copy over its implementation.
|       rank_zero_deprecation(
nfer_1      |     
| Traceback (most recent call last):
|   File "/srv/src/srv.py", line 103, in <module>
|     model = TokenClassificationModel.load_from_checkpoint(checkpoint_path="/tmp/model/best_ckpt.nemo")
|   File "/opt/conda/lib/python3.8/site-packages/nemo/collections/nlp/models/nlp_model.py", line 318, in load_from_checkpoint
|     checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
|   File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 45, in load
|     return new_load(*args, **kwargs)
|   File "/opt/conda/lib/python3.8/site-packages/lightning_fabric/utilities/cloud_io.py", line 48, in _load
|     return torch.load(f, map_location=map_location)
|   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
|     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
|   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 905, in _legacy_load
|     return legacy_load(f)
|   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 802, in legacy_load
|     tar.extract('storages', path=tmpdir)
|   File "/opt/conda/lib/python3.8/tarfile.py", line 2060, in extract
|     tarinfo = self.getmember(member)
|   File "/opt/conda/lib/python3.8/tarfile.py", line 1782, in getmember
|     raise KeyError("filename %r not found" % name)
| KeyError: "filename 'storages' not found"
```
I've checked the file `"/tmp/model/best_ckpt.nemo"` it's in place, not corrupted and can be extracted with tar (and it also works when nemo downloads the model from HF and then restore the state from that same file)
Any ideas how to fix this?

**Comment by titu1994** [comment]
Ok Nemo requires the model to be downloaded. Order of operations is as follows - build hf model, load it's hf state dict, add softmax head, load state dict from Nemo file, override state dict of HF with Nemo. 

So model first needs to be built by HF which requires internet at least one time to build the cache
