### ISSUE TITLE
ValueError: A NMTensor was produced twice in the same DAG

### ISSUE THREAD

**Issue by OndrejGl** [NVIDIA/NeMo#711]
I am getting the following error when training the Quartznet 15x5 model. It shows just after I get Loss is NaN or inf... Any idea where to look?  Do the nan loss warning and the error relate?

Thanks
...
[NeMo W 2020-06-05 23:23:22 actions:1580] Loss is NaN or inf. Skipping update.
Traceback (most recent call last):
  File "/home/ogl/src/NeMo/examples/asr/quartznet_ondra.py", line 282, in <module>
    main()
  File "/home/ogl/src/NeMo/examples/asr/quartznet_ondra.py", line 277, in main
    synced_batchnorm_groupsize=args.synced_bn_groupsize,
  File "/home/ogl/src/NeMo/nemo/core/neural_factory.py", line 340, in train
    amp_max_loss_scale=amp_max_loss_scale,
  File "/home/ogl/src/NeMo/nemo/backends/pytorch/actions.py", line 1561, in train
    call_chain=curr_call_chain, registered_tensors=self._training_state.tensor_dict,
  File "/home/ogl/src/NeMo/nemo/backends/pytorch/actions.py", line 376, in __nm_graph_forward_pass
    raise ValueError(f"A NMTensor was produced twice in the same DAG. {t_name}")
ValueError: A NMTensor was produced twice in the same DAG. processed_signal~~~audiotomelspectrogrampreprocessor0~~~ea72adea-75a9-46dd-86bf-c9269e6b564f
...

**Comment by OndrejGl** [comment]
I pulled new version yesterday and the problem seems to have disappeared - my training has been flawlessly running since then.

**Comment by okuchaiev** [comment]
thank you for confirmation. closing
