### ISSUE TITLE
ValueError: use_cache was set, but cache was empty

### ISSUE THREAD

**Issue by WillQuCD** [NVIDIA/NeMo#755]
I use same docker image. It was working well on other servers, but got this error on the new server when I was doing ASR jasper_eval.py.

Traceback (most recent call last):
  File "jasper_eval.py", line 204, in <module>
    main()
  File "jasper_eval.py", line 178, in main
    verbose=False
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 721, in infer
    modules_to_restore=modules_to_restore)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 1589, in infer
    offload_to_cpu=offload_to_cpu)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 738, in _infer
    raise ValueError("use_cache was set, but cache was empty")
ValueError: use_cache was set, but cache was empty

**Comment by WillQuCD** [comment]
Fixed! 
It is because the input --eval_dataset file is empty.
2020-06-20 08:24:40,423 - INFO - Dataset loaded with 0.00 hours. Filtered 0.00 hours.
