### ISSUE TITLE
How to continue finetuning of .nemo model from 768th epoch?

### ISSUE THREAD

**Issue by mukherjeesougata** [NVIDIA/NeMo#7932]
I am using https://github.com/Open-Speech-EkStep/vakyansh-nemo-experimentation/blob/main/src/finetuning/speech_to_text_ctc_bpe.py to finetune. Due to power cut the process stopped after 768 epochs. So, I want to continue training the .nemo model from the 768th epoch. What extra arguments shall I pass 
to speech_to_text_ctc_bpe.py for that?
My .sh file is as follows:-
```
if [[ ${tokenizer_type}=bpe ]]; then

CUDA_VISIBLE_DEVICES=3,4 python /home/conformer/vakyansh-nemo-experimentation/src/finetuning/speech_to_text_ctc_bpe.py \
     --config-path=${config_path} \
     --config-name=${config_name} \
    model.train_ds.manifest_filepath=${train_manifest_path} \
    model.validation_ds.manifest_filepath=${valid_manifest_path} \
    model.test_ds.manifest_filepath=${test_manifest_path} \
    model.tokenizer.dir=${tokenizer_dir} \
    model.tokenizer.type=${tokenizer_type} \
    trainer.devices=-1 \
    trainer.accelerator="gpu" \
    trainer.strategy="ddp" \
    exp_manager.resume_if_exists=true \
    exp_manager.resume_ignore_no_checkpoint=true \
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name=${wandb_run_name} \
    exp_manager.wandb_logger_kwargs.project=${wandb_project_name} \
    +init_from_pretrained_model=${pretrained_model}

fi
```
```[tasklist]
### Tasks
```

**Comment by mukherjeesougata** [comment]
@okuchaiev a gentle reminder for the same

**Comment by titu1994** [comment]
If you have the two resume flags set, simply calling the script multiple times with the same paths will be sufficient

**Comment by mukherjeesougata** [comment]
Yes, I have tried that but it is restarting from the 0th epoch.

**Comment by titu1994** [comment]
Please check the folder called nemo_experiments and if it has a folder inside it which contains logs and a checkpoints dir, then add the following line to your training script 

exp_manager.explicit_log_dir=<prefix>/nemo_experiments/<name of the folder>

In the future you can add exp_manager.name="xyz" in order for NeMo to automatically detect the folder.

**Comment by RobinDong** [comment]
Try
```
++exp_manager.resume_from_checkpoint="<path of your .nemo file>"
```

**Comment by mukherjeesougata** [comment]
> exp_manager.resume_from_checkpoint
I have used the following .sh script :
```
if [[ ${tokenizer_type}=bpe ]]; then

CUDA_VISIBLE_DEVICES=3,4 python /home/conformer/vakyansh-nemo-experimentation/src/finetuning/speech_to_text_ctc_bpe.py \
     --config-path=${config_path} \
     --config-name=${config_name} \
    model.train_ds.manifest_filepath=${train_manifest_path} \
    model.validation_ds.manifest_filepath=${valid_manifest_path} \
    model.test_ds.manifest_filepath=${test_manifest_path} \
    model.tokenizer.dir=${tokenizer_dir} \
    model.tokenizer.type=${tokenizer_type} \
    trainer.devices=-1 \
    trainer.accelerator="gpu" \
    trainer.strategy="ddp" \
    exp_manager.resume_if_exists=true \
    exp_manager.resume_ignore_no_checkpoint=true \
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name=${wandb_run_name} \
    exp_manager.wandb_logger_kwargs.project=${wandb_project_name} \
    +exp_manager.explicit_log_dir=${ckpt_dir} \
    +init_from_pretrained_model=${pretrained_model}

fi
```
But, it is showing the following error:-
```
Could not override 'exp_manager.explicit_log_dir'.
To append to your config use +exp_manager.explicit_log_dir=/home/conformer/nemo_experiments/Conformer-CTC-BPE/2023-11-22_17-23-06/
Key 'explicit_log_dir' is not in struct
    full_key: exp_manager.explicit_log_dir
    object_type=dict
```

**Comment by mukherjeesougata** [comment]
> Try
> 
> ```
> ++exp_manager.resume_from_checkpoint="<path of your .nemo file>"
> ```
I have also tried with the following .sh script:-
```
if [[ ${tokenizer_type}=bpe ]]; then

CUDA_VISIBLE_DEVICES=3,4 python /home/conformer/vakyansh-nemo-experimentation/src/finetuning/speech_to_text_ctc_bpe.py \
     --config-path=${config_path} \
     --config-name=${config_name} \
    model.train_ds.manifest_filepath=${train_manifest_path} \
    model.validation_ds.manifest_filepath=${valid_manifest_path} \
    model.test_ds.manifest_filepath=${test_manifest_path} \
    model.tokenizer.dir=${tokenizer_dir} \
    model.tokenizer.type=${tokenizer_type} \
    trainer.devices=-1 \
    trainer.accelerator="gpu" \
    trainer.strategy="ddp" \
    exp_manager.resume_if_exists=true \
    exp_manager.resume_ignore_no_checkpoint=true \
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name=${wandb_run_name} \
    exp_manager.wandb_logger_kwargs.project=${wandb_project_name} \
    +init_from_pretrained_model=${pretrained_model} \
    ++exp_manager.resume_from_checkpoint=${ckpt_path}

fi
```
It is showing the following error:-
```
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
    self._loop_check_status(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
    local_handle = request()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 758, in deliver_network_status
    return self._deliver_network_status(status)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _deliver_network_status
    return self._deliver_record(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread IntMsgThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages
    self._loop_check_status(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
    local_handle = request()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 766, in deliver_internal_messages
    return self._deliver_internal_messages(internal_message)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 490, in _deliver_internal_messages
    return self._deliver_record(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by titu1994** [comment]
You can add the key by using the provided instruction - 
 
To append to your config use ++exp_manager.explicit_log_dir=/home/conformer/nemo_experiments/Conformer-CTC-BPE/2023-11-22_17-23-06/

**Comment by mukherjeesougata** [comment]
> You can add the key by using the provided instruction -
> 
> To append to your config use ++exp_manager.explicit_log_dir=/home/conformer/nemo_experiments/Conformer-CTC-BPE/2023-11-22_17-23-06/

It is giving me the following error:-
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread NetStatThr    :
self.run()Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 286, in check_stop_status
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    Exception in thread self._loop_check_status(IntMsgThr
    :
self._target(*self._args, **self._kwargs)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
    local_handle = request()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 750, in deliver_stop_status
        self._loop_check_status(self.run()    

return self._deliver_stop_status(status)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 468, in _deliver_stop_status
    local_handle = request()    
self._target(*self._args, **self._kwargs)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 758, in deliver_network_status

    return self._deliver_record(record)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    return self._deliver_network_status(status)    
self._loop_check_status(  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _deliver_network_status

    handle = mailbox._deliver_record(record, interface=self)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status

      File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
return self._deliver_record(record)    
local_handle = request()  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    
interface._publish(record)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 766, in deliver_internal_messages
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    handle = mailbox._deliver_record(record, interface=self)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
        return self._deliver_internal_messages(internal_message)self._sock_client.send_record_publish(record)
    
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 490, in _deliver_internal_messages
interface._publish(record)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    return self._deliver_record(record)    
    self.send_server_request(server_req)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
self._sock_client.send_record_publish(record)

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    handle = mailbox._deliver_record(record, interface=self)
    self._send_message(msg)
      File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
self.send_server_request(server_req)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    interface._publish(record)
        self._sendall_with_error_handle(header + data)self._send_message(msg)  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish


  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sock_client.send_record_publish(record)
    sent = self._sock.send(data)      File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish

self._sendall_with_error_handle(header + data)BrokenPipeError
    :   File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
self.send_server_request(server_req)[Errno 32] Broken pipe

  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe    
self._send_message(msg)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mukherjeesougata** [comment]
This worked for me

> You can add the key by using the provided instruction -
> 
> To append to your config use ++exp_manager.explicit_log_dir=/home/conformer/nemo_experiments/Conformer-CTC-BPE/2023-11-22_17-23-06/
