### ISSUE TITLE
Cannot export NeuralDiarizer (diar_msdd_telephonic.nemo) to onnx

### ISSUE THREAD

**Issue by uro-sh** [NVIDIA/NeMo#8306]
**Describe the bug**

```
Traceback (most recent call last):
  File "/Users/urospetrovic/ml_projects/thq-transcription-module/export.py", line 44, in <module>
    main(args.nemo_file, args.onnx_file, model_type=args.model_type)
  File "/Users/urospetrovic/ml_projects/thq-transcription-module/export.py", line 38, in main
    model.export(onnx_file, onnx_opset_version=12)
  File "/Users/urospetrovic/opt/miniconda3/envs/transcription/lib/python3.10/site-packages/nemo/core/classes/exportable.py", line 113, in export
    out, descr, out_example = model._export(
  File "/Users/urospetrovic/opt/miniconda3/envs/transcription/lib/python3.10/site-packages/nemo/core/classes/exportable.py", line 177, in _export
    input_example = self.input_module.input_example()
  File "/Users/urospetrovic/opt/miniconda3/envs/transcription/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'EncDecDiarLabelModel' object has no attribute 'input_module'. Did you mean: 'output_module'?
```

**Steps/Code to reproduce bug**

I have used this codebase ([convasr_to_single_onnx](https://github.com/NVIDIA/NeMo/blob/v1.0.0b3/scripts/convasr_to_single_onnx.py)), extended by the new type 'diarizer' to be able to handle EncDecDiarLabelModel types.

**Expected behavior**
I was able to successfully convert vad_multilingual_marblenet.nemo to onnx file, but it fails for the diar_msdd_telephonic.nemo one.

**Comment by chidalgoRR** [comment]
this has not been solved i think
