### ISSUE TITLE
Multi-GPU Training on A100 - unhandled system error, NCCL version 2.7.5

### ISSUE THREAD

**Issue by paulhendricks** [NVIDIA/NeMo#833]
Issue: Multi-GPU Training on A100 results in `unhandled system error, NCCL version 2.7.5` on `a2-megagpu-16g` instance on GCP.

Steps to reproduce:

Dockerfile:

```
FROM nvcr.io/nvidia/pytorch:20.06-py3

RUN apt-get update && \
      apt-get install -y libsndfile1 ffmpeg && \
      pip install Cython

RUN cd /workspace && git clone https://github.com/NVIDIA/NeMo.git
RUN cd /workspace/NeMo && \
      bash reinstall.sh

WORKDIR /workspace/NeMo

CMD ["bash"]
```

Build container:

```
docker build -t nemo .
```

Run and step into container:

```
docker run \
  --runtime nvidia \
  --rm -it \
  --shm-size=16g \
  -p 8888:8888 \
  -p 6006:6006 \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  nemo bash
```

Download data:

```
cd examples/nlp/language_modeling

bash get_wkt2.sh data
```

Kick off BERT Pre-training (single node, single GPU) - **works just fine**:

```
python bert_pretraining.py \
  --train_data data/wikitext-2/train.txt \
  --eval_data data/wikitext-2/valid.txt \
  data_text
```

Kick off BERT Pre-training (single node, multi GPU):

```
python -m torch.distributed.launch \
  --nproc_per_node=16 \
  bert_pretraining.py \
  --num_gpus=16
  --train_data data/wikitext-2/train.txt \
  --eval_data data/wikitext-2/valid.txt \
  data_text
```

```
root@66354601f07f:/workspace/NeMo/examples/nlp/language_modeling# python -m torch.distributed.launch \
>   --nproc_per_node=16 \
>   bert_pretraining.py \
>   --num_gpus=16 \
>   --train_data data/wikitext-2/train.txt \
>   --eval_data data/wikitext-2/valid.txt \
>   data_text

...


Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "bert_pretraining.py", line 246, in <module>
    add_time_to_log_dir=False,
  File "/workspace/NeMo/nemo/core/neural_factory.py", line 193, in __init__
    torch.distributed.all_reduce(cuda_set_t, op=torch.distributed.ReduceOp.MIN)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 938, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:535, unhandled system error, NCCL version 2.7.5
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'bert_pretraining.py', '--local_rank=15', '--num_gpus=16', '--train_data', 'data/wikitext-2/train.txt', '--eval_data', 'data/wikitext-2/valid.txt', 'data_text']' returned non-zero exit status 1.
```

```
root@66354601f07f:/workspace/NeMo/examples/nlp/language_modeling# apt search nccl
Sorting... Done
Full Text Search... Done
libhttpasyncclient-java/bionic 4.1.3-1 all
  HTTP/1.1 compliant asynchronous HTTP agent implementation

libnccl-dev/now 2.7.5-1+cuda11.0 amd64 [installed,local]
  NVIDIA Collectives Communication Library (NCCL) Development Files

libnccl2/now 2.7.5-1+cuda11.0 amd64 [installed,local]
  NVIDIA Collectives Communication Library (NCCL) Runtime

libpuppetlabs-http-client-clojure/bionic 0.9.0-1 all
  Clojure wrapper around libhttpasyncclient-java

libvncclient1/bionic-updates,bionic-security 0.9.11+dfsg-1ubuntu1.2 amd64
  API to write one's own VNC server - client library

libvncclient1-dbg/bionic-updates,bionic-security 0.9.11+dfsg-1ubuntu1.2 amd64
  debugging symbols for libvncclient

python-ncclient/bionic 0.5.3-4 all
  Python library for NETCONF clients (Python 2)

python-ncclient-doc/bionic 0.5.3-4 all
  Documentation for python-ncclient (Python library for NETCONF clients)

python3-ncclient/bionic 0.5.3-4 all
  Python library for NETCONF clients (Python 3)
```

```
$ nvidia-smi
Wed Jul  8 19:11:41 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:00:03.0 Off |                    0 |
| N/A   49C    P0    67W / 400W |      0MiB / 39539MiB |     12%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      On   | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    64W / 400W |      0MiB / 39539MiB |     15%      Default |
|                               |                      |             Disabled |
....
```

**Comment by maksimovkonstantin** [comment]
@paulhendricks have you found any solution? I am facing the same problem((

**Comment by hujian233** [comment]
@maksimovkonstantin  It's a sad problem, and I am facing it too!  I don't know how to solve it
