### ISSUE TITLE
OmegaConf library

### ISSUE THREAD

**Issue by ShabnamRA** [NVIDIA/NeMo#8599]
**Describe the bug**

I am trying to use NeMo. As part of the Model example try to work with config :
`from omegaconf import MISSING
#example:
common_config = OmegaConf.create({
    'vocab_size': MISSING,
    'block_size': MISSING,
    'n_layer': MISSING,
    'n_embd': MISSING,
    'n_head': MISSING,
})`

facing this error when running in Pycharm latest version
`  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219, in run
    self._on_run()
  File "/home/shabs/.pycharm_helpers/pydev/_pydev_bundle/pydev_console_commands.py", line 31, in _on_run
    values.append(pydevd_thrift.var_to_struct(var_obj, name, evaluate_full_value=True, user_type_renderers=self.user_type_renderers))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 313, in var_to_struct
    value = _get_default_var_string_representation(v, _type, typeName, format, do_trim)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 260, in _get_default_var_string_representation
    str_from_provider = _str_from_providers(v, _type, typeName, do_trim)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 197, in str_from_providers
    return provider.get_str(o, do_trim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OmegaConfUserResolver.get_str() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219, in run
    self._on_run()
  File "/home/shabs/.pycharm_helpers/pydev/_pydev_bundle/pydev_console_commands.py", line 31, in _on_run
    values.append(pydevd_thrift.var_to_struct(var_obj, name, evaluate_full_value=True, user_type_renderers=self.user_type_renderers))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 313, in var_to_struct
    value = _get_default_var_string_representation(v, _type, typeName, format, do_trim)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 260, in _get_default_var_string_representation
    str_from_provider = _str_from_providers(v, _type, typeName, do_trim)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shabs/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_thrift.py", line 197, in str_from_providers
    return provider.get_str(o, do_trim)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OmegaConfUserResolver.get_str() takes 2 positional arguments but 3 were given`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version : 2.2.1+cu121
- Python version: 3.11

**Additional context**

Example: GPU model

**Comment by ShabnamRA** [comment]
It was resolved. The issue was Using PyCharm IDE. The latest update on PyCharm resolve the issue.
