### ISSUE TITLE
Error in coverting Mixtral-7B hf checkpoint to Nemo

### ISSUE THREAD

**Issue by YunchaoYang** [NVIDIA/NeMo#8970]
**Describe the bug**
I am trying to run the example run PEFT with Mistral 7B provided in NEVIDI DOCS HUB. When trying to convert  Mistral-7B in huggingface format to nemo format. Got the error message

 ```
python3 /opt/NeMo/scripts/checkpoint_converters/convert_mixtral_hf_to_nemo.py --input_name_or_path=./mistral-7B-hf/ --output_path=mistral.nemo
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[NeMo I 2024-04-18 09:56:50 convert_mixtral_hf_to_nemo:150] loading checkpoint ./mistral-7B-hf/
Loading checkpoint shards: 100%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 2/2 [07:21<00:00, 220.59s/it]
Traceback (most recent call last):
  File "/opt/NeMo/scripts/checkpoint_converters/convert_mixtral_hf_to_nemo.py", line 346, in <module>
    convert(args)
  File "/opt/NeMo/scripts/checkpoint_converters/convert_mixtral_hf_to_nemo.py", line 153, in convert
    nemo_config = load_config(model_args, tokenizer.vocab_file)
  File "/opt/NeMo/scripts/checkpoint_converters/convert_mixtral_hf_to_nemo.py", line 115, in load_config
    nemo_config.num_moe_experts = int(mixtral_config['num_local_experts'])
KeyError: 'num_local_experts'
```

**Steps/Code to reproduce bug**
I am using the ngc container [24.03
](nemo:24.03.framework.sif) . And following the steps listed on this page https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/mistralpeft.html

**Comment by akoumpa** [comment]
Hi, which one do you want to use the mistral-7b or the mixtral-7b? if you want to use the mistral-7b please use convert_mistral_hf_to_nemo.py instead of convert_mixtral_hf_to_nemo.py. Thanks.
