### ISSUE TITLE
Multi-GPU BERT Pre-Training Hangs on V100 & A100

### ISSUE THREAD

**Issue by paulhendricks** [NVIDIA/NeMo#986]
Issue: Multi-GPU Training on V100 or on A100 `a2-megagpu-16g` instance on GCP hangs.

Following this documentation: https://docs.nvidia.com/deeplearning/nemo/developer_guide/en/v0.11.0/nlp/bert_pretraining.html#bert-pretraining

Steps to reproduce:

Dockerfile:

```
FROM nvcr.io/nvidia/pytorch:20.07-py3

RUN apt-get update && apt-get install -y libsndfile1 ffmpeg && \
      pip install Cython

RUN cd /workspace && git clone https://github.com/NVIDIA/NeMo.git
RUN cd /workspace/NeMo && \
      bash reinstall.sh

WORKDIR /workspace/NeMo

CMD ["bash"]
```

Build container:

```
docker build -t nemo .
```

Run and step into container:

```
docker run \
  --gpus all \
  --network host \
  --rm -it \
  --shm-size=16g \
  -p 8888:8888 \
  -p 6006:6006 \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  nemo bash
```

Download data:

```
cd examples/nlp/language_modeling

bash get_wkt2.sh data
```

Kick off BERT Pre-training (single node, single GPU) - **works just fine**:

```
python bert_pretraining.py \
--amp_opt_level "O0" \
--train_data data/wikitext-2/train.txt \
--eval_data data/wikitext-2/valid.txt \
--work_dir outputs/bert_lm \
--batch_size 64 \
--lr 0.01 \
--lr_policy CosineAnnealing \
--lr_warmup_proportion 0.05 \
--optimizer novograd \
--beta1 0.95 \
--beta2 0.25 \
--vocab_size 3200 \
--hidden_size 768 \
--intermediate_size 3072 \
--num_hidden_layers 12 \
--num_attention_heads 12 \
--hidden_act "gelu" \
--save_step_freq 200 \
data_text \
--dataset_name wikitext-2 \
--tokenizer sentence-piece \
--num_epochs 10 \
--sample_size 10000000 \
--mask_probability 0.15 \
--short_seq_prob 0.1
```

Kick off BERT Pre-training (single node, multi GPU):

```
python -m torch.distributed.launch \
  --nproc_per_node=16 \
  bert_pretraining.py \
  --num_gpus=16 \
  --amp_opt_level "O0" \
  --train_data data/wikitext-2/train.txt \
  --eval_data data/wikitext-2/valid.txt \
  --work_dir outputs/bert_lm \
  --batch_size 4 \
  --lr 0.01 \
  --lr_policy CosineAnnealing \
  --lr_warmup_proportion 0.05 \
  --optimizer novograd \
  --beta1 0.95 \
  --beta2 0.25 \
  --vocab_size 3200 \
  --hidden_size 768 \
  --intermediate_size 3072 \
  --num_hidden_layers 12 \
  --num_attention_heads 12 \
  --hidden_act "gelu" \
  --save_step_freq 200 \
  data_text \
  --dataset_name wikitext-2 \
  --tokenizer sentence-piece \
  --num_epochs 10 \
  --sample_size 10000000 \
  --mask_probability 0.15 \
  --short_seq_prob 0.1
```

This results in processes being kicked off, and ultimately hangs after epoch 0. I've attached the full log but included the relevant snippet below:

```
[NeMo I 2020-08-05 15:22:05 deprecated_callbacks:232] Step: 0
[NeMo I 2020-08-05 15:22:05 bert_pretraining:414] Loss: 9.111 MLM Loss: 8.250 NSP Loss: 0.861
[NeMo I 2020-08-05 15:22:05 deprecated_callbacks:247] Step time: 4.48674750328064 seconds
[NeMo I 2020-08-05 15:22:05 deprecated_callbacks:316] Doing Evaluation ..............................
[NeMo I 2020-08-05 15:22:09 lm_bert_callback:65] Dev perplexity: 7948.54
[NeMo I 2020-08-05 15:22:09 deprecated_callbacks:321] Evaluation time: 3.838350772857666 seconds

^C

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    process.wait()
  File "/opt/conda/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by paulhendricks** [comment]
You can find the full log here: [log.txt](https://github.com/NVIDIA/NeMo/files/5029322/log.txt)

**Comment by paulhendricks** [comment]
On the V100, I was able to successfully run multi-GPU runs with 2, 4 GPUs (with batch sizes of 32 and 16 respectively).

However, moving to 8 GPUs with a batch size of 8 results in the same behavior as 16 GPUs with batch size of 4.

I'll try the same on the A100 - perhaps this is just a result of moving to distributed PyTorch with 8 GPUs or more?

I'm also going to explore if this is an issue with the `nvcr.io/nvidia/nemo:v0.11` container.

**Comment by FerchichiNourchene** [comment]
Hello @paulhendricks,
I'm running BERT Pre-training with multiple GPUs on GCP (4 V100) and facing the same issue you have faced: The run hangs after epoch 0. It is using 100% of each one of the GPU memory while I'm only training with a small sample data. 
I have tried multi-GPU runs with 2 and 4 GPUs with different batch sizes with no results. Did you figure out how to fix that?
Here after part of the log where the run gets blocked:

```
[NeMo I 2020-10-01 13:35:52 deprecated_callbacks:232] Step: 0
[NeMo I 2020-10-01 13:35:52 bert_pretraining:273] Loss: 5.397 MLM Loss: 4.865 NSP Loss: 0.532
[NeMo I 2020-10-01 13:35:52 deprecated_callbacks:247] Step time: 0.9880142211914062 seconds
[NeMo I 2020-10-01 13:35:52 deprecated_callbacks:316] Doing Evaluation ..............................
[NeMo I 2020-10-01 13:35:54 lm_bert_callback:65] Dev perplexity: 307.919
[NeMo I 2020-10-01 13:35:54 deprecated_callbacks:321] Evaluation time: 1.753828525543213 seconds
^C^CTraceback (most recent call last):
  File "/opt/tunbert/miniconda3/envs/tunbert-torch/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/opt/tunbert/miniconda3/envs/tunbert-torch/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/opt/tunbert/miniconda3/envs/tunbert-torch/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by FerchichiNourchene** [comment]
```
$ nvidia-smi
     
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    77W / 300W |   3263MiB / 16160MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:05.0 Off |                    0 |
| N/A   38C    P0    60W / 300W |   3193MiB / 16160MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:06.0 Off |                    0 |
| N/A   41C    P0    69W / 300W |   3209MiB / 16160MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:07.0 Off |                    0 |
| N/A   39C    P0    61W / 300W |   3225MiB / 16160MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

**Comment by gvijqb** [comment]
Hi @FerchichiNourchene we are facing the exact same issue but on Tesla A100 multi-gpu training. GPU utilization is at 100% but GPU memory used is around 1GB out of 40GB.  Not sure what's causing this bottleneck. Did you find resolution on this?

**Comment by FerchichiNourchene** [comment]
@gvijqb Hello, what helped me solve this bug was upgrading the Nemo version from 0.11.0 to 1.0.0b1 as it was advised from NVIDIA's team in the following issue #1247 . 
Hope that this will help you as well!
